### ISSUE TITLE
Не поддерживается прозрачность у растровых слоёв

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#107]
В QGIS рисуется как надо:
![image](https://f.cloud.github.com/assets/4630662/2146839/455caf9a-93c8-11e3-9bd2-d1313e45058f.png)
В веб-гис рисуется с чёрными краями, вместо прозрачных:
![image](https://f.cloud.github.com/assets/4630662/2146847/612cc98a-93c8-11e3-82ec-05e80c2cd813.png)

**Comment by dezhin** [comment]
С учетом последних исправлений - думаю все работать должно. Логика сейчас такая, если есть NODATA то при загрузке и перепроецировании используем его, если нет - генерируем альфаканал.
