### ISSUE TITLE
Возможность сокращать ссылки пермалинка

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#113]
В окошке пермалинка нужна галка Short link, при нажатии на которую урл сокращается. Пока может сокращать через какой-нибудь j.mp , тем временем поищу урл для корпоративной сокращалки.

**Comment by dezhin** [comment]
Я думаю мы должны закрыть этот тикет и ничего не предпринимать тут. Какого-то универсального API, которое подходило бы всем - нет, скоращалок этих миллион. Кому нужна аналитика - возьмут то что им нужно и сократят вручную, но я не видел такого "в дикой природе" - все постят как есть и не паряться. Ну и опять таки домен.

Возможно стоит подумать про более компактное кодирование параметров в ссылке веб-карты, но это про другое совсем.
