### ISSUE TITLE
Иконки из QGIS

### ISSUE THREAD

**Issue by dezhin** [nextgis/nextgisweb#122]
Выглядит наша система сейчас крайне убого, я думаю это очевидно всем. Наверное надо какую-то работу в этом направлении проводить.

Один из аспектов этой работы: иконки для разных действий и типов объектов. Я так понимаю многое можно взять из QGIS, судя по тому что нарисовали во 2-й версии там все очень даже ничего.

Поэтому вопрос: кто-нибудь может меня ткнуть в место, где лежат исходники QGIS иконок в SVG?

**Comment by drnextgis** [comment]
Вроде уже не актуально. Закрою.
