### ISSUE TITLE
sudo apt-get install nextgisweb

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#124]
При установке NGW на отдельные сервера, которые передаются заказчику  (или размещены у заказчика - Красногорск) необходимо обеспечить установку всех необходим компонент NGW с последующим их обновлением через стандартные механизмы - apt-get updarade и т.п.

Установка не должна требовать компиляции на сервере у заказчика. Все должно ставиться из тех или иных пакетов. Желательно избегать и девелоперских версий пакетов.

**Comment by drnextgis** [comment]
Больше не актуально.
