### ISSUE TITLE
Identification should be always on

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#133]
На старой системе (Красногорск) был по умолчанию активирован режим идентификации. Просят либо сделать также как было в старой системе, либо в админке сделать выбор какой инструмент будет активирован по-умолчанию

**Comment by simgislab** [comment]
Договорились, что режиме идентификации (клик по карте) должен быть включен всегда, если контекст не перехвачен другим инструментом. При этом раскладе кнопка идентификации не нужна.

Та же самая логика вроде бы следует и для сдвига карты, кнопка сдвиг не нужна.
