### ISSUE TITLE
Упростить просмотр атрибутов

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#135]
Заказчик попросил упростить просмотр атрибутов слоя - вынести пункты меню "слой" в виде кнопок. На скрине приведен пример как он хочет:
![wishes](https://f.cloud.github.com/assets/1708122/2420494/1bdd4ca8-ab72-11e3-97b9-97153eda93a1.png)

**Comment by drnextgis** [comment]
![image](https://github.com/nextgis/nextgisweb/assets/866124/97552cdd-6734-4c79-88fa-ee1ffd5bc948)
