### ISSUE TITLE
Мелкое замечание по дизайну - "создать ресурс" - вкладка mapserver

### ISSUE THREAD

**Issue by taimyr** [nextgis/nextgisweb#142]
Сделать надпись "Импорт стиля QGIS" так, чтоб было ясно, что это именно кнопка, а не просто надпись, а то пока не наведешь на нее курсор - не догадаешься

**Comment by simgislab** [comment]
сейчас так, действительно не очень понятно
![](http://m-d.me/img/ss/20190628_232618.png)

**Comment by simgislab** [comment]
![](http://m-d.me/img/ss/8c9aIPLjbw.png)

либо сделать экшн справа

**Comment by edpop** [comment]
Просто не хватало иконки, которая есть у всех кнопок на панели.
![Снимок экрана от 2020-08-01 03-05-57](https://user-images.githubusercontent.com/13479292/89059123-f7dff100-d3a3-11ea-9ba1-73304d887be4.png)
