### ISSUE TITLE
И снова 180-й градус

### ISSUE THREAD

**Issue by taimyr** [nextgis/nextgisweb#144]
И опять то же самое. Попытался загрузить и добавить точечный слой  - видна только "восточно-полушарная" половина. Я не понимаю в чем дело, 
taimyrsky.ru/other/4lay.zip - в архиве 4 архива слоев, 3 загрузились с первого раза нормально (reserve, protarea, lakes), 4-й - cabins видна только половина в западной части, а с реками, ссылка на которые есть уже в предыдущем тикете по теме, были вчера просто непонятные вещи - после по меньшей мере 5 архиваций и последующих загрузок загрузок загрузился наконец нормально, а так то не загружался вообще, то загружался, но отображалась только половина

**Comment by simgislab** [comment]
проверил, Connect загружает все слои штатно

![](http://m-d.me/img/ss/20180218_084909.png)
![](http://m-d.me/img/ss/20180218_084948.png)

переоткрывайте, если сохраняются проблемы с ручной загрузкой через веб-интерфейс
