### ISSUE TITLE
Расширенная поддержка растров

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#145]
Я тут подумал, т.к. у нас рендерингом растров занимается само приложение, а не backend не сделать ли нам более расширенную поддержку растров:
1) Поддержка многоканальных растров (от 1 и до 255)
2) Поддержка прозрачности через nodata
3) Поддержка комбинирования каналов
4) Операции над выходным растром (растяжка, гистограмма и т.п.)
5) Поддержка vrt
6) Отмывка рельефа на лету

Как это можно сделать - c++приложение с Python binding
На входе - ну тут либо номер тайла, либо охват в координатах, а также другие параметры рендеринга
На выходе тайл или картинка в формате png с необходимой прозрачностью

Кроме того загрузкой данных (наверное надо перепроецировать) занимается тоже приложение, причем с выдачей % выполнения, что бы можно было рисовать прогрессбар

Еще для настройки всей этой "красоты" в админке должны быть инструменты на подобии как в QGIS - выбор комбинации каналов, назначение алгоритма растяжки, выбор или назначение каналов прозрачности и т.п. с показом результата (preview).

**Comment by simgislab** [comment]
https://nextgis.ru/blog/raster-styles/
