### ISSUE TITLE
Порядок слоёв в списке идентификации должен совпадать с порядком отображения на веб-карте

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#151]
![image](https://cloud.githubusercontent.com/assets/4630662/2740803/3bb5d7fa-c6db-11e3-8b88-06159bf68c20.png)
Сейчас - как на картинке. 
Заказчик хочет, что бы в данном случае, в списке сначала был тот слой, который на веб-карте стоит выше в списке.

**Comment by simgislab** [comment]
duplicate of #525
