### ISSUE TITLE
Таблица объектов отдельной кнопкой

### ISSUE THREAD

**Issue by Mirotvorez** [nextgis/nextgisweb#166]
Можно ли вынести "Таблицу объектов" из выпадающего меню
"Слой" ? Например иконкой к инструментам измерить линию, площадь,
идентификация. По идее это очень часто используемый инструмент и каждый
раз лазить в выпадающее меню не удобно. После этого вместо выпадающего
меню можно оставить лишь кнопку "описание".

**Comment by drnextgis** [comment]
Duplicate https://github.com/nextgis/nextgisweb/issues/135
