### ISSUE TITLE
Добавить в интерфейс веб клиента кнопку вход/выход

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#178]
В интерфейсе веб клиента необходимо предусмотреть кнопку для ввода имени пользователя и пароля. Сейчас алгоритм просмотра от различных пользователей следующий: 
- заход в админку
- выбор карты
- кнопка просмотр

Но мы шарим ссылку с картой пользователям и им не нужна даминка. Однако по умолчанию им открывается практический пустоц клиент и как ввести пароль непонятно. Кроме того, когда открыто несколько вкладок с одним и тем же клиентом но разными входами, непонятно с какими правами я сейчас работаю.

**Comment by drnextgis** [comment]
@BishopGIS, шапка у карты появилась, закрываем?

**Comment by BishopGIS** [comment]
Круто!
