### ISSUE TITLE
Увеличение до охвата слоя

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#220]
Допустим у нас есть линейный слой. В нём 1-2 коротких линии. Стиль настроен так, что линии очень тонкие. На большом масштабе его абсолютно невозможно найти на карте.

Тут пригодилась бы кнопка "Увеличить до охвата слоя", как в QGIS.

**Comment by BishopGIS** [comment]
#374

**Comment by drnextgis** [comment]
Добавлено в https://github.com/nextgis/nextgisweb/commit/b43d0bbf84af64880e4b7eacf13f1ffdaefb91d3, не работает на PostGIS слоях. Если нужно для PostGIS - отдельный тикет.

**Comment by simgislab** [comment]
спасибо, про постгис создал тикет, назначил на 3.0.3, но если можно сделать быстро, то неплохо и в 3.0.2 сделать
