### ISSUE TITLE
Health check в JSON.

### ISSUE THREAD

**Issue by the-l-a-cat** [nextgis/nextgisweb#227]
Сейчас при отсутствии базы, file_storage или file_upload просходит выпадение разного рода ошибок. 

Нельзя ли сделать, чтобы во всех случаях ошибка ловилась, uwsgi открывал сокет и показывал что-то вроде "down on service" пользователю, а мне по секретной ссылке отдавал в каком-нибудь виде (идеально YAML) словарик вида {requisite: (status, description)},  где статус - True / False? Это позволит сделать нам автоматический единообразный health check и вывести индикаторы на console.

Чем больше реквизитов удастся проверять - тем лучше, особенно важно -  схему базы, так как init-db часто косячит.

**Comment by dezhin** [comment]
/api/component/pyramid/healthcheck это было реализовано некоторое время назад.
