### ISSUE TITLE
Подставлять названия поля id и геометрии при создании слоя PostGIS

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#234]
Сделать в интерфейсе NGW возможность настроек, общих для всего инстанса:
"При создании слоя PostGIS подставлять по умолчанию название поля id"
"При создании слоя PostGIS подставлять по умолчанию название поля геометрии"

Это позволить снизить количество нажатий кнопок при рутинной процедуре добавления 30 слоёв.

**Comment by drnextgis** [comment]
Довольно специфичная задача, не вижу особой нужды в этой функции в ядре, как и в #236. Поэтому закрою.
