### ISSUE TITLE
Фильтрация по классу в окне выбора ресурсов

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#240]
На уровне БД это может выглядеть так:

``` sql
WITH RECURSIVE resource_filtered AS (
    SELECT * FROM resource WHERE cls = 'postgis_layer'
  UNION
    SELECT resource.*
    FROM resource, resource_filtered
    WHERE resource.id = resource_filtered.parent_id
  )
SELECT *
FROM resource_filtered
```

[SQLAlchemy CTE](http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.cte)

**Comment by drnextgis** [comment]
Фильтрация на клиенте: https://github.com/nextgis/nextgisweb/commit/29f10d60291d87109339acbd5e837de56c18c202

**Comment by simgislab** [comment]
Кейсы использования:

1. Добавление слоя на веб-карту. Должны выбираться только стили векторных, растровых, постгис слоёв.
2. Добавление подложки на карту. Должны выбираться только подложки
3. Добавление охвата карты по слою. Должны выбираться только векторные слои.
4. Добавление слоя закладок на карту. Должны выбираться только векторные слои.
5. Добавление слоя в WFS сервис. Должны выбираться только векторные слои. 
https://demo.nextgis.com/resource/1730
6. Добавление слоя в WMS сервис. Должны выбираться только векторные слои.  https://demo.nextgis.com/resource/82
7. Добавление слоя PostGIS. Должны выбираться только соединения PostGIS. 
8. Добавление WMS слоя. Должны выбираться только соединения WMS.

тестировать можно на demo.nextgis.com

**Comment by simgislab** [comment]
решили делать через стили

**Comment by simgislab** [comment]
1. Добавление слоя на веб-карту.
    Выберите стиль слоя//Select layer's style
1. Добавление подложки на карту. 
    Выберите подложку//Select basemap
1. Добавление охвата карты по слою. 
    Выберите векторный слой//Select vector layer
1. Добавление слоя закладок на карту.
    Выберите векторный слой//Select vector layer
1.

**Comment by dezhin** [comment]
Еще с выбором нового родителя что-то надо придумать, он может быть любой.

**Comment by lisovenkoNastya** [comment]
Добавила возможность задавать кастомные заголовки.
Прописала нужные тексты, сделала переводы 
https://github.com/nextgis/nextgisweb/commit/96ca27fe52c8f0a6d81dc08dc56b1a6fe6c751d7
https://github.com/nextgis/nextgisweb_basemap/commit/8b0ff57f274d2fa6c6c1d5482a1dbcab39239719
