### ISSUE TITLE
Нужен полный перечень сообщений от НГВ

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#247]
Для документации и для ответов на вопросы в рамках поддержки нужен перечень сообщений, который могут выдаваться НГВ (табличка)

**Comment by dezhin** [comment]
Это предлагаю закрыть, я решительно, что мы можем тут сделать. У нас в принципе нет сообщений с кодами ошибок вроде E591, которые непонятно что значат. Сами сообщения в целом понятны. Если актуально и можете объяснить что нужно  - переоткройте и уточните.
