### ISSUE TITLE
WFS. IntegretyError вместо описания проблемы

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#248]
При создании нового ресурса и не указании ключа для слоя, появляется ошибка Integrity error.
Догадаться, где и чего не хватает - невозможно.
При этом, при входе на нужную вкладку значек необходимости ввода горит.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/908e0a80bebde9f5e52c3956233ff7a95175feb2
