### ISSUE TITLE
Масштабная шкала

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#25]
Неплохо бы добавить настройку отображения масштабной шкалы.
1. Расположение: нижний левый угол, верхний левый угол и т.п.
2. Единицы - отдельно м, футы или метры + футы (в старой веб ГИС по Красногорску были только метры)
3. Вкл/выкл

**Comment by dezhin** [comment]
Линейка у нас есть довольно давно, метры или футы - в соответствии с настройками единиц измерения. Убрать нельзя, но никто на нее не жаловался вроде бы.
