### ISSUE TITLE
Давать версию NGW API при запросе дерева

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#255]
Хотя бы при запросе дерева (child) давать версию API. 
Или еще где ни будь предусмотреть, например http://url_to_ngw/resource/version

**Comment by drnextgis** [comment]
@BishopGIS закрываем?

**Comment by BishopGIS** [comment]
@dezhin  сказал, что тут про другое - типа capabilities у модулей. Я бы закрыл, так как получил желаемое. Но ему виднее.

**Comment by drnextgis** [comment]
Про capabilities - это в другом тикете.

**Comment by drnextgis** [comment]
См. https://github.com/nextgis/nextgisweb/issues/432
