### ISSUE TITLE
Падение при неизвестном типе ресурса

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#261]
При несоответствии установленных расширений и БД (я понимаю что это не штатный режим работы, но такое случается при обновлении или разворачивании на уже существующей БД), при наличии в БД ресурсов с типами, относящихся к 'внешним' расширениям, любое обращение к этим ресурсам или группам ресурсам, содержащим их, происходит падение.
Может при нахождении подобных ресурсов выводить только его ид и тип, при ошибке восстановления инстанса класса?

**Comment by simgislab** [comment]
теперь происходит ошибка на уровне сборки и API
