### ISSUE TITLE
Не закрываются подключения к PostGIS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#274]
НГВ открывает экстремально много подключений к свой БД и к подключенной БД. 
В Росавто на сервере стоял лимит в 100 подключений (там всего 40 слоев). 
Вначале увеличили до 150, потом 200, 250 - сейчас 300. 
Так скоро и память закончится. 
В результате такого большого количества подключений к БД не подключится ни для бэкапа ни для просмотра в pgAdmin/psql.
Возможно стоит какие-то старые коннекты прибивать или в коде где закрывать подключения забыли.

**Comment by drnextgis** [comment]
Проблема больше не наблюдается.
