### ISSUE TITLE
UnicodeDecodeError при добавлении слоя в WFS и не указания ключа

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#275]
Если при добавлении в WFS сервис слоя с русским названием не указать его ключ, то не появляется ни каких ошибок, но и изменения не сохраняются.

В логе появляется запись:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 124: ordinal not in range(128)

Если название слоя английское - то появляется IntegrityError (который на самом деле тоже не дает внятной подсказки, что не так).

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/908e0a80bebde9f5e52c3956233ff7a95175feb2
