### ISSUE TITLE
Координаты в WFS

### ISSUE THREAD

**Issue by KolesovDmitry** [nextgis/nextgisweb#278]
Координаты всегда приходят в системе коодинат слоя не зависимо от того, в какой системе был запрос:

http://176.9.38.120/cl/resource/659/wfs?SERVICE=WFS&REQUEST=GetFeature&TYPENAME=overhead_power_line&VERSION=1.0.0:

`<gml:coordinates>4132670.50916749984026,6702262.844785958528519 4132488.743063123431057,6703182.78854896966368 4130791.673608019016683,6705675.359311155043542 4130844.707028490956873,6707080.744953663088381 4129774.530862953513861,6709154.147146104834974 4128723.37020961008966,6709109.27328671887517</gml:coordinates>`

http://176.9.38.120/cl/resource/659/wfs?SERVICE=WFS&REQUEST=GetFeature&TYPENAME=overhead_power_line&SRSNAME=EPSG:4326&VERSION=1.0.0:

`<gml:coordinates>4132676.673139616381377,6702262.017754058353603 4134888.505339483264834,6697972.25498759187758 4141146.448955181986094,6697176.753680511377752 4142631.384728398174047,6697229.78710098285228 4143904.186819727066904,6696540.352634847164154 4145017.88864963920787,6695267.550543518736959 4145953.401819194667041,6695366.025613998062909 4146124.96130199264735,6694922.833310450427234</gml:coordinates>`

**Comment by simgislab** [comment]
надо учесть в новой имплементации WFS в тестах

**Comment by edpop** [comment]
Уже давно работает
