### ISSUE TITLE
Права WFS

### ISSUE THREAD

**Issue by dezhin** [nextgis/nextgisweb#279]

**Comment by BishopGIS** [comment]
Не уверен что это имелось в виду, но при получении запроса GetCapabilities, если у пользователя права только на чтение, то не должно возвращаться insert, update, delete.
Пример: http://bnd.kirov.rekod.ru/api/resource/434/wfs?REQUEST=GetCapabilities
``` xml
<FeatureType><Name>kirov_zapovedniki_a</Name><Title>kirov_zapovedniki_a</Title><Abstract/><SRS>EPSG:3857</SRS><Operations><Insert/><Update/><Delete/></Operations><bbox maxx="0" maxy="0" minx="0" miny="0"/></FeatureType>
```

**Comment by simgislab** [comment]
надо учесть в новой имплементации WFS

**Comment by edpop** [comment]
Добавлено в новой реализации
