### ISSUE TITLE
Не хватает масштаба на веб-карте

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#281]
Сейчас zoom приблизительно до 19, на таком масштабе не видны карты отдельных кустиков. Предлагаю добавить в настройки веб-карты максимальный зум - чтоб по умолчанию был как у максимального зума тайлов OSM, но можно было сделать покрупнее. 
![image](https://cloud.githubusercontent.com/assets/4630662/5315894/5d490624-7c95-11e4-9408-fd31428a1b25.png)

**Comment by drnextgis** [comment]
Да, количество масштабных уровней каждой подложки можно задать в `basemap.json`. Пример:

```
[{
    "keyname": "osm-mapnik",
    "mid": "ngw/openlayers/layer/OSM",
    "title": "OpenStreetMap",
    "numZoomLevels": 25
}]
```

**Comment by simgislab** [comment]
@trolleway, @BishopGIS  в документации есть?

**Comment by BishopGIS** [comment]
Нет. Завел тикет https://github.com/nextgis/docs_ngweb/issues/26.
