### ISSUE TITLE
Разное отображение по АПИ и в веб-интерфейсе

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#283]
У пользователя права на чтение ресурса (Ресурс:Чтение) не распространять. При отображении через веб показывается 8 групп ресурсов, при запросе по АПИ - 2.
http://213.171.50.28:64033/resource/0/child/
user:maklakov
password:rekod

Это правильно? Так и задумывалось или баг?

**Comment by simgislab** [comment]
исправлено
