### ISSUE TITLE
Поддержка WMS клиент версии 1.3.0

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#294]
Собственно сабж

**Comment by drnextgis** [comment]
4 дня назад добавили в OWSLib, которую мы используем, как выйдет релиз - у себя добавим.

**Comment by drnextgis** [comment]
Добавил, пока в отдельную ветку https://github.com/nextgis/nextgisweb/commit/fa0ce76783fa1adcd720b020247f98c3ae997763

**Comment by drnextgis** [comment]
Closed via https://github.com/nextgis/nextgisweb/commit/4ee8324139db2ec4ef710003c343886bf1020ddf
