### ISSUE TITLE
Поменять стиль для поля ввода в редактировании атрибутов слоя

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#30]
![nextgisweb textbox](https://f.cloud.github.com/assets/4630662/1961620/4c7d3efa-8277-11e3-8f1a-453d4e24fb13.png)

Сейчас "name, notes" выглядят просто как надпись, и непонятно, что их можно редактировать. А хорошо бы сделать, чтоб они выглядели как поле ввода.

**Comment by drnextgis** [comment]
@lisovenkoNastya, может у тебя есть какие-нибудь идеи о том как это могло бы выглядеть?

**Comment by dezhin** [comment]
Стили мы давно поменяли, с тех пор был даже полный редизайн.
