### ISSUE TITLE
Путаница с fid

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgisweb#301]
В ngw:
    слой - RU-KLU-OBNINSK (http://demo.nextgis.ru/ngw/resource/1316)
    карта - RU-KLU-MAP (http://demo.nextgis.ru/ngw/resource/1309)
    объект c fid=4 (большой полигон в центре) имеет фото 3 шт. (например, http://demo.nextgis.ru/ngw/layer/1316/feature/4/photo/4)

Загружаю слой в ngq как geojson - все ОК.   Тот же объект (большой полигон в центре) имеет fid 4.

Проблема:
Загружаю слой в ngq через WFS (http://demo.nextgis.ru/ngw/resource/1311) - fid не соответствует.  Тот же объект (большой полигон в центре) имеет fid 3.

**Comment by dezhin** [comment]
Видимо это можно закрывать, похожее поведение мы наблюдаем и с новым WFS сервером в NGW. Видимо ноги мэппинга растут из того, что идентификаторы объекта в WFS - не число, а строка в общем случае. Но вроде бы это не приводит к проблемам.
