### ISSUE TITLE
Поддержка типов данных Int64

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#305]
GDAL 2.x поддерживает тип Int64. Он позволяет хранить идентификаторы OSM и другие без потери данных.
Имхо было бы полезно иметь возможность загружать такие данные в нгв.

**Comment by drnextgis** [comment]
Added in https://github.com/nextgis/nextgisweb/commit/442ebfefd6706fc37338b1609e7589a0f04fd5c4

**Comment by drnextgis** [comment]
Closed via https://github.com/nextgis/nextgisweb/commit/229fd7b8d0866f712ebd0e171764700352c25303
