### ISSUE TITLE
Идентификация: добавить поле с названием слоя

### ISSUE THREAD

**Issue by KoGor** [nextgis/nextgisweb#307]
Сейчас у нас при идентификации объекта выдаётся внутренний айдишник слоя, которому принадлежит объект (`layerId`). Поскольку эти айдишники формируются в NWG автоматом при создании слоя мы не можем их поменять в дальнейшем. Соответственно если нам нужно будет пересоздать слой NGW (удалить и загрузить по новой) мы получим уже другой внутренний айдишник. Это поломает нам всю привязку.

Простым решением было бы добавление дополнительного поля с названием слоя/ресурса (`display_name`), по которому тоже можно было бы определить принадлежность объекта.

А в дальнейшем конечно нужно добавить возможность перезагрузки данных слоя, что бы не было необходимости его пересоздавать в принципе.

**Comment by simgislab** [comment]
в идентификации добавлено
![](http://m-d.me/img/ss/lZGjlpCYu5.png)
