### ISSUE TITLE
Перечитывание полей PostGIS в процессе инициализации

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#313]
Сейчас если в таблице-источнике поменяются поля, то для того, чтобы с ней работать в ngw надо перечитать атрибуты из админки. Но таких слоев может быть достаточно много, да и факт обнаружения того, что нужно перечитать поля выясняется только в том момент, когда что-то перестает работать. Может нам стоит как-то добавить эту возможность в процесс общей инициализации БД ngw?

**Comment by simgislab** [comment]
reread? @drnextgis закрываем?

**Comment by dezhin** [comment]
Пока закрываю, это точно не про initialize_db. Думаю у тех, у кого эта проблема актуальна, могут это сделать через API.
