### ISSUE TITLE
Алиасы для адресов при раздаче tms

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#319]
Допустим я у себя дома делаю набор геоданных, время от времени его обновляю, хочу выкладывать его в gis.to, и делиться тайлами. Если я перезаписываю слой из шейпфайла, то меняется id слоя, и адреса тайлов надо будет менять.

Юзкейс:
1. Я делаю валидатор OSM / рисую троллейбусные маршруты / векторизую ворованные карты внутренних водных путей / рисую растр. 
2. Гружу шейп или GeoTIFF в gis.to.
3. Показываю тайлы на каком-нибудь сайте, создатели которого программировать не умеют, или смотрю их на мобильном устройстве (не в NextGIS Mobile)
4. При обновлении данных я удаляю шейп, и гружу его заново. 

Текущее поведение: Теперь у этого слоя другой id, и на клиентах приходится менять URL.

Желаемое поведение: в веб-карте для каждого стиля, там где настраивается прозрачность, и масштаб, добавить поле для указания алиаса. Тайлы будут иметь url типа
http://username.gis.to/resource/aliasname/tms?z=10&x=616&y=340

**Comment by simgislab** [comment]
решается через rewrite на nginx

**Comment by dezhin** [comment]
Думаю это можно закрыть, так как теперь в интерфейсе есть возможность заменить данные и для векторов и для растров.
