### ISSUE TITLE
Автоматическая генерация ключей ресурсов при создании WMS сервиса

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#322]
Делаю WMS-сервис, который раздаёт отдельные листы топокарт.
Текущее поведение: мне надо в админке вручную для каждого слоя скопировать его название из одного поля в другое.
![2015-04-17 16 59 48](https://cloud.githubusercontent.com/assets/4630662/7203432/52d3d538-e523-11e4-8fca-97fb7401a45a.png)

Желаемое поведение: раз в этом типе ресурса необходимо обязательно иметь ключи для слоёв, то они должны генерироваться сами .

**Comment by dezhin** [comment]
https://app.clickup.com/t/pvb69c
