### ISSUE TITLE
Поддержка WFS сервера v.1.1

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#326]
Сейчас наш WFS сервер работает по спецификации 1.0. 
Необходимо реализовать поддержку 1.1

**Comment by dezhin** [comment]
Сейчас поддерживаются 1.0 и 2.0. 1.1 во многом есть в коде, но не понятно честно говоря зачем он нужен. Софта, который только 1.1 мы не видели нигде. 1.0 - да, есть, QGIS например в части WFS-T и там это не собираются менять. В общем если нужно для чего-то именно 1.1 - нужно переоткрыть тикет.
