### ISSUE TITLE
Аутентификация в WMS сервисе

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#331]
Сейчас возможно подключать только анонимные WMS сервисы. Необходимо дать возможность указать логин и пароль для получения слоев с закрытых WMS сервисов

**Comment by dezhin** [comment]
Вообще эта возможность есть изначально, поскольку в WMS аутентификация передается через стандартную HTTP аутентификацию, которая в свою очередь обрабатывается ngw точно так же как и аутентификацию через куки.

Наверное проблема в чем-то другом.

**Comment by BishopGIS** [comment]
Возможно я не правильно выразился. Имеется в виду ситуация когда мы
подключаемых внешний wms, а он запаролен. Я не нашёл где указать логин и
пароль.

**Comment by dezhin** [comment]
Аааа, вот о чем речь. А в URL логин пароль указывать не пробовали?

**Comment by BishopGIS** [comment]
Ой. Нет. Но с точки зрения юзера, все таки поля ввода иметь неплохо.

**Comment by BishopGIS** [comment]
Проверил с вставкой логина/пароля в url - не работает:
```
Неизвестная исключительная ситуация InvalidURL, cериализатор wmsclient_connection, атрибут capcache.
```

**Comment by drnextgis** [comment]
Реализовано в https://github.com/nextgis/nextgisweb/pull/338

**Comment by snpotapov** [comment]
При добавлении сервиса Росреестра
http://maps.rosreestr.ru/arcgis/services/Cadastre/CadastreWMS/MapServer/WMSServer?
возникает ошибка:

В ходе выполнении операции произошла неожиданная ошибка. Сообщение об ошибке
Неизвестная ошибка 'XMLSyntaxError' в сериализаторе 'wmsclient_connection', атрибут 'capcache'.

Сервис анонимный

**Comment by drnextgis** [comment]
Причина в этом https://github.com/nextgis/nextgisweb/issues/415

**Comment by snpotapov** [comment]
И чего делать?
Сервис рабочий.

**Comment by drnextgis** [comment]
Править OWSLib.

**Comment by drnextgis** [comment]
@snpotapov проблема решена в https://github.com/nextgis/nextgisweb/commit/0932f3d980ca1ce6e08638c539f25bf7348bd581. Правда пока не вышел релиз OWSLib, он не доступен из PyPI, поэтому его нужно ставить с GitHub репозитория [OWSLib](https://github.com/geopython/OWSLib).

**Comment by snpotapov** [comment]
В какой версии OWSLib проблема решена?
с 0.11.0  такая же ситуация..... соединение не создается.

**Comment by drnextgis** [comment]
А я же там написал в сообщении к коммиту: `This changes requires latest OWSLib (not yet released).` Поставьте OWSLib из репозитория.

**Comment by snpotapov** [comment]
Понял

**Comment by snpotapov** [comment]
Сервис Росреестра прописать стало возможно , но при отображении чего-либо
вылезает это:
Exception when serving /api/component/render/tile
Traceback (most recent call last):
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/master/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
    response = handler(request)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "/home/master/ngw/nextgisweb/nextgisweb/render/api.py", line 33, in tile
    rimg = req.render_tile((z, x, y), 256)
  File "/home/master/ngw/nextgisweb/nextgisweb/wmsclient/model.py", line 203, in render_tile
    return self.style.render_image(extent, (size, size))
  File "/home/master/ngw/nextgisweb/nextgisweb/wmsclient/model.py", line 249, in render_image
    url, auth=auth, headers=env.wmsclient.headers).content))
  File "/home/master/ngw/env/local/lib/python2.7/site-packages/PIL/Image.py", line 2309, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x7fa36e560bf0>

**Comment by drnextgis** [comment]
Используйте провайдер `Image` вместо `Tiles` при добавлении слоя на карту, должно помочь. А ошибка, видимо, из-за того, что сервер ПКК присылает кривой ответ.

**Comment by drnextgis** [comment]
@snpotapov, получилось?

**Comment by snpotapov** [comment]
Неа, остальные веб-сервисы нормальные - я имею в виду самого NegtGisWeb.
А Росреестр не понятно. Из NextGis нормально читается.....

**Comment by drnextgis** [comment]
То есть вы создаёте WMS слой, добавляете его как Image на карту и он не отображается? У меня всё ok.

**Comment by snpotapov** [comment]
Да, я установил посл дистрибутив.
Скачал и установил отдельно OWSLib.
Сделал соединение WMS.
Сделал слой WMS. Добавил его как слой Image на карту. 
И получил красный квадрат......

**Comment by drnextgis** [comment]
А вы тут случаем не забыли формат выбрать? Без этого работать не будет. ![screenshot from 2016-04-19 21 21 13](https://cloud.githubusercontent.com/assets/866124/14642460/b644dca2-0674-11e6-8b2c-95c812b45e14.png)

**Comment by snpotapov** [comment]
Да всякие пробовал. 
Завтра попробую на голой чистой виртуалке .....
Может пакеты какие переклинило...

**Comment by snpotapov** [comment]
Все получилось. С нуля поставил дистрибутив веба и накатил библиотеку OWSLib.
Спасибо.

**Comment by drnextgis** [comment]
@snpotapov a вы на `2` ветке NextGIS Web? Предлагаю потестить `3` бранч с OpenLayers 3. `3` ветка не совместима со `2`, поэтому просто `git checkout 3` не сработает. Нужно ещё в БД выполнить команды [отсюда](https://github.com/nextgis/nextgisweb/blob/3/MIGRATE.md) за `2016-03-08`.

**Comment by snpotapov** [comment]
Попробую.

**Comment by drnextgis** [comment]
Спасибо. Жду фидбек.

**Comment by simgislab** [comment]
у меня все работает

**Comment by snpotapov** [comment]
Максим, проверяю ваше облако.
Росреестр так и не показывается ....
Но ошибок не выдает?

Сергей.

**Comment by drnextgis** [comment]
Только что попробовал в облаке - все работает. Можно ссылку на ваш пример?

**Comment by snpotapov** [comment]
http://mgisfryazino.nextgis.com/resource/1

**Comment by snpotapov** [comment]
http://mgisfryazino.nextgis.com/resource/1/display

**Comment by drnextgis** [comment]
А если изменить формат слоя с 'jpg' на 'png'?

**Comment by snpotapov** [comment]
не влияет. может какого пользователя ввести?
но там нет авторизации....

**Comment by simgislab** [comment]
у меня все работает прекрасно
посмотрите настройки, может у вас что-то по другому
http://maxim.nextgis.com/resource/1/display
http://maxim.nextgis.com/resource/37

**Comment by snpotapov** [comment]
А как он вообще работает - там нет ссылки на WMS сервис....

**Comment by snpotapov** [comment]
http://maxim.nextgis.com/resource/36/update

**Comment by simgislab** [comment]
есть 

![](http://m-d.me/img/ss/20164327-174336.png)

**Comment by snpotapov** [comment]
Все разобрался
ссылка  http://maps.rosreestr.ru/arcgis/services/Cadastre/CadastreWMS/MapServer/WmsServer?
а в документации другая....
http://maps.rosreestr.ru/arcgis/services/Cadastre/CadastreWMS/MapServer/WMSServer?request=GetCapabilities&service=WMS  
Исправьте, а то народ не поймет...

**Comment by simgislab** [comment]
https://github.com/nextgis/docs_ngweb/edit/ru/source/layers.rst

мы очень любим PR)

**Comment by snpotapov** [comment]
Максим дай твой прямой адрес.
Есть еще одна тема.

**Comment by simgislab** [comment]
maxim.dubinin@nextgis.com
