### ISSUE TITLE
Problem install- ImportError: No module named mapscript

### ISSUE THREAD

**Issue by Comiii** [nextgis/nextgisweb#332]
Hi. I have problem to install nextgisweb. I am using Ubuntu 14.10 and Python 2.7. 
When I try to to point to MaspScript verison I get this:

osboxes@osboxes:~/ngw$ echo `python -c "import mapscript; print 'Version: %s' % mapscript.MS_VERSION"` > env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO/PKG-INFO
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named mapscript

If I try to install mapscript:
osboxes@osboxes:~/ngw$ sudo apt-get install python-mapscript
[sudo] password for osboxes: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-mapscript is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 283 not to upgrade.

So, it's say that I already have new version. What I am doing wrong? 
Thanks!

**Comment by dezhin** [comment]
It looks like you are calling not a system python. Or something wrong with `python-mapscript` package. You can try this:

    $ echo `/usr/bin/python -c "import mapscript; print 'Version: %s' % mapscript.MS_VERSION" > env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO/PKG-INFO`

**Comment by Comiii** [comment]
Thanks for answering. Now I can do this. When I run  env/bin/pip freeze I get this:
osboxes@osboxes:~/ngw$ env/bin/pip freeze
mapscript==6.4.1
wheel==0.24.0
 
But when I try to:
osboxes@osboxes:~/ngw$ env/bin/pip install -e ./nextgisweb_mapserver
I get this:
Obtaining file:///home/osboxes/ngw/nextgisweb_mapserver
Collecting nextgisweb (from nextgisweb-mapserver===0.0dev-r0)
  Could not find a version that satisfies the requirement nextgisweb (from nextgisweb-mapserver===0.0dev-r0) (from versions: )
No matching distribution found for nextgisweb (from nextgisweb-mapserver===0.0dev-r0)

**Comment by drnextgis** [comment]
You have to install `nextgisweb` package before trying to install `nextgisweb_mapserver`.

**Comment by Comiii** [comment]
Ok. This is problem when I try to to install nextgisweb:
osboxes@osboxes:~/ngw$ env/bin/pip install -e ./nextgisweb
Obtaining file:///home/osboxes/ngw/nextgisweb
Collecting pyramid (from nextgisweb==0.0)
  Using cached pyramid-1.5.7-py2.py3-none-any.whl
Collecting SQLAlchemy<0.9,>=0.8 (from nextgisweb==0.0)
  Using cached SQLAlchemy-0.8.7.tar.gz
Collecting transaction (from nextgisweb==0.0)
  Using cached transaction-1.4.4.tar.gz
Collecting pyramid-tm (from nextgisweb==0.0)
  Using cached pyramid_tm-0.12-py2.py3-none-any.whl
Collecting pyramid-debugtoolbar (from nextgisweb==0.0)
  Using cached pyramid_debugtoolbar-2.4-py2.py3-none-any.whl
Collecting pyramid-mako (from nextgisweb==0.0)
  Using cached pyramid_mako-1.0.2.tar.gz
Collecting zope.sqlalchemy (from nextgisweb==0.0)
  Using cached zope.sqlalchemy-0.7.6.zip
Collecting zope.interface (from nextgisweb==0.0)
  Using cached zope.interface-4.1.2.tar.gz
Collecting bunch (from nextgisweb==0.0)
  Using cached bunch-1.0.1.tar.gz
Collecting flufl.enum (from nextgisweb==0.0)
  Using cached flufl.enum-4.0.1.tar.gz
Collecting waitress (from nextgisweb==0.0)
  Using cached waitress-0.8.9.tar.gz
Collecting pygdal==1.11.2 (from nextgisweb==0.0)
  Could not find a version that satisfies the requirement pygdal==1.11.2 (from nextgisweb==0.0) (from versions: 1.8.1.0, 1.8.1.1, 1.9.2.0, 1.9.2.1, 1.10.0.0, 1.10.0.1, 1.10.1.0, 1.10.1.1, 1.11.0.0, 1.11.0.1, 1.11.1.0, 1.11.1.1, 1.11.2.1)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external pygdal to allow).
No matching distribution found for pygdal==1.11.2 (from nextgisweb==0.0)

**Comment by BishopGIS** [comment]
I solve this changing the line in setup.py
from
``` python
gdalver = '==' + check_output(['gdal-config', '--version']).strip()
```
to
```python
gdalver = '>=' + check_output(['gdal-config', '--version']).strip()
```
Not the universal solution but works

**Comment by Comiii** [comment]
Yes this work. Thanks!
