### ISSUE TITLE
Сообщение об ошибке записи в WFS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#335]
При ошибке записи по протоколу WFS выдается пустое сообщение об ошибке, хотя в логе четко пишется, что одно из обязательных полей не заполнено. Необходимо выводить понятное сообщение об ошибке.

**Comment by drnextgis** [comment]
Если я правильно понял, то речь идёт об ошибке в инстансе лесонарушений. Можешь в отдельном тикете ее завести, если понятно как ее воспроизвести?
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
```

**Comment by BishopGIS** [comment]
Нет. Это об сервисе wfs.  Он должен в qgis непустой текст отдавать. Дима в
курсе, это он попросил создать тикет.

**Comment by dezhin** [comment]
Недавно в WFS и WMS был реализован механизм информирования об ошибках в соответствии со стандартом. К сожалению клиенты его по большей части игнорируют...
