### ISSUE TITLE
При создании WFS-сервиса не пишется его URL

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#342]
Создаю WFS-сервис.
Нажимаю кнопку "Создать".
Его URL нигде не пишется
Что бы посмотреть URL, нужно заходить в его настройку по-новой

**Comment by BishopGIS** [comment]
После создания что WFS, что WMS ссылку на сервис можно посмотреть зайдя в него. 
Мне кажется там все логично.

**Comment by trolleway** [comment]
Ну так надо лишний раз нажимать, и заходить в то же место, из которого ушел

**Comment by drnextgis** [comment]
Не понял сути проблемы. После того, как нажали `Создать`, нас перекидывает на главную страницу ресурса, на которой фигурирует URL созданного сервиса.
