### ISSUE TITLE
WFS сервис чувствителен к регистру ключей

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#343]
Вот так не работает:

```
http://demo.nextgis.ru/ngw/resource/22/wfs?SERVICE=WFS&request=GetCapabilities
```

**Comment by KolesovDmitry** [comment]
Проблема связана с тем, что я вызываю request.params, который использует case-sensitive dict:
https://github.com/nextgis/nextgisweb/blob/2/nextgisweb/wfsserver/view.py#L28
Понятно, что легко написать обертку над этим словарем, которая будет не зависима от регистра, но мне кажется, что это очень распространенная проблема, поэтому одна должна решаться без велосипедостроения.
Тем не менее, гугление не привело ни к какому результату.

@drnextgis, не знаешь ли ты стандартного способа обхода этой проблемы? Если нет, то я напишу обертку над словарем, которая будет регистронезависимой.

**Comment by drnextgis** [comment]
Может так? https://github.com/nextgis/nextgisweb/blob/2/nextgisweb/wmsserver/view.py#L38

**Comment by KolesovDmitry** [comment]
Спасибо, сделал так, как ты советуешь. Просто мне казалось, что регистр символов в запросе -- постоянный источник проблем, и должна быть какая-то системная штуковина "из коробки", чтобы бороться с этим.

**Comment by KolesovDmitry** [comment]
Сделал так, что ключи запроса к регистру не чуствительны, а значения -- регистрозависимы. Теперь все в соответствии со стандартом: Parameter names shall not be case sensitive, but parameter values shall be case sensitive.

**Comment by simgislab** [comment]
ok, так лучше
