### ISSUE TITLE
Эффективные права для ресурса

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#346]
Необходимо добавить возможность просмотра эффективных прав для ресурса - список пользователей и их прав для этого ресурса. Предлагается это вынести в отдельную вкладку - Эффективные права. 
Так же необходима галка - Выводить пользователей только с разрешениями. При её включении  в списке должны оставаться только те пользователи, у которых есть хотя бы одно разрешение для данного ресурса.

**Comment by simgislab** [comment]
эффективные права текущего пользователя через API узнать можно
