### ISSUE TITLE
Ренедеринг нескольких слоев за один запрос

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#351]
Проблематика - необходимо выводить на веб карту большое количество слоев с небольшим кол-вом объектов в каждом. Браузер начинает подвисать при 50+ слоях.

Есть вариант (достаточно универсальный):
Реализовать апи для рендеринга нескольких слоев за один запрос и добавить в веб карте новый тип слоя, которому можно будет задавать программно ид ресурсов для рендеринга.
Метод апи должен быть аналогичным тому, который сейчас есть для рендеринга векторного слоя, единственное отличие - вместо ид ресурса должен быть список ид. Сервис должен отрисовывать ресурсы в той последовательности, в котором пришел список ид.
Соответственно со стороны веб необходим новый тип слоя, у которого можно задать нужные ид. Все остальное поведение - полностью совпадает с уже существующим слоем.

Было бы хорошо если этот метод апи был бы многопоточный (с настройкой колва потоков в конфиге).

**Comment by yellow-sky** [comment]
Связный тикет - #352 
При отрисовке большого количества слоев на сервере можно было бы очень хорошо экономить время.

**Comment by dezhin** [comment]
Готово. URL

    /api/component/render/image?extent=...&size=...&resource=id1,id2
