### ISSUE TITLE
Картостиль при импорте слоя через NGM создаётся без переводов строк

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#354]
![image](https://cloud.githubusercontent.com/assets/4630662/9060798/d7585db4-3abf-11e5-8eb9-82531bdda172.png)

**Comment by simgislab** [comment]
может это NGM так отправляет?

**Comment by BishopGIS** [comment]
Да, он так и делает.

**Comment by drnextgis** [comment]
Закрываю, так как не имеет отношения к NGW.
