### ISSUE TITLE
Даты в окне инфотула

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#355]
Даты в окне инфотула отображаются некорректно - всегда на месяц больше. Если тот же объект на редактирование то дата отображается корректно.

**Comment by yellow-sky** [comment]
Закрыть связный https://github.com/nextgis/nextgisweb_compulink/issues/119

**Comment by dezhin** [comment]
Это я поправил в 8bdc34a717c82a8a8685cd55cc5e50778bbfa11e
