### ISSUE TITLE
180-й меридиан

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#358]
Файл с континентами со страницы http://openstreetmapdata.com/data/generalized-coastlines, land_polygons_z1

В NGW рисуется некорректно
![2015-08-07 12 57 25](https://cloud.githubusercontent.com/assets/4630662/9133381/deb98452-3d03-11e5-9997-8d1a09a610da.png)

http://demo.nextgis.ru/ngw/resource/46/display. Загружался через NGM из шейпа.

В QGIS тот же файл рисуется корректно
![land_qgis](https://cloud.githubusercontent.com/assets/4630662/9133404/05b5476c-3d04-11e5-8f81-dc8217ccf6e2.png)

В NGM тоже рисуется корректно
![2015-08-07 12 53 24](https://cloud.githubusercontent.com/assets/4630662/9133391/f0373756-3d03-11e5-8172-3b22296effcf.png)

Ссылка на файл: http://data.openstreetmapdata.com/land-polygons-generalized-3857.zip

**Comment by simgislab** [comment]
скорее всего это проблемы апстрим в GDAL, некорректная разрезка полигонов по 180 градусу: https://github.com/nextgis-borsch/lib_gdal/issues/22

здесь закрываю, потому что NGW непричем
