### ISSUE TITLE
Удаление пользователей

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#364]
Это уже не первый запрос, так как очень часто создают пользователей для тестов, а удалить нельзя. Это психологическая травма для юзеров :)

**Comment by yellow-sky** [comment]
Предлагается:
Добавить поле deleted. При удалении активировать его и не выводить его нигде в интерфейсах.
Самого пользователя переименовывать в некую служебную форму - Удаленный пользователь (Ваня Пупкуин, удален 10.08.2015).
Права сейчас можно оставлять как есть. Админы смогут изменить и владельца и удалить ненужные права.

**Comment by dezhin** [comment]
Тут вроде все просто, но я не очень все-таки понимаю. И я бы понял если бы речь шла о реальном удалении, которое мы не можем сделать по соображениям ссылочной целостности. Но в таком виде оно по-моему практически полностью пересекается с блокировкой и делает по сути то же самое.

Разница только в возможности выбирать и выводить где-то. Первое довольно странное: допустим мы сделали поиск ресурсов по владельцу и по логике этого тикеты мы не должны давать выбирать его в поле поиска. Но почему? Он же остался указан владельцем! Под "не выводить" я так понимаю имелось ввиду не показывать в списке пользователей. Это наверное возможно решить фильтром по отключенным пользователям.

И чего-то мне не приходит в голову ни одной похожей системы: в AD есть отключение и удаление, но удаление реальное. В 1С, где активно применяется отметка удаления типа предлагаемой, она по сути ни на что не влияет, можно выбрать, показывается в списках.

**Comment by simgislab** [comment]
В других системах проблема целостности при реальном удалении, как я понимаю, решается засчет переназначения всего другому юзеру, а без этого удалить пользователя нельзя.

**Comment by dezhin** [comment]
Есть разные подходы: не давать удалить пока есть ссылки, удалять но очищать ссылки, оставлять битые ссылки. Такого чтобы заменялось на какого-то другого я не видел, только руками некоторые так делают. Ну и первые два пункта в общем-то в распределенных системах проблематичено сделать.

**Comment by yellow-sky** [comment]
А почему мы сейчас не можем сделать честное удаление? Насколько я понимаю, все что нужно будет сделать - проверить правила и удалить если есть правила с этим чуваком и проверить группы и сделать аналогично. Или я что-то не увидел?

**Comment by dezhin** [comment]
Честное удаление с очисткой ссылок возможно в очень ограниченном круге ситуаций. Например, мы рано или поздно сделаем слой с историей изменений, где в истории будет фиксироваться пользователь сделавший правку. Удалять пользователя из истории объекта очень странно.

Опять таки всякие распределенные вещи, допустим какая-то внешняя система использовала NGW для аутентификации и хранила данные связанные с этим пользователем. Но тут внезапно пользователя удалили - это приведет в замешательство эту систему.

**Comment by yellow-sky** [comment]
Ок. давайте не будем удалять физически. Но тогда это не позволит создавать пользователя с таким же именем в последующем - это плохо. Поэтому я и предлагал переименовывать его.

**Comment by dezhin** [comment]
Ну переименовать то отключенного пользователя ничего не мешает.

**Comment by yellow-sky** [comment]
Но в интерфейсе то все равно пользователи  будут его видеть? И будет возможность использовать его при назначении прав? Это же не нормально.

**Comment by dezhin** [comment]
Конечно будут видеть, даже если бы пометка удаления была, то я выше писал о ситуациях где они были бы нужны. Ну а отключенные уж тем более нужны, это же обратимая операция.

Хотя конечно в интерфейсе какая-то индикация того что это отключенный пользователь безусловно нужна. Так же как нужно различать группы и пользователей, системные и не системные сущности.

**Comment by yellow-sky** [comment]
Мне кажется ты сильно путаешь удаленный и временно отключенный. Удаленный не должен нигде выводится. Вот создал я кривого пользователя и хочу удалить, как это сделать? Если я х*й написал в имя пользователя, то все, переставлять систему?
Удаленный остается только ссылочной целостности, но для интерфейса. Это основное отличие.  от временно отключенного, который везде может быть выбран.

**Comment by yellow-sky** [comment]
>>> допустим мы сделали поиск ресурсов по владельцу и по логике этого тикеты мы не должны давать выбирать его в поле поиска. Но почему? Он же остался указан владельцем! Под "не выводить" я так понимаю имелось ввиду не показывать в списке пользователей. Это наверное возможно решить фильтром по отключенным пользователям. >>>
А что мешает в этой функциональности (которой нет), выводить и удаленных тоже? Да в этом случае возможно имеет смысл выводить удаленных.
Но в списке пользователей, или в с писке назначения прав эти пользователи точно не нужны! И этот функционал уже есть.

**Comment by dezhin** [comment]
Ничего не мешает, но тогда в каждом месте придется решать, показывать удаленных это или нет. Допустим в правах, не показываем и не даем выбрать удаленного по твоей логике, но принципиально это ничего не меняет, мы точно так же остаемся с тем, что часть операций необратимы. Даже с теми же самыми пользователями: пользователя удалили, и мы ходим по правам и меняем его на того, кто пришел на его замену. Но случайно поменяли там, где пока неизвестно кто пришел на замену, теперь надо вернуть назад, но это невозможно.

**Comment by simgislab** [comment]
Резюмирую что решили:

1. В контрольной панели, списке пользователей появляется еще одна отдельная секция Deleted/Removed/Inactive
2. В редактировании конкретного пользователя появляется галка Delete/Remove/Make inactive. При взведении ее и сохранении пользователь перемещается в секцию из п.1
3. В виджетах выбора пользователей - "удаленные" пользователи НЕ показываются вообще, если только они не установлены уже как владельцы этого ресурса и т.п.
4. Для восстановления пользователя надо просто пойти в п.1 и снять галку п.2

**Comment by dezhin** [comment]
Я поправил немного третий пункт.

**Comment by BishopGIS** [comment]
#165 duplicated? May be close on of issue?

**Comment by simgislab** [comment]
удаление сделано
