### ISSUE TITLE
Отключить в GetCapabilities WFS возможность редактирования PostGIS

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#365]
Наверное, используя интерфейс `IWritableFeatureLayer`.

**Comment by simgislab** [comment]
а почему?

**Comment by drnextgis** [comment]
Потому что у нас не поддерживается сейчас редактирование PostGIS слоев, а в GetCapabilities написано, что поддерживается, в QGIS становится активной кнопка редактирования, пользователи редактируют данные, но сохранить изменения не могут.

**Comment by drnextgis** [comment]
Больше не актуально, так как теперь слои PostGIS редактируемые https://github.com/nextgis/nextgisweb/commit/6f702258bf0106de45d70be976eb3f2d14ec417d
