### ISSUE TITLE
А может сделать пользователя ресурсом?

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#369]
Тогда появятся классные плюшки:
1. Описание
2. Метаданные
3. Права на чтение свойств пользователей
4. Фотки!

**Comment by yellow-sky** [comment]
На удобство интерфейса это ни как не повлияет, имхо, а сейчас нам предоставляют требования именно к нему.

**Comment by dezhin** [comment]
Это здорово, все можно сделать ресурсом. Но я думаю это плохой путь, который только к излишнему усложнению приведет. Так что предлагаю это закрыть если никто не возражает.

**Comment by simgislab** [comment]
да, пока явно можно обойтись без этого
