### ISSUE TITLE
Добавить очистку таблицы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#370]
необходим запрос типа:
```
DELETE http://ngw_url/api/resource/{layerId}/feature/
```
по которому удаляются все записи таблицы. Сейчас можно удалить только одну.

**Comment by drnextgis** [comment]
Добавил в API, можешь потестить?

**Comment by BishopGIS** [comment]
Сделано в 59ed0e9637a3df0e2388160d9871b435beeaa466
