### ISSUE TITLE
Не импортируется стиль QGIS

### ISSUE THREAD

**Issue by paleogis** [nextgis/nextgisweb#371]
1.  Загрузил в нгв  слой дорог на  территорию Москвы из http://beryllium.gis-lab.info/project/osmshp/layer/highway-line 
2. Эскортировал стиль из qgis mapnik.
3. Попытался импортиовать стиль в нгв, но не получилось админка пишет  что природа ошибки не известна, хотя стиль административных границ был импортирован успешно
Вот сам текст проблемного стиля
https://yadi.sk/d/DKQKbCrbiQWW4

**Comment by drnextgis** [comment]
Из QGIS можно импортировать только самые простые стили. В остальных случаях стили нужно настраивать вручную.

**Comment by paleogis** [comment]
Спасибо! В таком случае  необходимо отметить  этот момент в документации.
С технической точки зрения возможна ли разработка  полноценной  поддержки  сложных стилей?

**Comment by drnextgis** [comment]
Да, полноценные стили QGIS поддерживаются путём подключения специального рендерера https://github.com/nextgis/nextgisweb_qgis
