### ISSUE TITLE
Ограничение на количество возвращаемых фич по WFS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#373]
Сейчас выставлено ограничение в **1000** возвращаемых фич. 
Соответственно при открытии в QGIS часть данных не получается. 
Для получения всех данных необходио добавить к пути WFS ключ 
```
MAXFEATURES=<количество фич> 
```

Про такую возможность не все знают. 
Есть пара вариантов:
1. На странице сервиса в ссылку сразу добавить этот параметр
2. Убрать ограничение

Кто, что думает?

**Comment by KolesovDmitry** [comment]
Чем хорошо ограничение, так это тем, что 

1) Работает на слабом соединении.
2) Можно получать данные по частям (через maxfeatures и startfeature), например, для получения 500 объектов из второй тысячи объектов нужно:
`
MAXFEATURES=500&startFeature=1000
`
Понятно, что есть и минусы -- все это усложняет логику клиента, когда ему нужно получить сразу все объекты.

Аналогичные параметры есть и в WFS 2.0 -- count и startIndex.

Эти параметры в стандартах помечены как опциональные параметры запроса. Поэтому можно смело отключать их. Тем не менее, если мне не изменяет память, обычно WFS сервера отдают данные по частям, а не сразу всей кучей.

**Comment by simgislab** [comment]
@KolesovDmitry что думаешь про идею вынести этот ключ в настройки NGW при инициализации
?

или вынести эту настройку в параметры слоя в WFS-сервера? Сделать по умолчанию равной 1000 и не давать возможности отключать совсем.

**Comment by KolesovDmitry** [comment]
@simgislab Думаю, что значение ключа очень сильно зависит от слоя и данных, которые в нем лежат. Поэтому, если выносить этот параметр в настройку, то конечно же в настройку слоя.

Думаю, что это сделать двольно просто (на серверном уровне знаю, как, на уровне интерфейса -- не очень).

**Comment by dezhin** [comment]
В похожей ситуации в REST API для объектов векторного слоя мы ничего не ограничиваем. Хотя это может быть проблемой с точки зрения производительности. Это то что касается верхнего ограничения. И я думаю тут нужно учитывать, что при изменяющихся данных скачивание данных через серию запросов с limit и offset может быть очень не тривиальным. И совершенно непонятно какую версию данных ресурса мы в итоге получим.

Что касается значения по-умолчанию, то проще и логичней разместить его в настройках конкретного wfs сервиса или даже слоя в нем.

На уровне слоя это тоже можно сделать с точки зрения интерфейса тут нет никаких проблем, отдельным виджетом это легко решается, но мне кажется это совсем не логично.

**Comment by simgislab** [comment]
@KolesovDmitry займись тогда этим, пожалуйста

**Comment by BishopGIS** [comment]
@dezhin 
```
Это то что касается верхнего ограничения. И я думаю тут нужно учитывать, что при изменяющихся данных скачивание данных через серию запросов с limit и offset может быть очень не тривиальным.
```
Мне кажется это решается на уровне WFS через транзакции.

**Comment by BishopGIS** [comment]
Тогда может тикет закрыть?
