### ISSUE TITLE
На странице ресурса для векторного слоя выводить тип геометри и количество записей и охват

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#374]
Сейчас для просомтра типа геотмерии надо смотреть представление реусрса в JSON а количество записей только примерно можно узнать из таблицы атрибутов.

**Comment by BishopGIS** [comment]
Добавлю еще охват слоя, и в JSON API вынести

**Comment by drnextgis** [comment]
Охват мне кажется тут ни к чему? Все равно в виде координат он сложно воспринимается.

**Comment by trolleway** [comment]
Ну пусть в API будет, а на экране не будет

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/issues/374

**Comment by dezhin** [comment]
Это сделает страницу недрступной, при отсутствии подключения к удаленному постгису.

**Comment by drnextgis** [comment]
Исправил в https://github.com/nextgis/nextgisweb/commit/a74e4b24c0d6be8d6965bbfe68067fde09844b3a, теперь не падает если база недоступна.

**Comment by dezhin** [comment]
Так оно может неопределенно долго выполняться, в API основное мы такое вроде решали не включать, тут по идее должна быть та же логика.

**Comment by drnextgis** [comment]
Тогда убираю из PostGIS, оставляю только для векторных слоёв.

**Comment by BishopGIS** [comment]
Это как-то криво. А нельзя запрашивать, а пока показыавть "нет данных". Придет ответ - отобразить, нет - ну так и останется.

**Comment by drnextgis** [comment]
Сводные данные о ресурсе у нас сейчас рендерятся на сервере, а не запрашиваются клиентом.

**Comment by BishopGIS** [comment]
PostGIS используется наравне с  векторными слоями. Ну он конечно менее популярен, но все таки в ходу. Так что вот так просто его выбросить - это не решение данного тикета. Тогда только переоткрывать и пусть висит до какого-то решения. 
Вот когда это будет сделано #298 - там такая же проблема будет.
