### ISSUE TITLE
В API представления ресурса векторного слоя в JSON давать количество записей

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#375]
При запросе описания векторного слоя в JSON не возвращается количество записей в векторном слое. Это нужно для показа статуса загрузки слоя в мобильное приложении.

**Comment by drnextgis** [comment]
Сделано в https://github.com/nextgis/nextgisweb/commit/5dc1d1b0cdbe53f36bdf1e1062f269335ef0b899

**Comment by dezhin** [comment]
Я думаю это все-таки лучше каким-то образом в REST API для записей перенести `/api/resource/{id}/feature/` которое. Не знаю как в REST это принято, может запрос OPTIONS или еще как, но сейчас довольно странно, мне кажется количество записей это не структура данных, а сами данные.

**Comment by BishopGIS** [comment]
Вы уж определитесь пожалуйста, а то мне уже это использовать надо.

**Comment by BishopGIS** [comment]
Да, тут выявился один нюанс. А запрашиваю данные по bbox и количество которые в описании ресурса не подходит для отображения процесса загрузки. Так что Саша прав, надо как то с результатом запроса выдавать количество записей в нем.

**Comment by dezhin** [comment]
Тут еще выяснили, что это изменение полностью блокирует REST API для postgis_layer в случае, если удаленный сервер недоступен или параметры подключения изменились - их даже поменять нельзя.

**Comment by dezhin** [comment]
Скоре всего проще всего будет реализовать отдельным урлом, типа `/api/resource/{id}/feature_count` с одним GET методом.

**Comment by drnextgis** [comment]
Готово.
