### ISSUE TITLE
Сделать в описании ресурса язык разметки markdown

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#380]
Он становится отраслевым стандартом, так сделано в ckan

**Comment by dezhin** [comment]
В моем понимании это все-таки гиковская штука больше. Для НЕ гиков это может быть проблемой.

**Comment by dezhin** [comment]
Кто чего по поводу этого думает помимо Артема и меня? Я так понимаю этот вопрос будет регулярно всплывать.

**Comment by simgislab** [comment]
мне кажется не нужно, markdown - для гиков, все действительно популярные системы для обычных пользователей это WYSIWYG, TinyMCE и т.д. То есть то что у нас уже и так есть.

**Comment by BushmanK** [comment]
Markdown - еще один стандарт разметки, который не делает её проще, он просто другой. Для html, например, есть куча визуальных редакторов на любой вкус для встраивания в страницу, в виде тулбара к browser-у и так далее.

**Comment by simgislab** [comment]
пока не видно необходимости
