### ISSUE TITLE
Переход к опубликованному ресурсу из сервиса

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#383]
При изменении сервиса (WMS, WFS) рядом с кнопкой "Удалить" сделать кнопку "Перейти", по которой происходит переход к выделенному ресурсу.

**Comment by drnextgis** [comment]
Эта кнопка будет дублировать кнопку `Назад` браузера?

**Comment by simgislab** [comment]
аналог ![](http://m-d.me/img/ss/CS1KLdF4PD.png)

**Comment by dezhin** [comment]
Это некоторое время назад сделано, везде есть ссылки теперь.
