### ISSUE TITLE
Новый способ вызова route поломал работу пространственных закладок

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#384]
Похоже, что вот [этот](https://github.com/nextgis/nextgisweb/commit/2a8ab482d5292d99512df07a63a5c8524af82889) коммит поломал работу пространственных закладок. Получаю в консоли такую ошибку:

```
Uncaught TypeError: route.feature_layer.store.item is not a function
```

**Comment by dezhin** [comment]
Вроде бы поправил в 7287ac1
