### ISSUE TITLE
Не соблюдается проверка прав на странице ресурса

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#386]
Если у пользователя нет прав на метаданные, то ему недоступно описание ресурса, но при этом на странице самого этого ресурса описание представлено. Пример: http://176.9.38.120/fv/resource/57 - описание есть (не должно быть) , http://176.9.38.120/fv/resource/57/update (вкладка Description) - описания нет (это правильно)

**Comment by simgislab** [comment]
исправлено
