### ISSUE TITLE
Не работает packages.ignore

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#387]
Может я что-то не так понимаю, но когда я в `packages.ignore` добавляю, например, `nextgisweb_mapserver`, то он всё равно не отключается.

**Comment by yellow-sky** [comment]
у меня аналогично. карта рисуется, в админке все создается

**Comment by dezhin** [comment]
Это я поправил. Но там остался нюанс связанный с тем, что невозможно определить какие типы ресурсов загружены, а какие нет. Из за этого например пункт меню создания стиля будет показываться для mapserver даже если его отключить. Это касается только пакетов где все в одном файле. Раньше то же самое было для отключения компонентов с components.ignore.

**Comment by drnextgis** [comment]
Чтобы избежать такого поведения, нужно компонент определять в отдельном Python-пакете, а не в файле `__init__.py` родительского пакета, в котором находится функция `pkginfo`.  В nextgisweb_mapserver так не сделано. Но особого в этом смысла нет, так как если ресурс однажды был создан, то если отключить соответствующий пакет, то возникнет ошибка.

**Comment by dezhin** [comment]
Вроде бы достаточно pkginfo выделить в отдельный файл и все.

**Comment by drnextgis** [comment]
А можешь на примере nextgweb_mapserver показать как это сделать, а то у меня что-то не получилось.
