### ISSUE TITLE
Чертить свои значки

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#388]
Сделать возможность задавать алгоритм черчения своих значков в картостиле, например как тут:
http://maperitive.net/docs/Properties/ShapeDef.html

Открываются возможности:
1. Создание текстур
2. Рисование значков для линейных объектов, наподобие мостов, каналов...

**Comment by dezhin** [comment]
В mapserver работает директива POINTS, которая как раз эту задачу и решает, хоть и в более ограниченном объеме.

**Comment by drnextgis** [comment]
auto-moving this issue to nextgis/nextgisweb_mapserver#12 and closing this one
