### ISSUE TITLE
При пустой подложке разрешить масштабирование до 20 или 22 зума.

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#390]
Если не включена тайловая подложка, то максимальный масштаб слишком мелкий, где-то 15 или 16 зум.  Нужно разрешить увеличивать до 22 зума, а то не получаются красивые скриншоты.

**Comment by dezhin** [comment]
Вообще я в 99a033b6bd08622f77fca95b375541b6d71975c4 недавно увеличивал до 20-го уровня для пустого слоя. Видимо нужно обновиться просто.
