### ISSUE TITLE
На веб-карте медленно загружаются иконки картографического виджета

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#392]
При открытии веб-карты иконки стали загружаться по 5 секунд, во время загрузки на их месте белые области. Раньше они загружались сразу.
Инстанс свежий, пятничный.
![2015-10-05 18 13 33](https://cloud.githubusercontent.com/assets/4630662/10284541/2aed6570-6b8d-11e5-8dfe-4775e78ae407.png)

**Comment by drnextgis** [comment]
Видимо, какие-то проблемы с сетью были.
