### ISSUE TITLE
Не валидируется название ключей

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#396]
Каким-то образом, возможно через вызов API, в WFS сервисе были созданы невалидные ключи (key) - пробелы, русские буквы и т.п.
Необходимо валидировать ключи на уровне вызова АПИ.

**Comment by edpop** [comment]
Добавлена валидация и контроль уникальности keyname слоёв WFS https://github.com/nextgis/nextgisweb/blob/d6ccb23c909f3021ebab2d60cc74e3165cd4935a/nextgisweb/wfsserver/model.py#L73. Необходимо аналогично проделать для WMS.

**Comment by edpop** [comment]
Поправлено для WMS тоже.
