### ISSUE TITLE
При создании подключения PostGIS нет trim для данных

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#397]
Пользователь может при создании указать концевой пробел в параметрах подключения.

**Comment by dezhin** [comment]
Это конечно довольно странно, так делать, но в PostGIS нет ограничений на идентификаторы пользователей, баз и таблиц - там вполне себе могут быть пробелы и в конце и в начале.

**Comment by trolleway** [comment]
Понятно, тогда не стоит
