### ISSUE TITLE
Если в вебе есть ресурс "новый ресурс", которую создали с другого компьютера, то новая папка не создаётся

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#399]
Идёт обучение на нескольких компьютерах.
Все запускают менеджер, коннектятся в веб, заходят в одну папку.
Внутри все создают папку со своей фамилией.
Один из пользователей нажимает "создать группу", и ему выдаётся ошибка "Группа с именем "Новая группа" уже создана".
Похоже, что во время работы менеджера другой юзер с другого компа уже создал такую папку, и ещё не переименовал.

Хотя этот случай встречается очень редко, только при обучении.

**Comment by BishopGIS** [comment]
Это не баг НГВ, это "особенность" НГМ.
