### ISSUE TITLE
Обновление OSM

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#40]
В веб ГИС необходимо предусмотреть ряд модулей для подключения сервисов NextGIS - геокодирование, выгрузки, пикетаж и т.п.
Сервис выгрузок должен обеспечивать:
- указание источника выгрузок
- возможность остановки выгрузок
- откат к предыдущему обновлению (например, если нужны локальные данные ОСМ, а они поломались) - не более одного шага
  - задание расписания обновления
- предустановленные стили отрисовки слоев ОСМ в Веб ГИС

**Comment by drnextgis** [comment]
Видимо, этому тикету место где-то в другом репозитории.
