### ISSUE TITLE
Во вкладке правки атрибутов нет прокрутки

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#400]
Если во всплывающем окне выбрать кнопку редактирования атрибутов, то в открывшемся окне нет прокрутки.

![2015-10-20 23 32 50](https://cloud.githubusercontent.com/assets/1708122/10620425/ae15d4da-7783-11e5-8770-03c7f6184c10.png)

**Comment by yellow-sky** [comment]
Либо связанно, либо дубляж - https://github.com/nextgis/nextgisweb/issues/330

**Comment by drnextgis** [comment]
Похоже что дубль, сам сегодня с такой же проблемой столкнулся.
