### ISSUE TITLE
Исправлять невалидные символы в названиях полей для загрузки слоя

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#402]
При загрузке geojson с русскими атрибутами создаётся слой, но с недопустимыми названиями полей

![image](https://cloud.githubusercontent.com/assets/4630662/10789794/a323e0b8-7d90-11e5-8b9c-4a221c0cac16.png)

**Comment by trolleway** [comment]
Надо что бы пользователю предлагалось: "Транслитерировать названия полей", "Прекратить импорт"

**Comment by simgislab** [comment]
а они недопустимые?

**Comment by BishopGIS** [comment]
Так по скринщоту же видно, восклицательные знаки не просто так!
Тем более вот еще #396

**Comment by dezhin** [comment]
Восклицательные убираем в рамках поддержки кириллических символов для wfs, в целом план - разрешить любые символы в качестве названий полей, чтобы было консистентно c qgis / ogr.
