### ISSUE TITLE
Инструмент контроля правильности бэкапа

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#403]
Нужен способ проверить, что бэкап сделался правильно. 
Сейчас из-за того, что размеры НГВ и бэкапа в папку отличаются - пользователи не могут понять. Возможно стоит писать лог бэкапирования, где в конце должно быть что-то типа SUCCESS 100% done

**Comment by dezhin** [comment]
Так по идее есть такой критерий - успешное завершение команды `nexgisweb backup`. Можно наверное сделать так, чтобы бэкап ngw во временный файл бэкап делал, а потом его уже переименовывал. Так как перименование атомарно, то наличие выходного файла тоже было бы критерием. Хотя и тут есть нюансы всякие.

**Comment by BishopGIS** [comment]
Завершение команды не дает явного сообщения что все ОК. Можно хотя бы его вставить

**Comment by dezhin** [comment]
Можно добавить, но насколько я понимаю в подобных случаях оно довольно редко выводится. В pg_dump например, который схожую функцию выполняет его нет. 

Ну а если кому-либо нужно сообщение, то он же может его сам добавить, причем любое, и даже не только сообщение: `nextgisweb backup ... && echo MESSAGE`

**Comment by simgislab** [comment]
все сделано
