### ISSUE TITLE
При показе картинки в веб-карте крутилка в lightbox наполовину закрыта белым дивом.

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#406]
![2015-11-13 13 59 20](https://cloud.githubusercontent.com/assets/4630662/11144589/cf1a6efa-8a0e-11e5-85fc-42fcd2c5e7a2.png)

**Comment by drnextgis** [comment]
@trolleway ещё актуально?

**Comment by simgislab** [comment]
давно не видел такой проблемы
