### ISSUE TITLE
Увеличить размер точки, которая принимает принимает нажатия мышкой для идентификации

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#410]
При показе точек из svg, при пользовании инструментом идентификации надо щёлкать очень точно. Нужно немного увеличить размер точки, которая слушает нажатия мышкой.

**Comment by dezhin** [comment]
По-моему у нас была настройка identify_radius!

**Comment by KoGor** [comment]
А разве там не через полигон идентификация идёт? http://docs.nextgis.ru/docs_ngweb_dev/doc/developer/misc.html
Соответственно вокруг точки строится bbox-полигон  с указаным "радиусом".

**Comment by dezhin** [comment]
Да в API полигон. Но этот полигон строится на клиенте исходя из identify_radius. То есть это полигон уже с радиусом.

**Comment by drnextgis** [comment]
Радиус идентификации можно задать в файле `config.in`, значение указывается в пикселах:

```
[webmap]

# Чувствительность идентификации
identify_radius = 5
```
