### ISSUE TITLE
Не импортируется цвет линии из стиля QGIS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#411]
При импорте стиля из QGIS для линейного объекта не импортируется цвет.
Для точек и полигонов все ок.

Вот пример стиля. 
[Границы КО 200000.qml.zip](https://github.com/nextgis/nextgisweb/files/59391/200000.qml.zip)

**Comment by drnextgis** [comment]
auto-moving this issue to nextgis/nextgisweb_mapserver#10 and closing this one
