### ISSUE TITLE
Пакетное удаление записей

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#413]
Сейчас можно удалить либо конкретную запись, либо все.
Необходимо добавить возможность удаления набора записей
Что-то типа DELETE /api/resource/(int: layer_id)/&feature=(int: id1),(int: id2)...

**Comment by BishopGIS** [comment]
В разрезе всех фич сделано (см. http://docs.nextgis.ru/docs_ngweb_dev/doc/developer/change.html#delete-all-features)

**Comment by simgislab** [comment]
реализовать поддержку транзакций в API (поддержка нескольких запросов в одной транзакции)

**Comment by dezhin** [comment]
Удаление нескольких фич было реализовано некоторое время назад. Про транзакции подумаем, может быть сделаем, может быть нет - пока не понятно. Но наверное это другой тикет.
