### ISSUE TITLE
При наличии записи без геометрии слой не создаётся.

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#414]
Имеется шейп-файл со всеми зданиями Москвы 2011 года. Нужны тайлы.

Гружу в NGW.
![2016-01-04 06 45 29](https://cloud.githubusercontent.com/assets/4630662/12081768/abb44666-b295-11e5-8782-01aed026987e.png)

Гружу в cartodb - слой рисуется.

Ожидаемое поведение: если в загружаемом файле геометрия с ошибками, то импорт не должен прекращаться.

**Comment by BishopGIS** [comment]
Как временное решение можно загрузить через manager - он обрабатывает эту ситуацию.

**Comment by dezhin** [comment]
Тут нужно просто с подходом определиться. Это не единственная проблема, которая может не дать загрузить слой. Это и кодировки и топология и отсутсвие стстемв координат. Нужно опрелелиться, мы во что бы то ни стало как нибудь пытаемся загрузить слой или же не грузим слой, если не можем загрузить его корректно. Сейчас выбрано последнее, можно выбрать по-другому, но тоже будут проблемы, просто немного другие.

**Comment by simgislab** [comment]
мне нравится текущий подход, но боюсь, что с точки зрения пользователей, лучше если слой бы загружался во что бы то ни стало, с соответствующими ворнингами.

Важно помнить про пользователей, которые никаких правок геометрий сделать не смогут, вообще.

**Comment by simgislab** [comment]
@trolleway проверь еще раз, пожалуйста

**Comment by trolleway** [comment]
Поведение осталось
[nogeom.zip](https://github.com/nextgis/nextgisweb/files/4930493/nogeom.zip)

**Comment by trolleway** [comment]
Так же сделал geojson с пустой геометрией, поведение такое же. Оба geojson валидны.
![Снимок экрана от 2020-07-16 12-29-31](https://user-images.githubusercontent.com/4630662/87654855-27fe8180-c760-11ea-8b4e-e90b02bc456b.png)
[nogeom_brackets.zip](https://github.com/nextgis/nextgisweb/files/4930594/nogeom_brackets.zip)

**Comment by dezhin** [comment]
В последнем большом обновлении мы добавили много разных опций, которые позволяют загрузить практически любые данные с ошибками.
