### ISSUE TITLE
Не могу добавить на веб карту векторный слой

### ISSUE THREAD

**Issue by paleogis** [nextgis/nextgisweb#417]
Не могу в административной панели добавить векторный слой на веб карту, кнопка добавления векторного слоя неактивна ( см. скриншот)
![_054](https://cloud.githubusercontent.com/assets/5592860/12820549/976db900-cb70-11e5-986d-6bade775462b.png)

**Comment by BishopGIS** [comment]
На веб карту можно добавить только стиль для слоя. См. http://docs.nextgis.ru/docs_ngweb/source/mapstyles.html и http://docs.nextgis.ru/docs_ngweb/source/webmaps_admin.html#ngweb-map-create и

**Comment by paleogis** [comment]
Дмитрий! Спасибо что ответил, однако я как раз не вижу заветной опции Добавить стиль ‣ Стиль MapServer.
![_055](https://cloud.githubusercontent.com/assets/5592860/12836762/bff79c54-cbcc-11e5-8f65-a1085b905c0b.png)

**Comment by simgislab** [comment]
Стиль зависит от векторного слоя и создается ИЗ него. Т.е. 
1. Создал слой
2. зашел в него
3. создал стиль

**Comment by BishopGIS** [comment]
Не установлен компонент nextgisweb_mapserver, поэтому и опции нет. Какая
выдача pip freeze ?
05 февр. 2016 г. 8:37 пользователь "Maxim Dubinin" <notifications@github.com>
написал:

**Comment by simgislab** [comment]
да нет же, у нас попробуй найти

![](http://m-d.me/img/ss/20160205-696-62kb.jpg)

**Comment by paleogis** [comment]
Спасибо за ответы. Вот что мне вываливает консоль:
root@p347995:~# pip freeze
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
html5lib==0.999
pycurl==7.19.3
python-apt==0.9.3.5ubuntu2
requests==2.2.1
six==1.5.2
urllib3==1.7.1
virtualenv==14.0.5
wheel==0.24.0
wsgiref==0.1.2

**Comment by simgislab** [comment]
то что я пишу никто не читает что ли?
бестолку такой pip freeze

**Comment by paleogis** [comment]
Максим я безусловно все читаю, спасибо за ответы, но в меню редактирования векторного слоя нет опции " загрузить стиль", Где она находится, пока понять не могу
![_056](https://cloud.githubusercontent.com/assets/5592860/12841287/b60a4db6-cbfb-11e5-8914-18431dfb379a.png)

**Comment by simgislab** [comment]
ну так это совершенно другой скриншот и тут действительно надо воспользоваться советом Димы, но по другому

Панель инструментов - Версии пакетов - Ищи nextgisweb_mapserver, есть-нет?

**Comment by paleogis** [comment]
Спасибо, Максим! Действительно нет в списке nextgisweb_mapserver, попробую его установить

**Comment by paleogis** [comment]
К сожалению установка mapserver  произошла с ошибками, буду разбираться 
root@p347995:~# sudo apt-get install python-mapscript
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
python-mapscript is already the newest version.
обновлено 0, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 34 пакетов не обновлено.
root@p347995:~# mkdir env/lib/python2.7/site-packages/mapscript.egg
mkdir: cannot create directory ‘env/lib/python2.7/site-packages/mapscript.egg’: No such file or directory
root@p347995:~# cd ngw
root@p347995:~/ngw# mkdir env/lib/python2.7/site-packages/mapscript.egg
root@p347995:~/ngw# cp /usr/lib/python2.7/dist-packages/*mapscript* \
> env/lib/python2.7/site-packages/mapscript.egg
root@p347995:~/ngw# echo "./mapscript.egg" > env/lib/python2.7/site-packages/mapscript.pth
root@p347995:~/ngw# env/bin/pserve development.ini
Exception:
Traceback (most recent call last):
  File "/root/ngw/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/root/ngw/env/local/lib/python2.7/site-packages/pip/commands/freeze.py", line 70, in run
    for line in freeze(**freeze_kwargs):
  File "/root/ngw/env/local/lib/python2.7/site-packages/pip/operations/freeze.py", line 49, in freeze
    dependency_links
  File "/root/ngw/env/local/lib/python2.7/site-packages/pip/__init__.py", line 260, in from_dist
    req = dist.as_requirement()
  File "/root/ngw/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2697, in as_requirement
    if isinstance(self.parsed_version, packaging.version.Version):
  File "/root/ngw/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2566, in parsed_version
    self._parsed_version = parse_version(self.version)
  File "/root/ngw/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2604, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file", mapscript [unknown version] (/root/ngw/env/lib/python2.7/site-packages/mapscript.egg))
Starting server in PID 32543.
serving on http://0.0.0.0:6543

**Comment by BishopGIS** [comment]
Не все шаги выполнены (http://docs.nextgis.ru/docs_ngweb/source/install.html#nextgis-web-mapserver)
Не увидел:
```
mkdir env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO
touch env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO/PKG-INFO
```
и
```
echo `python -c "import mapscript; print 'Version: %s' % mapscript.MS_VERSION"` > env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO/PKG-INFO
```

еще потом надо убедится что все ок
```
env/bin/pip freeze
```

**Comment by paleogis** [comment]
Спасибо, Дмитрий! Все сделал по твоей инструкции, но фокир пьяный, и еще что-то с githab  не загрузилось 
root@p347995:~# mkdir env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO
mkdir: cannot create directory ‘env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO’: No such file or directory
root@p347995:~# cd ngw
root@p347995:~/ngw# mkdir env/lib/python2.7/site-packages/mapscript.egg/EGG-INFOroot@p347995:~/ngw# touch env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO/PKG-INFO
root@p347995:~/ngw# echo `python -c "import mapscript; print 'Version: %s' % mapscript.MS_VERSION"` > env/lib/python2.7/site-packages/mapscript.egg/EGG-INFO/PKG-INFO
root@p347995:~/ngw# env/bin/pip freeze
Babel==2.2.0
bunch==1.0.1
flufl.enum==4.1
GeoAlchemy==0.7.2
geojson==1.3.2
lxml==3.5.0
Mako==1.0.3
mapscript==6.4.2
MarkupSafe==0.23
-e git+https://github.com/nextgis/nextgisweb.git@dbe40d07d84f700e9b2fa8c0a1832c16397fc86f#egg=nextgisweb
numpy==1.10.4
OWSLib==0.10.3
passlib==1.6.5
PasteDeploy==1.5.2
Pillow==3.1.0
psycopg2==2.6.1
pygdal==1.11.2.3
Pygments==2.1
pyproj==1.9.5.1
pyramid==1.6
pyramid-debugtoolbar==2.4.2
pyramid-mako==1.0.2
pyramid-tm==0.12.1
python-dateutil==2.4.2
pytz==2015.7
repoze.lru==0.6
requests==2.9.1
Shapely==1.5.13
six==1.10.0
SQLAlchemy==0.8.7
transaction==1.4.4
translationstring==1.3
unicodecsv==0.14.1
venusian==1.0
waitress==0.8.10
WebOb==1.5.1
wheel==0.26.0
zope.deprecation==4.1.2
zope.interface==4.1.3
zope.sqlalchemy==0.7.6
root@p347995:~/ngw# env/bin/pserve development.ini
Starting server in PID 32701.
serving on http://0.0.0.0:6543

**Comment by paleogis** [comment]
Пока не могу понять,  ошибка на вашей стороне, или у меня кривые руки.

**Comment by BishopGIS** [comment]
Вот эти пункты были выполнены: 
http://docs.nextgis.ru/docs_ngweb/source/install.html#mapserver
?

**Comment by paleogis** [comment]
Да выполнял и еще раз повторил,
Смущает следующие:
 -e git+https://github.com/nextgis/nextgisweb.git@dbe40d07d84f700e9b2fa8c0a1832c16397fc86f#egg=nextgisweb
-e git+https://github.com/nextgis/nextgisweb_mapserver.git@257ad0210141d43da6c66018f2a251b0a3f8cadf#egg=nextgisweb_mapserver




root@p347995:~/ngw# git clone https://github.com/nextgis/nextgisweb_mapserver.git
Cloning into 'nextgisweb_mapserver'...
remote: Counting objects: 738, done.
remote: Total 738 (delta 0), reused 0 (delta 0), pack-reused 738
Receiving objects: 100% (738/738), 1.38 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (480/480), done.
Checking connectivity... done.
root@p347995:~/ngw# env/bin/pip install -e ./nextgisweb_mapserver
Obtaining file:///root/ngw/nextgisweb_mapserver
Requirement already satisfied (use --upgrade to upgrade): nextgisweb in ./nextgisweb (from nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): geojson in ./env/lib/python2.7/site-packages (from nextgisweb-mapserver===0.0dev-r0)
Collecting ply (from nextgisweb-mapserver===0.0dev-r0)
/root/ngw/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/root/ngw/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading ply-3.8.tar.gz (157kB)
    100% |████████████████████████████████| 159kB 545kB/s 
Requirement already satisfied (use --upgrade to upgrade): pyramid>=1.5 in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy<0.9,>=0.8 in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): transaction in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): pyramid-tm in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): pyramid-debugtoolbar in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): pyramid-mako in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): zope.sqlalchemy in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): zope.interface in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): bunch in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): flufl.enum in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): waitress in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): pygdal<=1.11.2.9999,>=1.11.2.0 in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): geoalchemy>=0.7.2 in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): shapely in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): unicodecsv in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): pillow in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): lxml in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): passlib in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): owslib>=0.9.2 in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): requests in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): babel in ./env/lib/python2.7/site-packages (from nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./env/lib/python2.7/site-packages (from geojson->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): repoze.lru>=0.4 in ./env/lib/python2.7/site-packages (from pyramid>=1.5->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): PasteDeploy>=1.5.0 in ./env/lib/python2.7/site-packages (from pyramid>=1.5->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): WebOb>=1.3.1 in ./env/lib/python2.7/site-packages (from pyramid>=1.5->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): translationstring>=0.4 in ./env/lib/python2.7/site-packages (from pyramid>=1.5->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): zope.deprecation>=3.5.0 in ./env/lib/python2.7/site-packages (from pyramid>=1.5->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): venusian>=1.0a3 in ./env/lib/python2.7/site-packages (from pyramid>=1.5->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): Pygments in ./env/lib/python2.7/site-packages (from pyramid-debugtoolbar->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): Mako>=0.8 in ./env/lib/python2.7/site-packages (from pyramid-mako->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.0.0 in ./env/lib/python2.7/site-packages (from pygdal<=1.11.2.9999,>=1.11.2.0->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=1.5 in ./env/lib/python2.7/site-packages (from owslib>=0.9.2->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): pyproj in ./env/lib/python2.7/site-packages (from owslib>=0.9.2->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): pytz in ./env/lib/python2.7/site-packages (from owslib>=0.9.2->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in ./env/lib/python2.7/site-packages (from Mako>=0.8->pyramid-mako->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./env/lib/python2.7/site-packages (from python-dateutil>=1.5->owslib>=0.9.2->nextgisweb->nextgisweb-mapserver===0.0dev-r0)
Building wheels for collected packages: ply
  Running setup.py bdist_wheel for ply ... done
  Stored in directory: /root/.cache/pip/wheels/d9/34/fe/b9f5d00d8690911944b0c24811ed7f5fb2c5d89f9c4d6053c7
Successfully built ply
Installing collected packages: ply, nextgisweb-mapserver
  Running setup.py develop for nextgisweb-mapserver
Successfully installed nextgisweb-mapserver ply-3.8
root@p347995:~/ngw# env/bin/pip freeze
Babel==2.2.0
bunch==1.0.1
flufl.enum==4.1
GeoAlchemy==0.7.2
geojson==1.3.2
lxml==3.5.0
Mako==1.0.3
mapscript==6.4.2
MarkupSafe==0.23
-e git+https://github.com/nextgis/nextgisweb.git@dbe40d07d84f700e9b2fa8c0a1832c16397fc86f#egg=nextgisweb
-e git+https://github.com/nextgis/nextgisweb_mapserver.git@257ad0210141d43da6c66018f2a251b0a3f8cadf#egg=nextgisweb_mapserver
numpy==1.10.4
OWSLib==0.10.3
passlib==1.6.5
PasteDeploy==1.5.2
Pillow==3.1.0
ply==3.8
psycopg2==2.6.1
pygdal==1.11.2.3
Pygments==2.1
pyproj==1.9.5.1
pyramid==1.6
pyramid-debugtoolbar==2.4.2
pyramid-mako==1.0.2
pyramid-tm==0.12.1
python-dateutil==2.4.2
pytz==2015.7
repoze.lru==0.6
requests==2.9.1
Shapely==1.5.13
six==1.10.0
SQLAlchemy==0.8.7
transaction==1.4.4
translationstring==1.3
unicodecsv==0.14.1
venusian==1.0
waitress==0.8.10
WebOb==1.5.1
wheel==0.26.0
zope.deprecation==4.1.2
zope.interface==4.1.3
zope.sqlalchemy==0.7.6
root@p347995:~/ngw#

**Comment by BishopGIS** [comment]
Решили проблему - не была БД инициализирована.
