### ISSUE TITLE
Как добавить легенду к векторному слою 

### ISSUE THREAD

**Issue by paleogis** [nextgis/nextgisweb#418]
Как можно добавить легенду к векторному слою на веб-карте? В доках ответа не нашел.
![_060](https://cloud.githubusercontent.com/assets/5592860/12873333/12e81c22-cdcb-11e5-8977-98402fbab21c.png)

**Comment by drnextgis** [comment]
Пока такой возможности нет.

**Comment by paleogis** [comment]
В принципе стандартная фича, рекомендую к добавлению в базовый функционал

**Comment by drnextgis** [comment]
See https://github.com/nextgis/nextgisweb/issues/497
