### ISSUE TITLE
Ожидаемых свойств нет в интерфейсах

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#421]
Создаю новый класс, реализующий интерфейс `IFeatureLayer`, но этого оказывается недостаточно, нужно добавить ещё свойства `feature_label_field_id` и `feature_label_field`, иначе возникают ошибки. Если где-то подразумевается, что ресурс должен содержать данные поля, то может это имеет смысл вынести в отдельный интерфейс?

**Comment by simgislab** [comment]
нужно корректное сообщение об ошибке

**Comment by dezhin** [comment]
Если проблема все еще актуальна, лучше переоткрыть. Все эти поля объявлены в LayerFieldsMixin.
