### ISSUE TITLE
Не правильный тип геометрии слоя PostGIS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#424]
В НГВ все векторные слои приводятся к мульти. И тип слоя POINT == MULTIPOINT и т.д.
В случае слоя PostGIS геомтерии могут быть как мульти так и не мульти. Однако тип всегда мульти и установить реальный тип геометрии не получается. При этом запросы данных по АПИ возвращают геометрии в правильного типа POINT(...) и MULTIPOINT(...).
Правильный тип геометрии нужен для редактирвания на мобильном и в перспективе для драйвера GDAL.
Предлагаю расширить http://176.9.38.120/doc/docs_ngweb_dev/doc/developer/vector_data_types.html#nextgisweb.feature_layer.interface.GEOM_TYPE
стандартными типами геометрий:
POINT,
LINESTRING,
POLYGON,
MULTIPOINT,
MULTILINESTRING,
MULTIPOLYGON

**Comment by dezhin** [comment]
Вроде бы сделал, пока в виде отдельного бранча - geomtype. Пока потестил довольно ограниченно.

**Comment by BishopGIS** [comment]
А в результате как сделано? Теперь для стандартного векторного слоя (который всегда мульти) будут какие типы возвращаться?

**Comment by dezhin** [comment]
Сделано так, что поли и не поли теперь совершенно разные типы, соответственно если загружен не мульти, то будет не мульти и возвращаться.

**Comment by drnextgis** [comment]
В `MIGRATE.md` в концу два раза подряд идёт один и тот же набор команд, я так понял в одном случае там должен быть `vector_layer`? А откуда взялись эти CONSTRAINT-ы c 1 на конце?

**Comment by 4eRTuk** [comment]
Для слоя http://demo.nextgis.ru/ngw/resource/129 через API отдается тип POINT - http://demo.nextgis.ru/ngw/api/resource/129, а геометрии все в MULTIPOINT - http://176.9.38.120/fv/api/resource/64/feature/

**Comment by drnextgis** [comment]
Ожидаемо. Там сейчас другой бранч.

**Comment by drnextgis** [comment]
Правильные типы геометрий поселились в `3` ветке.
