### ISSUE TITLE
Права на сервисы WFS

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#425]
Назначаю на группу ресурсов такие права для пользователя:

```
Allow    username    Resource: All permissions    All resources    Yes
```

При этом не могу получить GetCapabilities на WFS сервис из этой группы ресурсов. Если права привести к такому виду, то все начинает работать:

```
Allow    username    Resource: All permissions    All resources    Yes
Allow    username    Service: All permissions     All resources    Yes
```

Так и задумано?

**Comment by dezhin** [comment]
Да, так и задумано. `Resource: All permissions` - подразумевает только те права, которые вот тут перечислены - https://github.com/nextgis/nextgisweb/blob/2/nextgisweb/resource/scope.py#L23. Чтобы дать все возможные права там же есть пункт `All resources: All permissions`. Видимо имелся ввиду он.

**Comment by dezhin** [comment]
Второе же поле `All resources` это по сути фильтр по типу ресурсов где будет применяться это правило.

**Comment by drnextgis** [comment]
Спасибо, с этим разобрался. Ещё такой вопрос. На корневой группе ресурсов выставлено право:

```
Allow    Гость    Resource:Read    All resources    No
```

При попытке обратиться в дочерний ресурс `/api/resource/236` получаю:

```
{"exception": "HTTPForbidden", "message": "Unknown exception 'HTTPForbidden'."}
```

Но при этом `GetCapabilities` WFS сервиса, находящегося внутри группы ресурсов `id=236` отрабатывает. Нет ли тут противоречия в том, что в корне явно не разрешён доступ в эту группу, но при этом WFS работает. Права на группу `id=236`:

```
Allow    username    All resources: All permissions    All resources    Yes
```

**Comment by dezhin** [comment]
Думаю это исправлено в 4247c1ef25761fddd4e664bcb3d8241db9034939
