### ISSUE TITLE
WFS c запросом OUTPUTFORMAT=geojson&BBOX= выдаёт ответ в gml

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#426]
http://demo.nextgis.ru/ngw/api/resource/255/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=enef2&SRSNAME=EPSG:4326&MAXFEATURES=3&OUTPUTFORMAT=geojson
выдаёт ответ в geojson

http://demo.nextgis.ru/ngw/api/resource/255/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=enef2&SRSNAME=EPSG:4326&MAXFEATURES=3&OUTPUTFORMAT=geojson?bbox=37.46260643005371,55.84481950825524,37.51410484313965,55.86409011279356
выдаёт ответ в формате gml, а я просил - в geojson

**Comment by drnextgis** [comment]
Это не баг, просить можно в чём угодно, но по стандарту WFS обязан поддерживать только GML, всё остальное - по желанию разработчиков.

**Comment by simgislab** [comment]
мнение @dezhin **не надо реализовывать geojson в WFS**
