### ISSUE TITLE
Упорядочивание списка ресурсов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#428]
В окне выбора ресурса выводить список слоев упорядоченным по алфавиту, иначе очень трудно найти нужный слой
![image](https://cloud.githubusercontent.com/assets/1277422/13781235/ad62640e-ead3-11e5-897d-173e9c366560.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/a641e62d3fee7e9c98d00b58141219d9f819c784

**Comment by yellow-sky** [comment]
Работает
