### ISSUE TITLE
Заменить в настройке прав название субъекта "Everyone" на "Everyone authendificated / Любой залогиненый".

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#429]
Заменить в настройке прав название субъекта "Everyone" на "Everyone authendificated / Любой залогиненый".
Сейчас кажется, что незалогиненый запрос должен попадать туда, а он не попадает.

![2016-03-17 13 04 11](https://cloud.githubusercontent.com/assets/4630662/13842723/d53b45cc-ec40-11e5-98e3-fd19b5b8e20d.png)

**Comment by dezhin** [comment]
Everyone - любой пользователь, в том числе не аутентифицированный. Authenticated - аутентифицированный соответственно.

**Comment by trolleway** [comment]
Значит в коде неправильно обрабатывается. Если назначить права Everyone на весь инстанс, то для незалогиненого пользователя не выдаётся /api/resource/29

**Comment by dezhin** [comment]
`/api/resource/29` это где?

**Comment by trolleway** [comment]
http://176.9.38.120/practice2/api/resource/29

**Comment by drnextgis** [comment]
Всё нормально работает. Просто у тебя для Everyone не стояла галка Распространять.
