### ISSUE TITLE
Данные в таблице на вкладке «Права доступа» упорядочивать по столбцу «Субъект» (по алфавиту)

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#430]
По умолчанию данные в таблице на вкладке «Права доступа» упорядочивать по столбцу «Субъект» (по алфавиту). 
Проблема в том, что при большом количестве пользователей достаточно трудно отыскать нужного пользователя, чтобы убедиться что у него есть доступ. 
Кстати, сортировка по данному столбцу работает некорректно.

**Comment by drnextgis** [comment]
А можно пример, где некорректно работает сортировка?

**Comment by yellow-sky** [comment]
![image](https://cloud.githubusercontent.com/assets/1277422/16423311/3298baa0-3d64-11e6-88d9-422c2dd07540.png)

**Comment by drnextgis** [comment]
В https://github.com/nextgis/nextgisweb/commit/71a405d5da7579cd609027a3651558a25aaf6edf сортировка починена, если кликнуть на имени поля, то должно правильно сортироваться.

**Comment by yellow-sky** [comment]
Денис, нужно включить по умолчанию сортировку в этом столбце

**Comment by drnextgis** [comment]
В https://github.com/nextgis/nextgisweb/commit/44ef2d09a382c8357989ebc5ec32893fa21b5216 добавлена сортировка по умолчанию.

**Comment by yellow-sky** [comment]
Работает
