### ISSUE TITLE
WFS-T возвращает не все данные которые ожидает GDAL

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#434]
При работе с WFS-T из GDAL (создание новой записи) показывается следующая ошибка: 

```
ERROR 1: Cannot find InsertResults.Feature.FeatureId
```

а в случае выполнения этого же кода внутри транзакции:

```
ERROR 1: Cannot find InsertResults
```

Код для воспроизведения:

``` python
from osgeo import ogr
from osgeo import gdal

wfst_url = 'http://176.9.38.120/practice2/api/resource/49/wfs'

gdal.SetConfigOption('CPL_DEBUG', 'ON')

ds = ogr.Open('WFS:' + wfst_url, update = 1)
if ds is None:
    exit() # 'fail'

lyr = ds.GetLayer(0)
print 'layer name: ' + lyr.GetName()

geom = ogr.CreateGeometryFromWkt('POINT(234000 890000)')
feat = ogr.Feature(lyr.GetLayerDefn())
feat.SetGeometry(geom)
feat.SetField('NAME', 'nameSetByOGR')
feat.SetField('SCADA_ID', '10')

# Test transactions
#if lyr.StartTransaction() != 0:
#    print 'StartTransaction() failed'
#    exit() # 'fail'

ret = lyr.CreateFeature(feat)
if ret != 0: # <-- тут ошибка
    print('fail on CreateFeature')
    exit() # 'fail'

# Test transactions
#if lyr.CommitTransaction() != 0:
#    print 'CommitTransaction() failed'
#    exit() # 'fail'

feat.SetField('NAME', 'nameSetByOGR1')
ret = lyr.SetFeature(feat)
if ret != 0:
    print('fail on SetFeature')
    exit() # 'fail'

gmlid = feat.GetField('gml_id')

ds.ExecuteSQL("DELETE FROM test_wfst WHERE gml_id = '%s'" % gmlid)

print('ok')
```

GDAL 2.1.

Вот парсинг результаттов ответа сервера:
- https://github.com/OSGeo/gdal/blob/trunk/gdal/ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp#L1971
- https://github.com/OSGeo/gdal/blob/trunk/gdal/ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp#L2552

Они говорят, что для GDAL это обязательно должно возвращаться.

**Comment by KolesovDmitry** [comment]
Запустил пример кода на своей копии, в качестве ответа приходит такой:
```
<?xml version="1.0" ?>
<wfs:TransactionResponse
version="1.0.0"
    xmlns:wfs="http://www.opengis.net/wfs"
    xmlns:ogc="http://www.opengis.net/ogc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/wfs ../wfs/2.0.0/WFS-transaction.xsd">

    <wfs:TransactionSummary>
        <wfs:totalInserted>1</wfs:totalInserted>   
    </wfs:TransactionSummary>
           <wfs:InsertResult>
                    <ogc:FeatureId fid="2"/>
                    </wfs:InsertResult><wfs:TransactionResult>
                        <wfs:Status><wfs:SUCCESS/></wfs:Status>
                </wfs:TransactionResult></wfs:TransactionResponse>
```
В общем-то там присутствует FeatureId.
Вот пример из стандарта 02-058_Web_Feature_Service_WFS:
```
<?xml version="1.0" ?>
<wfs:TransactionResponse
 version="1.0.0"
 xmlns:wfs="http://www.opengis.net/wfs"
 xmlns:ogc="http://www.opengis.net/ogc"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.opengis.net/wfs ../wfs/1.0.0/WFS-transaction.xsd">
 <wfs:InsertResult handle="STMT1">
 <ogc:FeatureId fid="SOMEFEATURE.4567"/>
 <ogc:FeatureId fid="SOMEFEATURE.4568"/>
 <ogc:FeatureId fid="SOMEFEATURE.4569"/>
 </wfs:InsertResult>
 <wfs:InsertResult handle="STMT2">
 <ogc:FeatureId fid="FEATURE1.4569"/>
 </wfs:InsertResult>
 <wfs:InsertResult handle="STMT3">
 <ogc:FeatureId fid="FEATURE2.389345"/>
 </wfs:InsertResult>
 <wfs:TransactionResult handle="TX01">
 <wfs:Status>
 <wfs:SUCCESS/>
 </wfs:Status>
 </wfs:TransactionResult>
</wfs:TransactionResponse> 
```
Единственное отличие на InsertResult -- у нас нет параметра handle, но, как я понял, он не обязателен.

Пока у меня только одно подозрение: возможно, GDAL ожидает данные в формате WFS-2 или WFS-1.1.0. Это я проверю отдельно, по результатам отпишусь.

**Comment by BishopGIS** [comment]
Подправил код - что бы был отладочный вывод.

Я так понимаю есть 2 типа запросов:

1. Вставка сразу
2. Вставка внутри транзакции

Твой пример именно в транзакции и там GDAL ищет  InsertResults - хотя тоже не работает.
А вот для вставки вне транзакции ответ должен быть видимо такой:

```xml
<InsertResults>
  <Feature>
    <FeatureId fid='2'/>
  </Feature>
</InsertResults>
```

Еще в твеом примере version 1.0.0 и схема такая же, а у нас version 1.0.0 а схема 2.0.0

**Comment by KolesovDmitry** [comment]
Несколько замечаний:
 * У нас в версии 1.0.0 возвращается TransactionResponse (точнее, wfs:TransactionResponse), это соответствует спецификации.
 * В версии 1.0.0 согласно спецификации ответ идет именно InsertResult, а не InsertResults. В версии 2.0.0 -- наоборот, нужно InsertResults, а не InsertResult (вообще в спецификациях разных версий введена куча таких мелких отличий, которые не очевидны).
 * Если в GDAL не поддерживается версия 1.0.0, то бесполезно тестировать эту версию через GDAL. Нужно тогда переводить тестирование на версию 2.0.0.
 * Если запросить сразу версию 2.0.0, но получаем ошибку "Server is read-only WFS; no WFS-T feature advertized", с этим нужно разбираться отдельно: #435

**Comment by dezhin** [comment]
Думаю это можно закрыть, саму проблему с ожидаемым ответом зарепортил сюда https://github.com/OSGeo/gdal/issues/3323
