### ISSUE TITLE
Ошибка при установке на Ubuntu 16.04

### ISSUE THREAD

**Issue by madw0lf** [nextgis/nextgisweb#439]
при выполнении
 env/bin/pip install -e ./nextgisweb
вылетает ошибка:
Collecting owslib>0.11.0 (from nextgisweb==2.0)
  Could not find a version that satisfies the requirement owslib>0.11.0 (from nextgisweb==2.0) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10, 0.8.11, 0.8.12, 0.8.13, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.3, 0.11.0)
No matching distribution found for owslib>0.11.0 (from nextgisweb==2.0)

**Comment by drnextgis** [comment]
Временное решение - уберите OWSLib из `setup.py` и поставить руками из [репозитория](https://github.com/geopython/OWSLib), как только выйдет следующий релиз OWSLib - проблема решиться сама собой.

**Comment by drnextgis** [comment]
Вышел OWSLib 0.11.1, проблема больше не актуальна.

**Comment by madw0lf** [comment]
спасибо)
