### ISSUE TITLE
Не работает запрос фич в wfs по bbox

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#440]
Если создать WFS-сервис, подключить его в QGIS, и выбрать 
![2016-04-29 18 07 03](https://cloud.githubusercontent.com/assets/4630662/14920249/30e896de-0e35-11e6-8f93-6762932ec3db.png)
то слой не добавляется с ошибкой
![2016-04-29 18 05 36](https://cloud.githubusercontent.com/assets/4630662/14920227/192e2806-0e35-11e6-89c0-a380ad1708bd.png)

**Comment by drnextgis** [comment]
Closed via https://github.com/nextgis/nextgisweb/commit/c4226fcec4d56e5d96781c814d630426218b385e
