### ISSUE TITLE
режутся поля ввода имени и пароля (дизайн)

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#441]
видимо с редизайном как-то связано

![](http://m-d.me/img/ss/20162629-182618.png)

**Comment by drnextgis** [comment]
Это и раньше так было в некоторых браузерах. @lisovenkoNastya можно тебя попросить переделать эту форму для логина, Dojo виджет мне кажется здесь не очень уместен, да и размещён он как-то не по центру.
