### ISSUE TITLE
Добавить в NGW кнопку вызова справки

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/nextgisweb#442]
В верхней панели нужна кнопка вызова справки. По клику на кнопку:
- из русской локали - в новом окне должна открываться страница http://nextgis.ru/help/
- из английской локали - в новом окне должна открываться страница http://nextgis.ru/en/help/

**Comment by Kinda-me** [comment]
Для английской локали должна использоваться новая ссылка - http://nextgis.com/help/

**Comment by dezhin** [comment]
Я поменял, после обновления будут новые ссылки.
