### ISSUE TITLE
Иконки для списка ресурсов в диалогах создания веб-карты и wms-сервиса

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#443]
![ogportalngwcreatewfs3](https://cloud.githubusercontent.com/assets/4630662/15146778/e4583d80-16c5-11e6-87ac-dd87610c1d6c.png)

На этом списке нужны более понятные иконки, а лучше - вместо иконок надписи.
Нужны иконки (нужно показать сущности) 
- Группа ресурсов
- Векторный слой
- Векторный стиль
- Растровый стиль

...

Сейчас очень громоздкие формулировки получаются в документации.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/e91309fe9cb8cad0a229d73af88d7901c53ca74e and https://github.com/nextgis/nextgisweb/commit/a37cee98fe10c3f565702cbf130fe1b17911c9ea. Thanks to @lisovenkoNastya.
