### ISSUE TITLE
Поправить "QGIS vector style" на "Стиль QGIS" в русской локали

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/nextgisweb#444]
![qgis style](https://cloud.githubusercontent.com/assets/6493848/15218433/99f52178-1868-11e6-8d17-276e0e5a4da1.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb_qgis/commit/506de87958b88fb1a5c8afde5bcbae36e14cb09c
