### ISSUE TITLE
Поправить название вкладки "MapServer" на "Стиль MapServer"/"MapServer style"

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/nextgisweb#445]
![mapserver](https://cloud.githubusercontent.com/assets/6493848/15218531/0942d052-1869-11e6-987b-70fb89fb612c.png)

![mapserver en](https://cloud.githubusercontent.com/assets/6493848/15218569/32502ce2-1869-11e6-9110-ca23fbdc5fe6.png)

**Comment by drnextgis** [comment]
Closed via https://github.com/nextgis/nextgisweb_mapserver/commit/43fa747195941926d97b4f4da27efa9e485e97c2
