### ISSUE TITLE
перевод Групп пользователей

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#447]
в англ просто Groups, лучше User groups
http://m-d.me/img/ss/20165217-095224.png

в ру Группы пользователей, а не Группы
http://m-d.me/img/ss/20165117-095158.png

**Comment by simgislab** [comment]
решили что лучше изменить ру-версию на просто Группы

**Comment by drnextgis** [comment]
Сделано https://github.com/nextgis/nextgisweb/commit/491005774780ffaa959e3a0fac4b8eaeee3de4be

**Comment by simgislab** [comment]
@tonynovi
