### ISSUE TITLE
Ошибка pygdal при обновлении. ubuntu 16.04

### ISSUE THREAD

**Issue by madw0lf** [nextgis/nextgisweb#451]
~/ngw$ gdal-config --version
2.1.0

Collecting pygdal<=2.1.0.9999,>=2.1.0.0 (from nextgisweb==3.0)
  Could not find a version that satisfies the requirement pygdal<=2.1.0.9999,>=2.1.0.0 (from nextgisweb==3.0) (from versions: 1.8.1.0, 1.8.1.1, 1.8.1.2, 1.8.1.3, 1.9.2.0, 1.9.2.1, 1.9.2.3, 1.10.0.0, 1.10.0.1, 1.10.0.3, 1.10.1.0, 1.10.1.1, 1.10.1.3, 1.11.0.0, 1.11.0.1, 1.11.0.3, 1.11.1.0, 1.11.1.1, 1.11.1.3, 1.11.2.1, 1.11.2.3, 1.11.3.3, 1.11.4.3)
No matching distribution found for pygdal<=2.1.0.9999,>=2.1.0.0 (from nextgisweb==3.0)

**Comment by drnextgis** [comment]
Ожидаемо, потому что в PyPI пока нет `pygdal==2.1.0`, отправил PR, как будет готово - отпишусь.

**Comment by drnextgis** [comment]
@madw0lf проверьте сейчас, обновили pygdal в PyPI.

**Comment by madw0lf** [comment]
спасибо) но это уже числа после 12 июня. сессия..

**Comment by drnextgis** [comment]
Переоткройте, если будут какие-то проблемы.

**Comment by madw0lf** [comment]
собственно, та же проблема, но другая версия
Collecting pygdal<=2.1.2.9999,>=2.1.2.0 (from nextgisweb==3.0)
  Could not find a version that satisfies the requirement pygdal<=2.1.2.9999,>=2.1.2.0 (from nextgisweb==3.0) (from versions: 1.8.1.0, 1.8.1.1, 1.8.1.2, 1.8.1.3, 1.9.2.0, 1.9.2.1, 1.9.2.3, 1.10.0.0, 1.10.0.1, 1.10.0.3, 1.10.1.0, 1.10.1.1, 1.10.1.3, 1.11.0.0, 1.11.0.1, 1.11.0.3, 1.11.1.0, 1.11.1.1, 1.11.1.3, 1.11.2.1, 1.11.2.3, 1.11.3.3, 1.11.4.3, 1.11.5.3, 2.0.0.3, 2.0.1.3, 2.0.2.3, 2.0.3.3, 2.1.0.3, 2.1.1.3)
No matching distribution found for pygdal<=2.1.2.9999,>=2.1.2.0 (from nextgisweb==3.0)
