### ISSUE TITLE
Не загружается shp, если в нём есть мультигеометрии

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#456]
Не загружается shp, если в нём есть мультигеометрии [#4939](https://trac.osgeo.org/gdal/ticket/4939) из-за кривизны формата, может вообще откажемся от него? Кто согласен?)

**Comment by BishopGIS** [comment]
На замену нужен какой-то форматец, GeoJSON тяжеловат. 
Например, geopackage.

**Comment by simgislab** [comment]
не не, вы что! мультигигабайтные geojson'ы загружать - не айс
в будущем конечно откажемся, но пока явно рано

**Comment by simgislab** [comment]
закрываю, от шейпов пока точно не отказываемся
