### ISSUE TITLE
Не переведено название "пустой" подложки в Web Map

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/nextgisweb#459]
![default](https://cloud.githubusercontent.com/assets/6493848/15611559/807030e0-2433-11e6-83d6-2fd689567420.png)

**Comment by dezhin** [comment]
Это проблематично перевести в текущем варианте работы с базовыми слоями. Могу если оперативно, то на английское название поменять.

**Comment by Kinda-me** [comment]
Да, мне кажется, тогда лучше английское название.

**Comment by drnextgis** [comment]
В документации это переведено как "No basemap".

**Comment by simgislab** [comment]
остановились на None
