### ISSUE TITLE
Ссылка на язык картостиля

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#46]
![webgis mark language](https://f.cloud.github.com/assets/4630662/1983332/72441d64-8413-11e3-9e4e-c9a17b9fd818.jpg)
Оформления некоторых слоёв не конвертируются из QGIS, нужно сочинять их вручную. Не могу найти описание языка, потому что у MapServer qml несколько другой.

**Comment by dezhin** [comment]
Ссылка на доки у нас давно есть, конечно можно было бы в нужное место на конкретный раздел ссылку вставить или вообще как-то интегрировать это в ngw. Но вряд ли этот тикет про это. В целом mapserver, особенно в таком виде мы вряд ли планируем развивать.
