### ISSUE TITLE
При постинге ссылок на веб-карту в facebook/vk/ok должна быть картинка.

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#460]
Сейчас 
![image](https://cloud.githubusercontent.com/assets/4630662/15619405/c4a5c724-245c-11e6-950b-f6b3f4a5cd0b.png)

Как надо:
![image](https://cloud.githubusercontent.com/assets/4630662/15619425/d1ff7442-245c-11e6-8b07-8ad8eb3c023d.png)
Обратите внимание: тот сервис специально монтирует красивую обложку для шаринга из нескольких картинок.

У facebook это реализовано через этот стандарт метаданных: http://ogp.me/
Так же там есть теги для названия, description, и возможно для работы статистики.

vk вроде бы поддерживает этот стандарт
twitter вроде бы поддерживает этот стандарт, плюс свои теги: https://dev.twitter.com/cards/getting-started

**Comment by BishopGIS** [comment]
Да, я тоже обратил внимание, что картинки нет и  все как-то уныло.

**Comment by lisovenkoNastya** [comment]
добавила PR для ngw c параметрами для постов в соц.сетях.
Нужно добавить перевод для строки:  ${tr(_('Your Web GIS at nextgis.com'))}
По-русски должно быть так:  "Ваши карты - онлайн. Веб ГИС от nextgis.com"

**Comment by simgislab** [comment]
сделано, может пока подглюкивать из-за переносов сайта nextgis на новый сервер (освобождение гислаба) и днсов
