### ISSUE TITLE
Кнопки шаринга ссылки на карту в соцсети

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#461]
Кнопки должны показываться на экране там же, где сейчас "ссылка на карту". После нажатия на "ссылка на карту" сейчас появляется окно с написанным url, туда же добавить кнопки шаринга в соцсети.

Преимущества:
1. Юзер сможет написать сопроводительный текст
2. По крайней мере у fb такие кнопки чего-то дают к статистике.

Хотя не знаю, какой от этого будет эффект, может и не быть резона.

**Comment by simgislab** [comment]
а мне кажется отдельно должно быть, там где i в правом нижнем углу, стандартные три точки как на мобильных "раскладывающиеся" в fb, vk, twitter

**Comment by karavanjo** [comment]
Closed as an exact duplicate of https://github.com/nextgis/nextgisweb/issues/492
