### ISSUE TITLE
Изменение имени веб ГИС через административный интерфейс

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#463]
Сейчас имя и еще ряд параметров (какой ресурс открывать по-умолчанию при запросе корня и т.д.) упрятано в конфиг, нужно вынести это в панель настройки веб ГИС.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/d0344a69f9ff6cefa95f02c751f1d602487f0674
