### ISSUE TITLE
Не загружается векторный слой в nextgis.com

### ISSUE THREAD

**Issue by paleogis** [nextgis/nextgisweb#465]
Пишет что "msgstr неизвестная ошибка 'DataError'
Думаю что проблемы с  спецсимволами в таблице атрибутов или около того. Шейп в приложении.
[12.zip](https://github.com/nextgis/nextgisweb/files/289902/12.zip)

**Comment by simgislab** [comment]
пожалуйста, перенеси тикет вот сюда: https://github.com/nextgis/nextgis.com-webgis/issues
