### ISSUE TITLE
В пермалинке 2 параметра center, facebook ломает ссылку

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#468]
Пермалинк: http://trolleway.nextgis.com/resource/1/display?base=osm-mapnik&center=4186225.1110264496&center=7511413.743427706&resolution=76.43702828517625&styles=5

Facebook чинит ссылку: http://trolleway.nextgis.com/resource/1/display?base=osm-mapnik&center=7506651.236802304&resolution=76.43702828517625&styles=35

Нужно что бы параметры назывались по-разному, а то нельзя постить ссылки в facebook.

**Comment by simgislab** [comment]
речь про два раза center, это действительно странно, может нужно сделать centerx, centery

еще явно завышена разрядность у значений

**Comment by drnextgis** [comment]
@simgislab до какого знака округлять?

**Comment by simgislab** [comment]
не против!

если мы оставляем цифры в 3857, то округлять можно отбрасывая дробную часть целиком
если мы конвертируем их в 4326 (что лучше), то 4 знака после запятой будет достаточно

**Comment by drnextgis** [comment]
Исправил в https://github.com/nextgis/nextgisweb/commit/f03e5c85f804c059ef9442c979f59b5b65012007. Координаты теперь передаём в 4326, поэтому пусть будет `lon`, `lat`. Также  заменил `resolution` на `zoom`.

**Comment by simgislab** [comment]
отлично!

**Comment by drnextgis** [comment]
Проверьте, сейчас нормально шарится? http://176.9.38.120/practice2/resource/8/display

**Comment by simgislab** [comment]
судя по https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2F176.9.38.120%2Fpractice2%2Fresource%2F8%2Fdisplay%3Fbase%3Dosm-mapnik%26lon%3D40.7071%26lat%3D56.2556%26zoom%3D9%26styles%3D

все нормально, но надо чтобы Артем еще что-нибудь расшарил попробовал живое

**Comment by trolleway** [comment]
Вроде норм. 
https://www.facebook.com/artem.svetlov.94/posts/972944099492172?pnref=story
Правда теперь на ссылках на standalone-инстансы будет реклама nextgis.com.
