### ISSUE TITLE
При создании векторного слоя Unknown exception 'IntegrityError'

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/nextgisweb#469]
Через основной сайт nextgis.com создал ГИС.

Через веб-админку создал resource group:
Create resource -- Resource group

Заполнил поля
Display name = ResGroup proba1
Keyname = proba1

Зашел через
Main resource group -- ResGroup proba1
в свою новую группу. В ней пытаюсь создать vector layer:
Create resource -- Vector layer

Заполняю поля
Display name = VectorL proba2
Keyname = proba2
Parent = уже заполнен как ResGroup proba1, выбрать другое нет возможности.

Нажимаю "Create and edit", получаю в диалоге с кнопкой ОК сообщение об ошибке:
Unexpected error occurred during the operation. Error message:
Unknown exception 'IntegrityError'.

**Comment by drnextgis** [comment]
Всё правильно, нужно перейти на вкладку `Векторный слой` и загрузить сами данные.

**Comment by simgislab** [comment]
Но опять же, эта ошибка про более толковое сообщение об ошибке типа: 

"No data. Forgot to upload data layer?"

**Comment by lisovenkoNastya** [comment]
Подтверждаю возникновение ничего не говорящей ошибки при создании векторного слоя без данных:
![image](https://cloud.githubusercontent.com/assets/16019740/15834129/91ea9c64-2c32-11e6-9b76-33852ee163c1.png)

Подобная ошибка появляется при создании WMS слоя без данных:
![image](https://cloud.githubusercontent.com/assets/16019740/15834237/18fdc7da-2c33-11e6-87b3-94b04e76be58.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/c7a0a0ec32f608b5fc9a3549558e6bf424cad4af
