### ISSUE TITLE
Падает при загрузке большого векторного слоя geojson

### ISSUE THREAD

**Issue by ANAT01** [nextgis/nextgisweb#470]
### Описание проблемы

При попытке загрузить 500мб geojson - сервер падает (запущен через env/bin/pserve)

1) Загружаем большой файл
2) Нажимаем "Сохранить" векторный слой.
В это время съедается вся оперативная память, - у меня ее 0,5гб RAM и 4гб swap
3) После исчерпания памяти pserver падает. Файл остается на сервере в папке upload и доступа к нему через web-интерфейс нет (чтобы удалить или еще что с ним сделать)

Проблема явно с нехваткой памяти. Нужно как то предупреждать (рассчитывать) допустимый объем загрузки, а также делать что-то с загруженными но не используемыми файлами (чистить upload)
### Версии пакетов
- Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2] on Linux-3.13.0-71-generic-x86_64-with-Ubuntu-14.04-trusty
- nextgisweb    3.0 c4226fce

**Comment by drnextgis** [comment]
Инструмент для удаления неиспользуемых файлов имеется:

```
(env)rykov@work:~/git/ngw2$ nextgisweb --config config.ini file_upload.cleanup
Deleted |    518 files |      0 directories |   1855555797 bytes |
Kept    |     56 files |    463 directories |     47214641 bytes |
```
