### ISSUE TITLE
Копирование адреса WFS и WMS сервиса в один клик

### ISSUE THREAD

**Issue by lisovenkoNastya** [nextgis/nextgisweb#471]
![image](https://cloud.githubusercontent.com/assets/16019740/15806172/3be3ab22-2b46-11e6-88ab-ccc36cda2c0e.png)

При наведении на блок с адресом WMS или WFS сервиса показывать в углу сообщение "click to copy adress"  и при клике копировать в буфер обмена адрес сервиса

**Comment by edpop** [comment]
Сделал выделение в один клик https://github.com/nextgis/nextgisweb/commit/417ffe562493f5ea9b6adbefb7c833be6c26766e
