### ISSUE TITLE
Автокликер

### ISSUE THREAD

**Issue by liarsd** [nextgis/nextgisweb#473]
Доброго возможно ли штатными средствами включить режим идентификации (на постоянной основе) объектов на карте? Если не предусмотрено было бы актуально ввести, мы показывали возможности бесплатной ГИС платформы вашей на семинаре и 80% присутствующих спрашивали об этом.
Спасибо

**Comment by simgislab** [comment]
а что значит
>режим идентификации (на постоянной основе) объектов на карте

**Comment by liarsd** [comment]
Иконка которую (кружок с синим воскл. знаком) нажимаешь на вебкарте, для последующего нажатия на  отображаемом объекте, для получения информации о объекте,

**Comment by simgislab** [comment]
что такое инструмент идентификации понятно

я хотел услышать, что значит "постоянная основа"

**Comment by liarsd** [comment]
Простите, видимо, не ясно выразился, имеется в виду, чтобы не было необходимости его нажимать,  то есть, чтобы он был включен по умолчанию, при отображении слоя на веб карте, или как вариант иметь возможность включения данной функции например с админ панели.

**Comment by drnextgis** [comment]
Уже есть такой тикет https://github.com/nextgis/nextgisweb/issues/133
