### ISSUE TITLE
АПИ получения данных слоя в бинарном виде

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#475]
Сейчас АПИ типа /api/resource/feature и /api/resource/feature/<id> отдают данные в json. Для больших данных получается большой объем и долгий парсинг.
Предлагается дополнить АПИ бинарным протоколом для передачи таких данных. 
Варианты:
- http://wiki.fasterxml.com/SmileFormatSpec
- http://bsonspec.org/
- http://ubjson.org/
- http://bjson.org/
- https://developers.google.com/protocol-buffers/ 

При этом должны кодироваться не только атрибуты, но и геометрии. Как минимум WKT надо на WKB заменить или иное бинарное представление.

**Comment by simgislab** [comment]
https://github.com/mapbox/geobuf

**Comment by BishopGIS** [comment]
Protobuffers — это неправильно - https://habr.com/post/427265/

**Comment by dezhin** [comment]
Обсудили еще раз это. Мы могли бы добавить на равне с JSON еще MsgPack, но похоже это никому особо не нужно, консенсуса нету. Тут скорее вопрос про эффективную синхронизацию.
