### ISSUE TITLE
Загрузка файла если нет прав на создание слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#476]
Если нет прав на создание слоя, но доступ на чтение ресурсов, то можно загрузить файл. Сообщение о отсутствии прав появится только при попытке создать слой.
Тут может быть проблема, что на сервер зальют какой ни будь мусор. Хорошо если только место съедят, а может и вредоносное что-то.

**Comment by simgislab** [comment]
больше не актуально, UI больше не позволяет создавать или редактировать слои если нет соответствующих прав
