### ISSUE TITLE
В URL веб-карты заменить запятые на точки с запятой

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#477]
Ссылка на веб-карту выглядит так: http://trolleway.nextgis.com/resource/1/display?base=osm-mapnik&lon=37.7491&lat=55.6881&angle=0&zoom=11&styles=97,96
При постинге ссылки в vk.com она обрезается по первой запятой, таким образом поделится ссылкой на веб-карту таким способом невозможно.
![workspace 1_090](https://cloud.githubusercontent.com/assets/4630662/16084951/2f39186e-3323-11e6-9946-e0f8a67d5935.png)
Предлагаю заменить в URL запятую на точку с запятой, такая ссылка не ломается.

**Comment by trolleway** [comment]
Проверил тот же кейс на ok.ru, facebook.com, plus.google.com - там везде запятая остаётся.

**Comment by simgislab** [comment]
проблем с фб нет

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Ftrolleway.nextgis.com%2Fresource%2F1%2Fdisplay%3Fbase%3Dosm-mapnik%26lon%3D37.7491%26lat%3D55.6881%26angle%3D0%26zoom%3D11%26styles%3D97%2C96
