### ISSUE TITLE
После создания веб-карты писать её tms url

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#478]
Так же как при создании WMS: 
![image](https://cloud.githubusercontent.com/assets/4630662/16092543/fd8ae270-3340-11e6-8851-b2e808b01fd0.png)
Выводить 2 строки: URL карты, и URL tms-сервиса с активными по умолчанию слоями, например

```
http://trolleway.nextgis.com/api/component/render/tile?z={z}&x={x}&y={y}&resource=42,45
```

А то после перехода на OpenLayers3 невозможно просто эти адреса через Debug браузера выковыривать.

**Comment by dezhin** [comment]
Это было реализовано некоторое время назад.
