### ISSUE TITLE
В форме входа не переводится сообщение "Invalid login or password!"

### ISSUE THREAD

**Issue by lisovenkoNastya** [nextgis/nextgisweb#480]
![image](https://cloud.githubusercontent.com/assets/16019740/16152454/a56e89f0-34aa-11e6-8984-e30b371ca495.png)

**Comment by drnextgis** [comment]
Так вроде уже нет этой формы?

**Comment by lisovenkoNastya** [comment]
а сообщение об ошибке осталось. И оно по-прежнему не переводится, хотя перевод для этой строки есть

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/2edd2bb6a0ed1b01188ae467ff6d63cae8dba6e1
