### ISSUE TITLE
У страниц, где осуществляется закачка, показывать индикатор в <title>

### ISSUE THREAD

**Issue by BushmanK** [nextgis/nextgisweb#481]
При загрузке, например, растрового файла, иногда это происходит весьма долго. Было бы удобно видеть проценты в заголовке страницы (перед существующим заголовком, чтобы можно было видеть это даже на сравнительно небольших вкладках browser-а).

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/048edd2d86be4fe1688986f3699348f165187856
