### ISSUE TITLE
Показывать на веб-карте красивым шрифтом название и описание

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#482]
Как на cartodb (это у них в редакторе так, а на самой веб-карте выводится просто текстом ниже картодвижка)
![2016-06-30 17-07-54](https://cloud.githubusercontent.com/assets/4630662/16491207/b010682a-3ee5-11e6-8e08-41ef74833872.png)

Вывод названия и описания по умолчанию должен быть включён, в настройках веб-карты его должно быть можно выключать.

Сейчас каждый раз когда я публикую ссылку на карту со своими данными, мне приходится пояснять, что на ней такое.

**Comment by BushmanK** [comment]
Title не читают, да.

**Comment by lisovenkoNastya** [comment]
Заголовок и описание добавлены на карту
https://github.com/nextgis/nextgisweb/commit/b5e5b8eed5f814cf78c5a9d587e15237504f7e6c
