### ISSUE TITLE
Add the possibility of getting a file with qml-style.

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgisweb#484]
For QGIS style resource.

Needed to apply this style to imported into the QGIS layer.

**Comment by dezhin** [comment]
Готово, но требуются некоторые улучшения.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb_qgis/commit/64131db358b51738160b864bb45f4d8d027cf15d
