### ISSUE TITLE
Add table and map icons to children resources table

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#485]

**Comment by lisovenkoNastya** [comment]
Map icon was fixed in https://github.com/nextgis/nextgisweb/commit/c956b42603131e58449b0a64f3f19d71fe341390

**Comment by lisovenkoNastya** [comment]
Table-icon for postgis layers https://github.com/nextgis/nextgisweb/commit/ec4c179e173d21ffd2bc3ebbf52defeda6e1d2eb
