### ISSUE TITLE
Заблокированные пользователи в списке выводились серым цветом

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#486]

**Comment by drnextgis** [comment]
Имеется в виду вот этот список `/auth/user/`? Сейчас обнаружил, что заблокированные пользователи выводятся в списке пользователей при настройке прав на ресурсы - это нормально?

**Comment by lisovenkoNastya** [comment]
Приглушила цвет заблокированных пользователей
https://github.com/nextgis/nextgisweb/commit/2b1dbb32964d505fd586ca516167d130750ae81b

**Comment by yellow-sky** [comment]
Работает
