### ISSUE TITLE
Перечень ресурсов в окне выбора ресурса-родителя должен быть упорядочен по алфавиту

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#487]
![image](https://cloud.githubusercontent.com/assets/1277422/16843202/f57f1a4c-49e8-11e6-9c91-ba9df02d2192.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/a641e62d3fee7e9c98d00b58141219d9f819c784

**Comment by yellow-sky** [comment]
Работает
