### ISSUE TITLE
При попытке создать пользователя с уже существующим логином вылетает непонятное сообщение об ошибке

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#489]
![image](https://cloud.githubusercontent.com/assets/1277422/16911400/ef0efe38-4ce6-11e6-892f-70b160d72a8b.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/2f7d5903f82ee00ed77b450b310b9ee839a5a227

**Comment by yellow-sky** [comment]
работает
