### ISSUE TITLE
Добавить кнопки для публикации веб-карты в социальных сетях

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb#492]
Для начала - Facebook, Twitter, Google+, VKontakte.

**Comment by karavanjo** [comment]
Implemented by https://github.com/nextgis/nextgisweb/commit/98294b08c2bb14a276d1807b82b1272d809383f1, https://github.com/nextgis/nextgisweb/commit/417daed0bf31a7cb5c37f0365a7f57ca0ef8b4b7, https://github.com/nextgis/nextgisweb/commit/c61278a0c908a9bbf4ebc21345ad341fbc8231fb, https://github.com/nextgis/nextgisweb/commit/373a440fe0be1b98650927f7db26b56f5591dd75.

**Comment by simgislab** [comment]
а дай ссылку где можно потестить, можно прям сюда

**Comment by karavanjo** [comment]
Развернуто для тестирования (https://github.com/nextgis/nextgisweb/commit/553301cadf62303e331b49eb5420868ee901dbe7) по этому [адресу](http://176.9.38.120/ngw-karavanjo-demo/resource/1/display).

**Comment by dezhin** [comment]
С включенным AdBlock карта не показывается вообще, падает с какой-то ошибкой в консоли.

**Comment by drnextgis** [comment]
Кнопки шаринга перекрывают контрол сброса поворота карты.

**Comment by lisovenkoNastya** [comment]
Переместила кнопку сброса поворота карты https://github.com/nextgis/nextgisweb/commit/fcc855c25df112fbc2de17516c9fd4b4a1def86e

**Comment by drnextgis** [comment]
@lisovenkoNastya на iPad кнопка сброса поворота наползает на кнопку с минусом.
