### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#497]
Add legend!

Suggested implementation:
1. Determine geometry type (point, multipoint, line, multiline ... etc.) for each layer. Use predetermined primitives as icons for drawing the legend.
2. Determine if there is just one class or multiple (single symbol or unique value or graduated symbol)
3. For each subclass - determine color of the outline and color of fill
4. Put them all together in one chart, i.e.: 
   - single class: layer name (heading), icon -> layer name, 
   - multiple classes: layer name (heading), for each class icon -> layer name
5. For raster layers - use a placeholder icon.

Reserve a section of layer tree on the left to output constructed legend.

Make legend a part of webmap settings (new tab).

Allow to set:
- Turn legend on checkbox
- Legend title: 'Legend' or 'Условные обозначения' etc
- something else ...

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/32a481d6a1b6d1221441914ab6fed8f0c0c1fa75
