### ISSUE TITLE
allow adding zipped geojsons

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#498]
when creating vector layers, saves bandwidth (upload time) for a user

these are already understood by QGIS and NGM

**Comment by drnextgis** [comment]
Может не заниматься ручной распаковкой zip-архивов, а отдать это на откуп GDAL-у? Только единственное, что опция `CPL_VSIL_ZIP_ALLOWED_EXTENSIONS` появилась в [1.11.0](https://trac.osgeo.org/gdal/wiki/Release/1.11.0-News). Завёл под это бранч https://github.com/nextgis/nextgisweb/tree/vsizip Проверил на запакованных GeoJSON-ах, всё работает.

**Comment by dezhin** [comment]
Fixed in bea953340b3cad87282b889644a3554f6a76a99c
