### ISSUE TITLE
Report NGW limitations

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#501]
Need API method to report about NGW limitations:
1. Max size of upload files - this is not only NGW but web server too, but if I upload 1.5Gb file and in 500Mb it stops - it's a pity, some warning before uploading will be welcome.

May be in administrative interface create a resource to set such limitations metadata. Special key-value storage which applications can request via API. Keys must be permanent and cannot be change from administrator/user.

**Comment by simgislab** [comment]
method added
