### ISSUE TITLE
Удалить кнопку ссылки на карту в основной панели

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb#504]
Так как реализована новая панель с компонентом Permalink в https://github.com/nextgis/nextgisweb/issues/492:
![image](https://cloud.githubusercontent.com/assets/669999/17657957/3cb87674-62d0-11e6-95fa-45e618ae2e22.png)
возможно кнопку для получения ссылки на карту в основной панели можно удалить?
![image](https://cloud.githubusercontent.com/assets/669999/17657982/67743ed4-62d0-11e6-8290-6ac4b330a09f.png)

**Comment by simgislab** [comment]
нужно удалить конечно
