### ISSUE TITLE
С включенным AdBlock карта не показывается вообще, падает с какой-то ошибкой в консоли

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb#505]
Перенесено из https://github.com/nextgis/nextgisweb/issues/492.

**Comment by karavanjo** [comment]
Причина ошибки в этом [списке](https://easylist-downloads.adblockplus.org/fanboy-social.txt), который AdBlock Plus [реккомендует](https://adblockplus.org/features#socialmedia) для отключения кнопок социальных сетей - если **список включен** (по умолчанию его нет) - **баг воспрозводится**.

Вариант исправления - переименовать файл скрипта и отдельные стили - это позволяет избежать ошибок и применить такой сценарий:
* **Сценарий А**. При включенном AddBlock Plus cо списком [fanboy-social](https://easylist-downloads.adblockplus.org/fanboy-social.txt):
  * Иконка пермалинка видна и работоспособна.
  * Иконки социальных сетей скрыты.
  * Ошибок нет.
*  **Сценарий Б**. При выключенном AddBlock Plus или включенном AddBlock Plus, но без списка [fanboy-social](https://easylist-downloads.adblockplus.org/fanboy-social.txt) - функционал виджета полный.


**Сценарий А** | **Сценарий Б**
------------ | -------------
![image](https://cloud.githubusercontent.com/assets/669999/17661171/39e2cbdc-62e6-11e6-8412-8e5bf6f1481d.png) | ![image](https://cloud.githubusercontent.com/assets/669999/17661185/4770ca10-62e6-11e6-98f9-c1c7a12492ee.png)

Исправление реализовано, описанные сценарии доступны для тестировании по [ссылке](http://176.9.38.120/ngw-karavanjo-demo/resource/1/display) (NextGIS Web https://github.com/karavanjo/nextgisweb/commit/b2aacfa95e62c18d9201abbaa1c113ab88804451).

@dezhin и @simgislab, просьба посмотреть и высказать мнение.

**Comment by dezhin** [comment]
Да, все так как и должно быть!
