### ISSUE TITLE
Добавить возможность отключать NgwShareButtons в конфигурационном файле

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#512]
Для инстансов, развёрнутых в локальных сетях, она бесполезна за исключением, может быть, пермалинка. Ну а если кому он нужен, то пусть не отключают.

**Comment by edpop** [comment]
Добавил опцию webmap.enable_share_panel https://github.com/nextgis/nextgisweb/commit/14e308a1b0014c5f991866f81a1182b128f823cc

**Comment by dezhin** [comment]
Тут немного не то что нужно получилось. Наверное как-то явно это надо было описать, но скрывать имеет смысл только кнопки соц. сетей, пермалинки и встраивание надо оставить.

**Comment by edpop** [comment]
Настройка ещё и до фронта не долетала. Поменял на enable_social_networks https://github.com/nextgis/nextgisweb/commit/6543caa6eeaa63409f7279d968563a292700c23e
