### ISSUE TITLE
Add tool for hiding tree layers panel

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb#517]

**Comment by simgislab** [comment]
>Не хватает мобильного варианта карты, чтобы панель можно было свернуть.

[via](https://www.facebook.com/nextgis/posts/1118638878220746?comment_id=1118671218217512&comment_tracking=%7B%22tn%22%3A%22R%22%7D)

**Comment by karavanjo** [comment]
Implemented. Deployed [here](http://176.9.38.120/ngw-karavanjo-demo/resource/1/display).
