### ISSUE TITLE
Implement addition/deletion of attachments into identification popup

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb#518]
Example:
![image](https://cloud.githubusercontent.com/assets/669999/14820849/09006c70-0bd1-11e6-9439-c7085e243e9c.png)
Details [here](https://github.com/nextgis/nextgisweb_compulink/milestone/5?closed=1)

**Comment by dezhin** [comment]
Сейчас оно все открывается без ухода с веб-карты на отдельной вкладке.
