### ISSUE TITLE
Поддержка кэшей карт для мобильного приложения

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#52]
Кэши карт формируются в настольной  QGIS (zip с набором папок и тайлов). Неплохо иметь возможность:
1. Подключения кэша в качестве слоя карты
2. Выдачу мобильному приложению перечня кэшей в виде json
3. Скачивание кэша в мобильное приложение

**Comment by BishopGIS** [comment]
Fixed here: https://github.com/nextgis/android_gisapp/issues/24

**Comment by simgislab** [comment]
непонятно, ты же это в мобильном сделал, а не в НГВ

**Comment by BishopGIS** [comment]
Да, я сделал в мобильном, поэтому в НГВ это делать больше не нужно. Были варианты либо сделать на стороне НГВ или на стороне мобильного - сделали на стороне мобильного.

**Comment by simgislab** [comment]
а разве это отменило возможную необходимость подключения таких кэшей в НГВ?

**Comment by BishopGIS** [comment]
Я думаю да. Т.к. мы нгв и так по ТМС подключаем. Кэш в zip можно размещать
в наборах файлов, но это тоже уже сделано. Нужна только поддержка на
стороне мобильного.
Я думаю в плане подключения данных с нгв имеется исчерпывающее количество
возможностей. Сейчас крайне важно решить вопрос с синхронизацией, что бы
получать не весь векторный слой или справочник, а только изменения. В этом
плане, мне вариант росавто кажется не плохим, да ещё с бонусами.
