### ISSUE TITLE
Missing translation for Create button under Groups management

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#520]
![missing-tr](https://cloud.githubusercontent.com/assets/172806/18466724/d8a3c2ca-79ad-11e6-8b24-2af7e7f65eae.png)

**Comment by simgislab** [comment]
It is not currently possible to translate strings in files that are not part of the package
https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/amd_packages/ngw/modelWidget/FormMixin.js#L33

solution is to add them to ngw-pyramid package

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/3ed1d2b2201eb3cead62733c5bf5e2e19a78ce1d
