### ISSUE TITLE
Simplify select user/group

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#522]
Add different icons for users and groups. Group groups at the beginning of the list.

On picture demo is the group and the user.
![groups_problem](https://cloud.githubusercontent.com/assets/1708122/18523581/eb757cae-7ac5-11e6-8543-abca2265a604.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/27544a26826f8bd0d35991ab33349421a8b688ee by @lisovenkoNastya

**Comment by BishopGIS** [comment]
Исправлено
<img width="713" alt="2016-10-28 13 10 16" src="https://cloud.githubusercontent.com/assets/1708122/19803179/f46933d4-9d0f-11e6-9e39-df6b73b1025f.png">
