### ISSUE TITLE
Tracking API

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#523]
Implement API to work with tracking information:
1. Post coordinates, time, accuracy, elevation, fix, source (sat, wifi, cell, etc), nextgisid/login or some other id
2. Get linestring from list of nextgisids/logins or other ids, time period.
3. Get last point for list of nextgisids/logins or other ids
4. Export to GPX/GeoJSON

**Comment by simgislab** [comment]
So single storage per instance for tracking info from all users of the instance?

**Comment by BishopGIS** [comment]
Yes. We can efficiently get tracking information using filters (list of nextgisid's and time period).

**Comment by simgislab** [comment]
track.nextgis.com
176.9.38.120

**Comment by simgislab** [comment]
implemented as tracking extension
