### ISSUE TITLE
Upload KML

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#529]

**Comment by drnextgis** [comment]
https://github.com/nextgis/nextgisweb/commit/485312b196e98d37c31816c56a26a8cab0d9ae99

**Comment by simgislab** [comment]
this can be closed when #540 is closed, otherwise this is not implemented fully as current upload imports only first type of geometries, while there can be multiple

**Comment by dezhin** [comment]
KML and selection of geometry type are supported now.
