### ISSUE TITLE
Определить интерфейс для WebmapPlugin

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#531]
Речь идёт вот об [этом](https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/webmap/plugin/base.py) классе. Как я понял из того, что сделано, есть метод `is_layer_supported`, который [возвращает](https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/webmap/plugin/feature_layer.py#L11) (MID, словарь параметров) для каждого слоя. Но плагин карты же может не относится к слоям, а быть общего назначения (например, плагин подложек)?

1. Как в этом случае назвать метод класса и что он должен возвращать, просто MID?
2. Если мы добавляем этот метод, то должен ли у плагинов, не относящихся к слоям быть метод `is_layer_supported` (возвращающий False) или лучше в коде проверять наличие метода через `hasattr`?

**Comment by dezhin** [comment]
Если я правильно помню, то это история исключительно про плагины привязанные к слоям. Наверное если нужно что-то не привязанное, то это наверное нужно отделить в какой-нибудь WebmapLayerPlugin, и не привязанное сделать отдельно. Хотя можно и это пытаться использовать добавив какие-то доп. методы, которые потом по hasattr проверять.

**Comment by drnextgis** [comment]
Спасибо, переименовал WebmapPlugin в https://github.com/nextgis/nextgisweb/commit/703d6f2810341e7679c032607e397599501b605b.
