### ISSUE TITLE
ImportError: No module named WMSCapabilitiesReader (wmsclient/model.py)

### ISSUE THREAD

**Issue by pirr** [nextgis/nextgisweb#533]
При установке сервера на Ubuntu 14.04 столкнулся с ошибкой ImportError: No module named WMSCapabilitiesReader в wmsclient/model.py. Проблема решилась указанием верного пути до модуля WMSCapabilitiesReader https://github.com/pirr/nextgisweb/commit/61c028c60467f37fb7f4aac67754f33e4e28bc57

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/d6160dc2b481e49979bf9b45d4c129b335af0678
