### ISSUE TITLE
Сломалась верстка подсказки в WMS и WFS сервисах

### ISSUE THREAD

**Issue by lisovenkoNastya** [nextgis/nextgisweb#537]
![a48e692add104b4393bc4f2a2be2bcae](https://cloud.githubusercontent.com/assets/16019740/19717736/b688164e-9b6a-11e6-8bb4-a4a00e8d5ea3.png)

**Comment by drnextgis** [comment]
А что именно сломалось?

**Comment by lisovenkoNastya** [comment]
![image](https://cloud.githubusercontent.com/assets/16019740/19718001/093a131e-9b6c-11e6-94b3-7ee6735fcd5a.png)
