### ISSUE TITLE
Walk through shapefile geometries to get rid of multi/single part error on upload

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#539]
Shapefiles are bad, but they are widespread.

Shapefile can store Multipart features, but can't declare them as a result there is no way we can predict 100% w/o parsing if contents are Polygon or Multipolygon.
GDAL driver will return Polygon even if there is Multipolygon indise.

We need to walk through all geometries on input and if there a single Multi - convert all to Multi and create Mulipolygon layer.

see 
https://github.com/nextgis/nextgisweb/issues/424
https://github.com/nextgis/nextgisweb/issues/456

This will erradicate a need for ugly ```Geometry type (Multipolygon) does not match column type (Polygon).``` error message (https://github.com/nextgis/testdata/wiki/Demo-and-test-data#bugs).

**Comment by dezhin** [comment]
Fixed in 900d3d290a10ff2f5ffca2001abf4a4e14635878. Tested on testdata dataset but need more testing.

**Comment by simgislab** [comment]
it seems to be working well
