### ISSUE TITLE
Selector for basic geometry types for multi-type formats

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#540]
KML, GeoJSON, MI TAB and other formats can store multiple geometry types in one file. I.e. points and polygons.

Currently on upload only one (first?) is considered, others are ommited (the case for KML #529).

We need selector to allow user to choose what geometries to import. Two possible options are:

1. Selector before upload with all geom types
2. (better) selector with available types of geoms after upload and file parsing (see also #539). Like in QGIS.

**Comment by dezhin** [comment]
Now it's possible to select geometry type in advanced options:

![image](https://user-images.githubusercontent.com/237320/116922527-2efa7000-ac5e-11eb-86f5-9c84d0a54701.png)
