### ISSUE TITLE
Improve error message on upload with wrong encoding

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#541]
was
>Unable to decode string value of feature #1 attribute #8

should be

en
>It seems like declared and actual attributes encodings do not match. Try declaring different encoding. (Unable to decode attribute #8 of feature #1)

ru
>Похоже, заданная кодировка отличается от фактической. Попробуйте выбрать другую кодировку (Невозможно раскодировать атрибут #8 записи #1).

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/c9c20d17b79c80f0e6c9ade60cdc3c89ed5efef4
