### ISSUE TITLE
Multiline WYSIWYG editor for attributes

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#545]
Need ability to enter html formatted text into attribute fields for cases where frontend different from Web map is used.

1. User opens feature editing dialog
2. Each text area for string fields has a little pencil icon on the right (don't forget to add a tooltip 'Rich text editor')
3. If it is clicked, WYSIWYG control pops up with contents of the textarea (or clean)
4. User can enter and format text
5. On save, html-code for this text is saved as a string in the textarea

If user edits html-code through the textarea itself and breaks it - it's his fault.

![edit](https://cloud.githubusercontent.com/assets/172806/20588970/a204af64-b232-11e6-8c8a-8c16a7b4f447.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/8d80b3dbfe03ba42b5489f364825ada84f2e48de
