### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#547]
need pretty 404 page, should mention broken embeds as well

right now it looks like this

![404](https://cloud.githubusercontent.com/assets/172806/20602630/9daddb80-b277-11e6-84dc-d3fe91a6e065.png)

**Comment by trolleway** [comment]
:-1: 

проверка голосования

**Comment by karavanjo** [comment]
The page was added:
![image](https://cloud.githubusercontent.com/assets/669999/24334073/7362dbe6-126c-11e7-937c-d570001a295b.png)
Link on the page points to contact form on NextGIS - [russian](http://nextgis.ru/contact/), [english](http://nextgis.com/contact/).

@lisovenkoNastya, How about incredible design for the page? Body of the page [here](https://github.com/nextgis/nextgisweb/blob/1ddffa09c22e1176623de458f5cba01fe5aec683/nextgisweb/pyramid/template/404.mako).

**Comment by drnextgis** [comment]
@simgislab, закрываем?

**Comment by simgislab** [comment]
нужно проверить как оно на сломаных эмбедах выглядит

**Comment by drnextgis** [comment]
@simgislab проверил?

**Comment by simgislab** [comment]
норм

![](http://m-d.me/img/ss/20190628_231419.png)
