### ISSUE TITLE
Link to main map from embed

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#548]
an icon or text somewhere

@lisovenkoNastya, can you help with where is better? @karavanjo will implement

**Comment by karavanjo** [comment]
This functionality will be configurable on EmmbeddedMapSettings or no?
For example:
![image](https://cloud.githubusercontent.com/assets/669999/23617045/bc00f46c-029c-11e7-891f-4e731787377d.png)

**Comment by simgislab** [comment]
sounds good

**Comment by karavanjo** [comment]
Implemented.
Demo available by [link](https://youtu.be/bFbiEK5peCs).

The changes were deployed on [dev.nextgis.com/ngw-dev-demo](http://dev.nextgis.com/ngw-dev-demo). Credentials for the NextGIS Web instance can get on request from @karavanjo.

**Comment by simgislab** [comment]
perfect
