### ISSUE TITLE
Untranslated strings for embeds

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#549]
Window title, button and labels

![untranslated](https://cloud.githubusercontent.com/assets/172806/20626175/64752d2c-b331-11e6-99c1-7112a6f1ebcd.png)

**Comment by drnextgis** [comment]
@simgislab помоги с переводом

**Comment by simgislab** [comment]
Embedded map settings -> Настройки встраиваемой карты
Width -> Ширина
Height -> Высота
HTML code -> Код для встраивания
Preview -> Предварительный просмотр

**Comment by drnextgis** [comment]
А не слишком ли длинная кнопка будет?

**Comment by simgislab** [comment]
мне кажется там хватает места или нет? если нет, то можно просто "Просмотр" тогда или "Протестировать" (второе больше нравится)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/df7e2d765ebada3d9a9775ab297377ab96bcdf4b
