### ISSUE TITLE
Unsupported field name @id

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#550]
Я создал через NGW Connect в nextgis.com слой из файла. 
У слоя в вебе есть поля id1, @id. В QGIS я не могу теперь получить этот слой по wfs, текст ошибки: 
```
Server generated an exception in GetFeature response: 
Field name @id contains unsupported symbol. You may attempt reloading the layer with F5
```
Слой: http://trolleway.nextgis.com/resource/820/feature/
Поле @id содержится в ответах http://overpass-turbo.eu, это популярный ресурс.

**Comment by simgislab** [comment]
а это не нарушение спецификации WFS, такой символ в названии поля? думаю что нарушение

**Comment by simgislab** [comment]
see 551
