### ISSUE TITLE
WFS edits can't be commited if WFS layer name contains '('

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#551]
example layer name: ```новый (слой)-wfs-service```
add via Connetc and attempted to edit in QGIS

>Commit errors:
			  ERROR: 1 feature(s) not added.
>			  Provider errors:
>			      WFS exception report (code= text=Can't parse the request)

**Comment by simgislab** [comment]
see #550 as well

**Comment by edpop** [comment]
Имя слоя используется в теге xml в запросах WFS, так что невозможно. При создании слоя WFS стоит валидация имени.
