### ISSUE TITLE
Block buttons on resource create 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#552]
При создании ресурса, после нажатия кнопки Создать, в основной части экрана появляется надпись - Пожалуйста подождите, идет обработка запроса...
При этом кнопки 'Создать' и 'Создать и продолжить' все еще активны и есть соблазних нажать повторно.
Имхо будет лучше, если они будут задизейблины.

**Comment by drnextgis** [comment]
Подтверждаю. В коде кнопки дизейблятся и нажатие на них ни к чему не приводит, но визуально да они выглядят как активные. Видимо при переезде с нативных dojo кнопок немного стилей потерялось, @lisovenkoNastya посмотри пожалуйста.
