### ISSUE TITLE
Folder doesn't show up as folder icon when moving a resource

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#556]
If it is empty. In the example below, selected resource is a group, like all others (except webmap)

![](http://m-d.me/img/ss/20161213-1gb-31kb.jpg)

**Comment by drnextgis** [comment]
It is expected behavior. Folder icon within resource tree means that resource has children. Any resource without children as in your example displays as leaf.

**Comment by simgislab** [comment]
because of this: https://github.com/nextgis/nextgisweb/issues/443
