### ISSUE TITLE
Using Ctrl + pgUp(pgDn) for change browser tab leads to changing inside tab in ngw page.

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgisweb#557]
in Firefox (in Chrome OK)
1. Move to creating resource page. There is few inside tabs in this page. Resource tab is selected.
2. Press Ctrl+PgUp(Dn) to change browser tab.
3. Return to creating resource page tab.

* Another inside tab (not Resource tab) is selected.

**Comment by dezhin** [comment]
I've tested the case in Firefox both on Windows and Linux; it works fine now and doesn't switch tabs inside a page. But I saw the same behavior a few years ago. So, I think it was fixed on the browser side.
