### ISSUE TITLE
Просмотр пользователей в группе

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#561]
В данный момент невозможно узнать, какие пользователи состоят в группе

**Comment by drnextgis** [comment]
В https://github.com/nextgis/nextgisweb/commit/e6c06f0caff9d4f92b83dba2743a96822359dca5 добавлена возможность просмотра списка пользователей конкретной группы.

**Comment by drnextgis** [comment]
Сделано.
