### ISSUE TITLE
Проверка значения «Имя группы»

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#562]
В данный момент поле должно быть уникальным, при этом допускает пустое значение

**Comment by drnextgis** [comment]
Добавил ограничение в интерфейсе https://github.com/nextgis/nextgisweb/commit/ec1638a15b8325e1d0611984d666f0f20184c15b. Этого достаточно?

**Comment by yellow-sky** [comment]
Работает
