### ISSUE TITLE
Сортировка групп в свойствах пользователя

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgisweb#564]
Активные группы в карточке пользователя хорошо бы перемещать в начало списка групп. В некоторых случаях можно незаметить что пользователь состоит в группах, скрытых ниже в списке.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/e84573bdc0b5c1b729d7d9d1571c0ec94dd2414b
