### ISSUE TITLE
Инструкция установки NextGIS Web в Ubuntu (замечания)

### ISSUE THREAD

**Issue by spatialhast** [nextgis/nextgisweb#567]
2.11.1. Установка в Ubuntu http://docs.nextgis.ru/docs_ngweb/source/install-ubuntu.html

1. В 'Установить дополнительные инструменты:' указан  'python-mapscript'. Далее его установка указана в 'Установка MapServer'. Стоит его удалить из 'Установить дополнительные инструменты:'

2. Дублирование git и python-dev в
'Установить дополнительные инструменты:
sudo apt-get install git python-mapscript python-dev git libgdal-dev python-dev \'

3. Если был подключен репозиторий 'ppa:ubuntugis/ubuntugis-unstable' - то устанавливается GDAL 2.x но в требованиях указан GDAL 1.x

4. Необходимо обновить примеры конфигурационных файлов - некоторые параметры сейчас обязательны для указания (например '# Директория для хранения файлов')

**Comment by simgislab** [comment]
для начала, а о какой именно инструкции речь?

**Comment by spatialhast** [comment]
http://docs.nextgis.ru/docs_ngweb/source/install-ubuntu.html

**Comment by simgislab** [comment]
спасибо!
1. поправил
2. поправил
3. убрал про ubuntugis
4. разъяснил что either sdir or (core/file_storage/path and file_upload/path) is required

**Comment by simgislab** [comment]
на всякий случай, ишью по доке НГВ можно заводить тут: https://github.com/nextgis/docs_ngweb
