### ISSUE TITLE
Ошибка создания ресурса из shp/geojson при GDAL 2.1

### ISSUE THREAD

**Issue by spatialhast** [nextgis/nextgisweb#568]
Ubuntu Server 14.04, запуск через pserve
Если  установлен GDAL 2.1 в NextGIS Web при создании ресурса из shp/geojson возникает ошибка:

> При создании ресурса из shp
> msgstr: Неизвестная ошибка 'IntegrityError'
> IntegrityError: (IntegrityError) new row for relation "layer_field" violates check constraint "layer_field_datatype_check1"
> DETAIL:  Failing row contains (1, 2, vector_layer, 0, osm_id, BIGINT, osm_id, t).
> 
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
>     reraise(*exc_info)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
>     view_name
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
>     response = view_callable(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 182, in __call__
>     return view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
>     return view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
>     return view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
>     result = view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
>     response = view(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/resource/api.py", line 318, in collection_post
>     DBSession.flush()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1828, in flush
>     self._flush(objects)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1946, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 58, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1910, in _flush
>     flush_context.execute()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 367, in execute
>     n.execute_aggregate(self, set_)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 459, in execute_aggregate
>     self.execute(uow)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
>     uow
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
>     table, insert)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 569, in _emit_insert_statements
>     execute(statement, params)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
>     params)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
>     compiled_sql, distilled_params
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
>     context)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
>     exc_info
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
>     context)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
>     cursor.execute(statement, parameters)
> 
> 
> При загрузке geojson
> Exception when serving /resource/3/geojson/
> Traceback (most recent call last):
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
>     task.service()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
>     self.execute()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
>     app_iter = self.channel.server.application(env, start_response)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 236, in __call__
>     response = self.invoke_subrequest(request, use_tweens=True)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 211, in invoke_subrequest
>     response = handle_request(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/pyramid/api.py", line 84, in cors_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
>     return handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
>     reraise(*attrs['exc_info'])
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
>     reraise(*exc_info)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
>     view_name
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
>     response = view_callable(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
>     return view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
>     return view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
>     result = view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
>     response = view(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/feature_layer/api.py", line 62, in view_geojson
>     content_disposition=content_disposition)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/webob/response.py", line 310, in __init__
>     "You cannot set the body to a text value without a "
> TypeError: You cannot set the body to a text value without a charset
> Exception when serving /resource/3/geojson/
> Traceback (most recent call last):
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
>     task.service()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
>     self.execute()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
>     app_iter = self.channel.server.application(env, start_response)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 236, in __call__
>     response = self.invoke_subrequest(request, use_tweens=True)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 211, in invoke_subrequest
>     response = handle_request(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/pyramid/api.py", line 84, in cors_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
>     return handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
>     reraise(*attrs['exc_info'])
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
>     reraise(*exc_info)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
>     view_name
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
>     response = view_callable(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
>     return view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
>     return view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
>     result = view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
>     response = view(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/feature_layer/api.py", line 62, in view_geojson
>     content_disposition=content_disposition)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/webob/response.py", line 310, in __init__
>     "You cannot set the body to a text value without a "
> TypeError: You cannot set the body to a text value without a charset

Версии пакетов:

> Пакет	Версия
> appdirs	1.4.0	 
> babel	2.3.4	 
> bunch	1.0.1	 
> flufl.enum	4.1.1	 
> geoalchemy2	0.4.0	 
> geojson	1.3.3	 
> lxml	3.7.2	 
> mako	1.0.6	 
> mapscript	7.0.4	 
> markupsafe	0.23	 
> nextgisweb	3.0	d8a95163
> nextgisweb_mapserver	0.0.dev0	b765f2de
> numpy	1.12.0	 
> olefile	0.44	 
> owslib	0.14.0	 
> packaging	16.8	 
> passlib	1.7.1	 
> pastedeploy	1.5.2	 
> pillow	4.0.0	 
> ply	3.10	 
> psycopg2	2.6.2	 
> pygdal	2.1.0.3	 
> pygments	2.2.0	 
> pyparsing	2.1.10	 
> pyproj	1.9.5.1	 
> pyramid	1.7.4	 
> pyramid-debugtoolbar	3.0.5	 
> pyramid-mako	1.0.2	 
> pyramid-tm	1.1.1	 
> python-dateutil	2.6.0	 
> pytz	2016.10	 
> repoze.lru	0.6	 
> requests	2.13.0	 
> shapely	1.5.17.post1	 
> six	1.10.0	 
> sqlalchemy	0.8.7	 
> transaction	2.0.3	 
> translationstring	1.3	 
> unicodecsv	0.14.1	 
> venusian	1.0	 
> waitress	1.0.2	 
> webob	1.7.1	 
> zope.deprecation	4.2.0	 
> zope.interface	4.3.3	 
> zope.sqlalchemy	0.7.7

**Comment by drnextgis** [comment]
GDAL 2.x пока не поддерживается, можно попробовать вот этот коммит https://github.com/nextgis/nextgisweb/commit/442ebfefd6706fc37338b1609e7589a0f04fd5c4 и поправить в БД CONSTRAINT:

```
ALTER TABLE public.layer_field DROP CONSTRAINT layer_field_datatype_check;
ALTER TABLE public.layer_field DROP CONSTRAINT layer_field_datatype_check1;
ALTER TABLE public.layer_field
  ADD CONSTRAINT layer_field_datatype_check CHECK (datatype::text = ANY (ARRAY['INTEGER'::character varying, 'BIGINT'::character varying, 'REAL'::character varying, 'STRING'::character varying, 'DATE'::character varying, 'TIME'::character varying, 'DATETIME'::character varying]::text[]));
```

**Comment by drnextgis** [comment]
@spatialhast, получилось?

**Comment by spatialhast** [comment]
@drnextgis обновил, ошибок нет

**Comment by drnextgis** [comment]
Теперь поддержка GDAL 2.x доступна и в основной ветке.
