### ISSUE TITLE
Ошибка при отображении растрового слоя на карте при GDAL 1.x

### ISSUE THREAD

**Issue by spatialhast** [nextgis/nextgisweb#569]
Ubuntu Server 14.04, запуск через pserve, установлен GDAL 1.x (репозиторий ppa:ubuntugis/ubuntugis-unstable не добавлялся при установке NGW)

Опубликован растр и сделана карта (адаптер - тайлы, охват по слою, слой включен по умолчанию). При открытии карты с растром возникает ошибка. Тайлы растрового слоя на карте отображаются.

> Exception when serving /api/component/render/tile
> Traceback (most recent call last):
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
>     task.service()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
>     self.execute()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
>     app_iter = self.channel.server.application(env, start_response)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 236, in __call__
>     response = self.invoke_subrequest(request, use_tweens=True)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 211, in invoke_subrequest
>     response = handle_request(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/pyramid/api.py", line 84, in cors_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
>     return handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
>     reraise(*attrs['exc_info'])
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
>     reraise(*exc_info)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
>     view_name
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
>     response = view_callable(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
>     result = view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
>     response = view(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/render/api.py", line 34, in tile
>     rimg = req.render_tile((z, x, y), 256)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/raster_style/models.py", line 33, in render_tile
>     return self.style.render_image(extent, (size, size))
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/raster_style/models.py", line 107, in render_image
>     numpy.uint8)
> TypeError: 'float' object cannot be interpreted as an index
> 

Ошибка также если выбран в карте для растра адаптер - изображение
После открытия карты растровый слой через некоторое время отображается

> Exception when serving /api/component/render/image
> Traceback (most recent call last):
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
>     task.service()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
>     self.execute()
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
>     app_iter = self.channel.server.application(env, start_response)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 236, in __call__
>     response = self.invoke_subrequest(request, use_tweens=True)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 211, in invoke_subrequest
>     response = handle_request(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/pyramid/api.py", line 84, in cors_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
>     return handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
>     reraise(*attrs['exc_info'])
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
>     reraise(*exc_info)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
>     response = handler(request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
>     view_name
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
>     response = view_callable(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
>     result = view(context, request)
>   File "/home/ngweb/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
>     response = view(request)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/render/api.py", line 74, in image
>     rimg = req.render_extent(p_extent, p_size)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/raster_style/models.py", line 29, in render_extent
>     return self.style.render_image(extent, size)
>   File "/home/ngweb/ngw/nextgisweb/nextgisweb/raster_style/models.py", line 107, in render_image
>     numpy.uint8)
> TypeError: 'float' object cannot be interpreted as an index
> 

Информация gdalinfo о растре

> Driver: GTiff/GeoTIFF
> Files: LC81770252015260LGN00_B432_c.tif
> Size is 8021, 8131
> Coordinate System is:
> PROJCS["WGS 84 / UTM zone 37N",
>     GEOGCS["WGS 84",
>         DATUM["WGS_1984",
>             SPHEROID["WGS 84",6378137,298.257223563,
>                 AUTHORITY["EPSG","7030"]],
>             AUTHORITY["EPSG","6326"]],
>         PRIMEM["Greenwich",0,
>             AUTHORITY["EPSG","8901"]],
>         UNIT["degree",0.0174532925199433,
>             AUTHORITY["EPSG","9122"]],
>         AUTHORITY["EPSG","4326"]],
>     PROJECTION["Transverse_Mercator"],
>     PARAMETER["latitude_of_origin",0],
>     PARAMETER["central_meridian",39],
>     PARAMETER["scale_factor",0.9996],
>     PARAMETER["false_easting",500000],
>     PARAMETER["false_northing",0],
>     UNIT["metre",1,
>         AUTHORITY["EPSG","9001"]],
>     AXIS["Easting",EAST],
>     AXIS["Northing",NORTH],
>     AUTHORITY["EPSG","32637"]]
> Origin = (232485.000000000000000,5693415.000000000000000)
> Pixel Size = (30.000000000000000,-30.000000000000000)
> Metadata:
>   AREA_OR_POINT=Area
> Image Structure Metadata:
>   INTERLEAVE=PIXEL
> Corner Coordinates:
> Upper Left  (  232485.000, 5693415.000) ( 35d 9'35.09"E, 51d19'44.36"N)
> Lower Left  (  232485.000, 5449485.000) ( 35d19'54.88"E, 49d 8'23.53"N)
> Upper Right (  473115.000, 5693415.000) ( 38d36'48.95"E, 51d23'28.80"N)
> Lower Right (  473115.000, 5449485.000) ( 38d37'51.48"E, 49d11'51.26"N)
> Center      (  352800.000, 5571450.000) ( 36d56' 2.73"E, 50d16'36.52"N)
> Band 1 Block=8021x1 Type=Byte, ColorInterp=Red
>   Mask Flags: PER_DATASET ALPHA
> Band 2 Block=8021x1 Type=Byte, ColorInterp=Green
>   Mask Flags: PER_DATASET ALPHA
> Band 3 Block=8021x1 Type=Byte, ColorInterp=Blue
>   Mask Flags: PER_DATASET ALPHA
> Band 4 Block=8021x1 Type=Byte, ColorInterp=Alpha

Версии пакетов:
> Пакет	Версия
> appdirs	1.4.0	 
> babel	2.3.4	 
> bunch	1.0.1	 
> flufl.enum	4.1.1	 
> geoalchemy2	0.4.0	 
> geojson	1.3.3	 
> lxml	3.7.2	 
> mako	1.0.6	 
> mapscript	6.4.1	 
> markupsafe	0.23	 
> nextgisweb	3.0	d8a95163
> nextgisweb_mapserver	0.0.dev0	b765f2de
> numpy	1.12.0	 
> olefile	0.44	 
> owslib	0.14.0	 
> packaging	16.8	 
> passlib	1.7.1	 
> pastedeploy	1.5.2	 
> pillow	4.0.0	 
> ply	3.10	 
> psycopg2	2.6.2	 
> pygdal	1.10.1.3	 
> pygments	2.2.0	 
> pyparsing	2.1.10	 
> pyproj	1.9.5.1	 
> pyramid	1.7.4	 
> pyramid-debugtoolbar	3.0.5	 
> pyramid-mako	1.0.2	 
> pyramid-tm	1.1.1	 
> python-dateutil	2.6.0	 
> pytz	2016.10	 
> repoze.lru	0.6	 
> requests	2.13.0	 
> shapely	1.5.17.post1	 
> six	1.10.0	 
> sqlalchemy	0.8.7	 
> transaction	2.0.3	 
> translationstring	1.3	 
> unicodecsv	0.14.1	 
> venusian	1.0	 
> waitress	1.0.2	 
> webob	1.7.1	 
> zope.deprecation	4.2.0	 
> zope.interface	4.3.3	 
> zope.sqlalchemy	0.7.7

**Comment by drnextgis** [comment]
@spatialhast а можно ссылку на растр?

**Comment by spatialhast** [comment]
@drnextgis ссылк на используемые растры http://fex.net/798208098183
При создании растрового слоя из растра LC81770252015260LGN00_B432.tif возникает ошибка (alert) "Канал #1 имеет тип 'Unit16', однако поддерживаются только следующие типы каналов: Byte". Выше ошибка возникает для растра LC81770252015260LGN00_B432_c.tif (данный растр был получен путем пересохранения как Rendered image в QGIS)

**Comment by spatialhast** [comment]
после обновления nextgisweb, Pyramid до 1.8.1 данная ошибка есть

**Comment by drnextgis** [comment]
@spatialhast, должно быть исправлено в https://github.com/nextgis/nextgisweb/commit/043a6d3e44eb8ab289af8be58b3e00aa7ca3bde1, проверьте, пожалуйста. Если всё хорошо, то можно закрывать.

**Comment by spatialhast** [comment]
после обновления ошибки нет. спасибо!
