### ISSUE TITLE
Ошибка при добавлении WMS сервиса (NextGIS Web) в NextGIS QGIS

### ISSUE THREAD

**Issue by spatialhast** [nextgis/nextgisweb#572]
В NGW сервис wms для растра успешно создан. При добавлении созданного wms в QGIS возникает оибка. (но сам слой на карте через несколько секунд отображается)

> Exception when serving /api/resource/28/wms
> Traceback (most recent call last):
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
>     task.service()
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
>     self.execute()
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
>     app_iter = self.channel.server.application(env, start_response)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 233, in __call__
>     response = self.invoke_subrequest(request, use_tweens=True)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 208, in invoke_subrequest
>     response = handle_request(request)
>   File "/home/opengeo/ngw/nextgisweb/nextgisweb/pyramid/api.py", line 84, in cors_tween
>     response = handler(request)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 187, in toolbar_tween
>     return handler(request)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
>     reraise(*attrs['exc_info'])
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
>     response = handler(request)
>   File "/home/opengeo/ngw/nextgisweb/nextgisweb/resource/api.py", line 204, in resource_exception_tween
>     response = handler(request)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
>     reraise(*exc_info)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 98, in tm_tween
>     response = handler(request)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
>     view_name
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
>     response = view_callable(context, request)
>   File "/home/opengeo/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 409, in viewresult_to_response
>     result = view(context, request)
>   File "/home/opengeo/ngw/nextgisweb/nextgisweb/wmsserver/view.py", line 52, in handler
>     return _get_legend_graphic(obj, request)
>   File "/home/opengeo/ngw/nextgisweb/nextgisweb/wmsserver/view.py", line 238, in _get_legend_graphic
>     img = layer.resource.render_legend()
> AttributeError: 'RasterStyle' object has no attribute 'render_legend'

При этом в NGW сервис WFS успешно создан и добавляется в NGQ

Ubuntu Server 14.04, запуск через pserve, установлен GDAL 1.x (репозиторий ppa:ubuntugis/ubuntugis-unstable не добавлялся при установке NGW)

Версия пакетов
> Пакет	Версия
> appdirs	1.4.0
> babel	2.3.4
> bunch	1.0.1
> flufl.enum	4.1.1
> geoalchemy2	0.4.0
> geojson	1.3.3
> hupper	0.4.2
> lxml	3.7.2
> mako	1.0.6
> mapscript	6.4.1
> markupsafe	0.23
> nextgisweb	3.0	2a158c9
> nextgisweb_mapserver	0.0.dev0	b765f2de
> numpy	1.12.0
> olefile	0.44
> owslib	0.14.0
> packaging	16.8
> passlib	1.7.1
> pastedeploy	1.5.2
> pillow	4.0.0
> ply	3.10
> psycopg2	2.6.2
> pygdal	1.10.1.3
> pygments	2.2.0
> pyparsing	2.1.10
> pyproj	1.9.5.1
> pyramid	1.8.1
> pyramid-debugtoolbar	3.0.5
> pyramid-mako	1.0.2
> pyramid-tm	1.1.1
> python-dateutil	2.6.0
> pytz	2016.10
> repoze.lru	0.6
> requests	2.13.0
> shapely	1.5.17.post1
> six	1.10.0
> sqlalchemy	0.8.7
> transaction	2.0.3
> translationstring	1.3
> unicodecsv	0.14.1
> venusian	1.0
> waitress	1.0.2
> webob	1.7.1
> zope.deprecation	4.2.0
> zope.interface	4.3.3
> zope.sqlalchemy	0.7.7

Используемый растр https://github.com/nextgis/nextgisweb/issues/569#issuecomment-278583517

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/00939be55615bacf37ca543d28bc9132ad1d84a9
