### ISSUE TITLE
initialize_db error

### ISSUE THREAD

**Issue by soulnix** [nextgis/nextgisweb#573]
```
[root@mapserver_ ngw]# env/bin/nextgisweb --config config.ini initialize_db --drop
Traceback (most recent call last):
  File "env/bin/nextgisweb", line 9, in <module>
    load_entry_point('nextgisweb==3.0', 'console_scripts', 'nextgisweb')()
  File "/root/ngw/nextgisweb/nextgisweb/script.py", line 49, in main
    env.initialize()
  File "/root/ngw/nextgisweb/nextgisweb/env.py", line 70, in initialize
    c.initialize()
  File "/root/ngw/nextgisweb/nextgisweb/core/__init__.py", line 49, in initialize
    self.engine = create_engine(sa_url)
  File "/root/ngw/env/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 341, in create_engine
    return strategy.create(*args, **kwargs)
  File "/root/ngw/env/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 48, in create
    u = url.make_url(name_or_url)
  File "/root/ngw/env/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 164, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/root/ngw/env/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 209, in _parse_rfc1738_args
    return URL(name, **components)
  File "/root/ngw/env/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 59, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ''

```
MapServer
1 GB Memory / 30 GB Disk / AMS3 - CentOS 7.3.1611 x64

Подскажите пожалуйста, в чем может быть причина?

**Comment by drnextgis** [comment]
Какое значение `database.host` у вас в настройках?

**Comment by soulnix** [comment]
localhost

**Comment by drnextgis** [comment]
Что-то не так с параметрами подключения, пароль указан, настройки не закомментированы? У вас ошибка в том, что он пытается пустую строку конвертировать в число (порт).

**Comment by soulnix** [comment]
Эта часть конфига выглядит вот так
[core]

# Название системы 
system.name = NextGIS Web
# Полное название системы 
system.full_name = Геоинформационная система NextGIS
# Имя сервера БД 
database.host = localhost
# Имя БД на сервере 
database.name = db_ngw
# Имя пользователя БД 
database.user = ngw_admin
# Пароль пользователя БД 
database.password = some_pass
# Проверять подключение при запуске 
# database.check_at_startup = 
# Не загружать перечисленные пакеты 
# packages.ignore = 
# Не загружать перечисленные компоненты 
# components.ignore = 
# Локаль, используемая по-умолчанию 
# locale.default = 
# Доступные локали 
# locale.available = 
# Дополнительный инструментарий для отладки 
# debug = 
# Директория для хранения данных 
sdir = /root/ngw/data
# Отключение проверки прав при рендеринге слоев 
# permissions.disable_check.rendering = 
# Отключение проверки прав при получении информации об объектах 
# permissions.disable_check.identify = 
я понимаю пустая строка в порт конвертируется,
но где там порт указать , трейс ведет в sqlalchemy

**Comment by drnextgis** [comment]
Вот так:

```
database.host = localhost:5432
```

**Comment by soulnix** [comment]
идентичная ошибка

**Comment by drnextgis** [comment]
Поставьте бряк вот тут https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/core/__init__.py#L49 и посмотрите чему равно значение `sa_url`.

**Comment by soulnix** [comment]
(Pdb) sa_url
u'postgresql+psycopg2://ngw_admin:/neverm0re696@localhost:5432/db_ngw'

**Comment by drnextgis** [comment]
Обновитесь, проблема должна решиться.

**Comment by soulnix** [comment]
к сожалению не помогло, `__init__.py`  обновился

**Comment by drnextgis** [comment]
Может у вас пакет не в development mode установлен, тогда переустановите его.

**Comment by soulnix** [comment]
Ставил с ключем `-e`
поставился коректно

**Comment by drnextgis** [comment]
Тогда проверьте ещё раз `sa_url` - слэш в вашем пароле по идее теперь должен экранироваться.

**Comment by soulnix** [comment]
не работает
```
(Pdb) sa_url
u'postgresql+psycopg2://ngw_admin:/neverm0re696@127.0.0.1:5432/db_ngw'
```

**Comment by drnextgis** [comment]
Значит не обновились, должно быть так:

```
(Pdb) sa_url
u'postgresql+psycopg2://ngw_admin:%2Fneverm0re696@localhost/db_ngw'
```

**Comment by soulnix** [comment]
да. и правда, файл не обновляется из за изменений в нем

**Comment by soulnix** [comment]
Спасибо , все работает
