### ISSUE TITLE
Ошибка загрузки ресурсов разного типа но с одинаковым именем

### ISSUE THREAD

**Issue by spatialhast** [nextgis/nextgisweb#574]
При создании нового векторного слоя с таким же именем как у созданного растрового слоя возникает сообщение "Наименование ресурса не уникально. Ресурс с таким именем уже существует.". Это ошибка или названия ресурсов должны быть уникальными?

**Comment by drnextgis** [comment]
Название ресурсов, имеющих общего родителя, должны быть уникальными.

**Comment by drnextgis** [comment]
@spatialhast, закрываем?
