### ISSUE TITLE
Layer creation seemingly doing nothing on Create

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#576]
1. Create vector layer, data: https://docs.google.com/uc?id=0B869Q9_IuBiTMUJ1bnMySWFBS3c&export=download
2. Click create - after button unfreezes nothing shows up.
3. Wait for couple of minutes - layer shows up.

**Comment by simgislab** [comment]
bigdata problem, probably a duplicate

**Comment by dezhin** [comment]
It's about timeouts I think. It was fixed a few months ago. Now you'll see a timeout error message and the layer won't be created.
