### ISSUE TITLE
Layer with invalid geom fails to upload, Internal server error

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#577]
data: https://www.dropbox.com/s/95mof8m3aud6486/contour_lines.zip?dl=0

**Comment by drnextgis** [comment]
Zip archive should contains files not directory.

**Comment by simgislab** [comment]
Unfortunately we 'fixed' a different bug.

The same data without folder: https://www.dropbox.com/s/95mof8m3aud6486/contour_lines.zip?dl=0 Can't load with Internal server error

**Comment by drnextgis** [comment]
There is object with invalid geometry in this layer. See https://github.com/nextgis/pywps.contour_lines_generator/issues/2

**Comment by simgislab** [comment]
need to deal with this issue 100%, but not in this milestone

**Comment by drnextgis** [comment]
http://gdal.org/python/osgeo.ogr.Geometry-class.html#IsValid
http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Point.html
http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/LineString.html
http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Polygon.html

**Comment by edpop** [comment]
Dup #414
