### ISSUE TITLE
Embedded map without selected base layer

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisweb#579]
1. Select empty base layer on a map
2. Create embedding map by sharing tool

- `Expected`: Map with empty base layer
- `Actual`: Map with OSM base layer

**Comment by karavanjo** [comment]
Fixed.
Demo available by [link](https://youtu.be/nu_Mlo7oc0o).

The changes were deployed on [dev.nextgis.com/ngw-dev-demo](http://dev.nextgis.com/ngw-dev-demo). Credentials for the NextGIS Web instance can get on request from @karavanjo.

**Comment by simgislab** [comment]
great, thanks!
