### ISSUE TITLE
При получении большого числа объектов не хватает памяти?

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#581]
Если я правильно понимаю, то вот [тут](https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/feature_layer/api.py#L242) все объекты загоняются в память, что вызывает проблемы, если их слишком много. @dezhin, может есть какой-то другой способ выдавать результат, может [FileIter](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/response.html#pyramid.response.FileIter) как-то пригодится? При этом как GeoJSON загружается без проблем, так же как и CSV.

**Comment by drnextgis** [comment]
Сериализация экстеншенов очень сильно замедляет общую сериализацию фич, а выполнения `json.dumps` потом я так и не дождался.

**Comment by dezhin** [comment]
Способ всегда есть, но мне кажется нужно определится что нужно в итоге, в зависимости от этого выбрать способ. Нужен способ получить произвольно большой слой разом?

**Comment by drnextgis** [comment]
@simgislab, что думаешь? Может быть стоит сделать возможность указывать диапазон запрашиваемых объектов, например, через HTTP-заголовки: `Range: items=0-19`.

**Comment by simgislab** [comment]
мне кажется задачу минимум нужно сформулировать следующим образом: "не падать", выдавать внятные сообщения о невозможности загрузить слой и причинах.

ну и конечно придумать какие-то способы обмена более оптимизированные для общения с мобильным и другими клиентами, через бинарный протокол, блоки и т.п.

короче нужно обсудить это комплексно

**Comment by dezhin** [comment]
Сейчас есть возможность ограничивать количество выдаваемых фич через limit / offset. Есть возможность отказаться от сериализации экстеншнов (как правило они не нужны) + с тайм аутами более менее разобрались (но есть общая проблема, про то, что клиент никак не может узнать, что проблема именно в таймауте, в не в сети). FileIter тут интегрировать сложно, так как к моменту итерации конекшн к БД будет уже закрыт как я понимаю.

**Comment by shpawel** [comment]
Добрый день. В случае использования Postgresql 11 с Posgis 2.5(если я не ошибаюсь) можно сериализовать GeoJSON средствами базы данных. Это намного быстрее чем json.dumps
