### ISSUE TITLE
Если в shp много объектов, то он не загружается

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb#582]
Похоже, что в [этом](https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/vector_layer/model.py#L347) месте заканчивается память. У нас сейчас нет никакой завязки на версию SA, поэтому может имеет смысл посмотреть в сторону [Bulk Operations](http://docs.sqlalchemy.org/en/latest/orm/persistence_techniques.html#bulk-operations)?

**Comment by cfdbwrbq** [comment]
загружаю 5млн точек (shp/geojson) 
--timeout 600 в gunicorn/nginx  
[14G оперативной и 4G виртуальной]
Результат - отваливается в вэбе и qgis: 504 (Gateway Time-out).
не знаком в алхимией совсем, но если что-то можно сделать, то было бы круто.

**Comment by drnextgis** [comment]
Проверенный вариант - загружать с помощью HTTP API.

**Comment by cfdbwrbq** [comment]
gisolog@mapserver:~/ngw$ curl --user "user:mapserver" -H "Accept: */*" -X POST -d '{"resource":
 {"cls": "vector_layer","description": "test curl points create", "display_name": "sample points",
 "keyname": null,"parent": {"id": 0}},"vector_layer": {"source": {"encoding": "utf-8",
 "id": "377c2811-73be-40b3-a693-9ffaa6c0ecba","mime_type": "application/zip","name": "points.zip",
 "size": 99147130},"srs": {"id": 3857}}}' http://mapserver/api/resource/
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

**Comment by drnextgis** [comment]
Да, PATCH, наверное правильнее всего будет использовать. Вот простой пример с добавлением объектов по одному с использованием POST. Думаю, переделать на PATCH будет не сложно.

https://gist.github.com/drnextgis/3e3fcd4fb4a588b541afefcadb4ce104

**Comment by cfdbwrbq** [comment]
Понятно. Буду разбираться.
Интересно, 40млн точек по одной сколько литься по времени будут?...

**Comment by drnextgis** [comment]
Если загружать в несколько потоков, то намного быстрее, чем в один.

**Comment by cfdbwrbq** [comment]
шутки ради (я не спец в этих делах), а если asincio'шных <strike>100500</strike> много тасков в одном потоке... 
или это не смешно?

**Comment by simgislab** [comment]
перешло в дискуссию
