### ISSUE TITLE
Basemaps do not show up on the embedded map

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#584]
Might also be related to the fact that they are not stored by permalinking

**Comment by karavanjo** [comment]
Fixed.

1. For clear NGW (without `nextgisweb_basemap`) - demo is available [here](https://www.youtube.com/watch?v=8qfDPqzQkuw).
2. For NGW with `nextgisweb_basemap` functionality - demo is available [here](https://www.youtube.com/watch?v=it48iqZyTB8&feature=youtu.be).

The changes were deployed on [dev.nextgis.com/ngw-dev-demo](http://dev.nextgis.com/ngw-dev-demo/resource/1/display). Credentials for the NextGIS Web instance can get on request from @karavanjo.
