### ISSUE TITLE
numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by madw0lf** [nextgis/nextgisweb#587]
`gis@gis:~/ngw$ env/bin/nextgisweb-config > config.ini
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "env/bin/nextgisweb-config", line 11, in <module>
    load_entry_point('nextgisweb', 'console_scripts', 'nextgisweb-config')()
  File "/home/gis/ngw/nextgisweb/nextgisweb/script.py", line 85, in config
    load_all()
  File "/home/gis/ngw/nextgisweb/nextgisweb/component.py", line 99, in load_all
    __import__(pkginfo.comp_mod(comp))
  File "/home/gis/ngw/nextgisweb/nextgisweb/raster_style/__init__.py", line 4, in <module>
    from .models import Base, RasterStyle
  File "/home/gis/ngw/nextgisweb/nextgisweb/raster_style/models.py", line 4, in <module>
    from osgeo import gdal_array
  File "/home/gis/ngw/env/local/lib/python2.7/site-packages/osgeo/gdal_array.py", line 28, in <module>
    _gdal_array = swig_import_helper()
  File "/home/gis/ngw/env/local/lib/python2.7/site-packages/osgeo/gdal_array.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal_array', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import
`

ubuntu 17.04, установка производилась на чистую систему. До этого аналогичная ошибка была в 16.04, 16.10 и centos 7.
Решил сделать себе образ, где только ОСь, NGW и QGIS (для ngw_qgis) - как гарантированно рабочий бекап чистой системы, в результате ругается на numpy. прошелся по разным версиям убунты и попробовал на центоси - результат абсолютно одинаковый. делал всё по мануалу. до создания конфига ни единой ошибки.

**Comment by simgislab** [comment]
а можно нормальный стектрейс? глаза же люди сломают и не ответят ничего

**Comment by madw0lf** [comment]
> $ env/bin/nextgisweb-config > config.ini

вывод:

> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa 
Traceback (most recent call last): File "env/bin/nextgisweb-config", line 11, in <module> load_entry_point('nextgisweb', 'console_scripts', 'nextgisweb-config')() 
File "/home/gis/ngw/nextgisweb/nextgisweb/script.py", line 85, in config load_all() 
File "/home/gis/ngw/nextgisweb/nextgisweb/component.py", line 99, in load_all __import__(pkginfo.comp_mod(comp)) 
File "/home/gis/ngw/nextgisweb/nextgisweb/raster_style/__init__.py", line 4, in <module> from .models import Base, RasterStyle 
File "/home/gis/ngw/nextgisweb/nextgisweb/raster_style/models.py", line 4, in <module> from osgeo import gdal_array 
File "/home/gis/ngw/env/local/lib/python2.7/site-packages/osgeo/gdal_array.py", line 28, in <module> _gdal_array = swig_import_helper() 
File "/home/gis/ngw/env/local/lib/python2.7/site-packages/osgeo/gdal_array.py", line 24, in swig_import_helper _mod = imp.load_module('_gdal_array', fp, pathname, description) 
ImportError: numpy.core.multiarray failed to import


все предыдущие шаги точь в точь по мануалу http://docs.nextgis.ru/docs_ngweb/source/install-ubuntu.html

**Comment by drnextgis** [comment]
Покажите вывод:

```
$ ./env/bin/pip freeze
```

**Comment by madw0lf** [comment]
> $ env/bin/pip freeze

вывод:

> appdirs==1.4.3
Babel==2.4.0
bunch==1.0.1
certifi==2017.4.17
chardet==3.0.3
flufl.enum==4.1.1
GeoAlchemy2==0.4.0
geojson==1.3.5
hupper==1.0
idna==2.5
lxml==3.7.3
Mako==1.0.6
mapscript==7.0.4
MarkupSafe==1.0
-e git+https://github.com/nextgis/nextgisweb.git@02c3323a243ec08f642bb7d18b742feee3f478fb#egg=nextgisweb
-e git+https://github.com/nextgis/nextgisweb_mapserver.git@4fb34863b0d7a431730c9adf982ee9be3ebf4b64#egg=nextgisweb_mapserver
numpy==1.12.1
olefile==0.44
OWSLib==0.14.0
packaging==16.8
passlib==1.7.1
PasteDeploy==1.5.2
Pillow==4.1.1
ply==3.10
psycopg2==2.7.1
pygdal==2.1.2.3
Pygments==2.2.0
pyparsing==2.2.0
pyproj==1.9.5.1
pyramid==1.8.3
pyramid-debugtoolbar==4.0.1
pyramid-mako==1.0.2
pyramid-tm==2.0
python-dateutil==2.6.0
pytz==2017.2
repoze.lru==0.6
requests==2.16.5
Shapely==1.5.17.post1
six==1.10.0
SQLAlchemy==1.1.10
transaction==2.1.2
translationstring==1.3
unicodecsv==0.14.1
urllib3==1.21.1
venusian==1.1.0
waitress==1.0.2
WebOb==1.7.2
zope.deprecation==4.2.0
zope.interface==4.4.1
zope.sqlalchemy==0.7.7

**Comment by drnextgis** [comment]
Ни разу не сталкивался с такой проблемой, гугл советует попробовать обновить numpy:

```
env/bin/pip install numpy --upgrade
```

**Comment by simgislab** [comment]
Денис, может нам в документацию прописать минимальную версию нумпи тогда тоже?
Я тоже сталкивался с такой проблемой.

**Comment by madw0lf** [comment]
> $ env/bin/pip install numpy --upgrade

ответ:

> Requirement already up-to-date: numpy in ./env/lib/python2.7/site-packages

мне кажется, что тут не обновить нумпи надо, а наоборот сделать даунгрейд версии. но до какой версии...

**Comment by drnextgis** [comment]
numpy ставится как зависимость pygdal, можете попробовать дропнуть обоих и переустановить pygdal.

**Comment by madw0lf** [comment]
я вот смотрю на первую строку вывода при создании конфига:

RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

если я правильно понимаю, то версия нумпи выше, чем необходимо для правильной работы модуля, в котором вышла ошибка. но понизить версию нумпи не получилось без понижения версии pygdal. а при понижении версии pygdal повторяется вот эта ошибка https://github.com/nextgis/nextgisweb/issues/558
я потому и решил сделать "чистый" образ с настроенной NextGIS Web, чтоб в случае какого своего косяка можно было откатиться.

**Comment by drnextgis** [comment]
Вы никак не понизите версию pygdal, она жестко завязана на версию GDAL, установленную в системе.

**Comment by madw0lf** [comment]
Для этого, в случае с убунту, в синаптике можно выбрать устанавливаемую версию GDAL (по умолчанию идет автовыбор максимальной версии, но в ручную возможен даунгрейд).

**Comment by simgislab** [comment]
на nextgis.com numpy 1.11.0

**Comment by drnextgis** [comment]
Я так и не понял, что будет, если удалить pygdal и numpy и заново поставить pygdal?

**Comment by madw0lf** [comment]
Будет та же картина. В 17.04 только одна версия gdal ставится - 2.13.2

**Comment by drnextgis** [comment]
Понятно, всё что вам нужно - это версия pygdal 2.1.3, которой сейчас нет в PyPi. Добавим.

**Comment by madw0lf** [comment]
Спасибо)

хех.. всё что мне нужно, это грамотное ТЗ по работе (уже год работаю вообще без ТЗ и хоть какого-то понимания со стороны работодателя зачем им ГИС понадобилась) и адекватная зарплата.  Но это уже явно не к вам)

**Comment by drnextgis** [comment]
Можно проверять.

**Comment by madw0lf** [comment]
Завтра утром проверю и напишу что получилось.

**Comment by madw0lf** [comment]
Та же картина. Ну тут и мой косяк - не ту версию gdal указал. в 17.04 gdal==2.1.2+dfsg-3, numpy==1.12.1. Сейчас перезагружусь в 16.04, посмотрю там.

**Comment by drnextgis** [comment]
То есть вы удалили pygdal и numpy, переустановили pygdal и проблема осталась?

**Comment by madw0lf** [comment]
Да. 
numpy==1.12.1
pygdal==2.1.2.3

**Comment by drnextgis** [comment]
У меня такие же версии и всё ok:

```
(env) rykov@work:~$ pip freeze | grep 'numpy\|pygdal'
numpy==1.12.1
pygdal==2.1.2.3
(env) rykov@work:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal, gdal_array
>>> gdal.__file__
'/home/rykov/git/ngw2/env/local/lib/python2.7/site-packages/osgeo/gdal.pyc'
>>> import numpy
>>> numpy.__file__
'/home/rykov/git/ngw2/env/local/lib/python2.7/site-packages/numpy/__init__.pyc'
```

**Comment by madw0lf** [comment]
ну, как бы, вот..
W: Репозиторий «http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu zesty Release» не содержит файла Release.
Вернусь к этой теме уже на следующей неделе.

**Comment by madw0lf** [comment]
не знаю.. накатил чистую 16.04, та же картина. наверно я что-то делаю не так, но всё 1:1 по мануалу. установка проходит, ошибок при установке никаких, единственное что - не создается config.ini. попробую подсунуть конфиг от работающей версии, посмотрю что будет.

**Comment by drnextgis** [comment]
Может можно на это как-то посмотреть, teamviewer там или ssh?

**Comment by madw0lf** [comment]
Такой возможности нет. Сделаю иначе: на ноутбуке в виртуалке повторю всё тоже самое, виртуальный диск упакую в tar.gz и сброшу на яндекс диск, потом сюда ссылку выложу. Если проблема сохранится, то будет возможность ее поковырять в оффлайне. А если проблема в процессе пропадет, то будет просто готовый образ для виртуалки. Планируемый состав:
Ubuntu 16.04
Postgresql-9.5
Postgis-2.2
QGIS
NextGIS Web
nextgisweb_qgis

Ну и плюс стектрейс, в случае повтора ошибки.

**Comment by madw0lf** [comment]
подзабросил я эту проблему, а сейчас решил вспомнить, чтоб скоротать остаток рабочего дня. не знаю что было, но после:

> sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get upgrade

проблема не проявилась. на прошлой неделе делал всё точь в точь по мануалу в виртуалке, плюс добавил этот репозиторий - проблема еще была. сейчас на реальном железе всё заработало. 
потом таки сделаю образ чистой системы и скину ссылочку.

**Comment by madw0lf** [comment]
как и обещал:
Ubuntu 16.04.2 server с установленной поверх xubuntu
login: gis
password (в системе и на все сервисы): gis
nginx(не настроен)
PostgreSQL 9.5.7
PostGIS 2.2
Apache 2.4.18 
MySQL 5.7.18 
QGIS 2.14

NextGIS Web:
http://0.0.0.0:6543
login: administrator
password: admin
с модулями:
nextgisweb_qgis
nextgisweb_basemap
Запуск через pserve:
$ cd ~/ngw
$ env/bin/pserve development.ini
в rc.local не прописано

установлена панель Webmin для управления через веб-интерфейс, адрес:
https://localhost:10000/

ссылка на образ https://yadi.sk/d/nUxkDHeD3KVbWP
md5: 77dc8902d1f1bb993bd37fa42e4d5ca0  Ubuntu_ngw_v1.iso

сборка сделана как бэкап для себя, на случай если что-то пойдет не так.

**Comment by darkscript** [comment]
@madw0lf could I get this Ubuntu_ngw_v1.iso in english, spend time trying to resolve #587. Crazy with numpy/gydal version. Am stuck in that and am using current nextgis web git status (1st Jan 2018)

**Comment by drnextgis** [comment]
@darkscript how we can help you? Could you share your environment info or may be can provide ssh access to your instance?

**Comment by darkscript** [comment]
@drnextgis am using putty to connect, I attached .ppk file for putty, public dns: ec2-52-14-178-94.us-east-2.compute.amazonaws.com and login as : ubuntu

[phive-putty.zip](https://github.com/nextgis/nextgisweb/files/1599504/phive-putty.zip)

**Comment by drnextgis** [comment]
@darkscript I've fixed your issue and you can delete your credentials now. For all who will faced with the same issue in the future:

```bash
pip uninstall pygdal
pip uninstall numpy
pip install --no-cache-dir ./nextgisweb
```

**Comment by darkscript** [comment]
Thanks much, I appreciate the help. Am now working on launching using uSWGI+nginx, no much success so far, trouble with the configurations (config.ini, not sure). The access to the instance is still open. I appreciate the help.
