### ISSUE TITLE
Проблемы с добавлением подложки

### ISSUE THREAD

**Issue by Venique** [nextgis/nextgisweb#590]
Не получается добавить стороннюю подложку на отображаемую веб-карту. html-версия инструкции ссылается на пункты меню в веб-интерфейсе, которые отсутствуют. Кое-как нашёл упоминание о том, что можно задать подложки через basemap.json. Скопировал его в корневую директорию ngw, прописал путь к новому файлу в config.ini, для чистоты эксперимента сократил его объём до такого:
```
[{
    "base": {
        "keyname": "osm-mapnik",
        "mid": "ngw/openlayers/layer/OSM"
    },
    "layer": {
        "title": "OpenStreetMap"
    },
    "source": {}
}, {
    "base": {
        "keyname": "test",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "test",
        "visible": false
    },
    "source": {}
}]
```

В данном случае корректно отображается стандартная подложка OSM и стиль без подложки (пустой). Сверх этого удалось подключить только подложки Bing, скопировав описание из стандартного basemaps.json, а также добавив API-ключ в config.ini. Что-то ещё - ни в какую. Пробовал варианты, описанные, например, [здесь](https://raw.githubusercontent.com/nextgis/nextgisweb_compulink/master/nextgisweb_compulink/basemaps.json) или [здесь](https://raw.githubusercontent.com/nextgis/nextgisweb_ecopassport/master/nextgisweb_lipetsk/basemaps.json).

Формат записи по ссылкам, кстати, совершенно отличается от формата в текущей версии файла basemaps.json, в том числе и от инструкции на [wiki-странице](https://github.com/nextgis/nextgisweb/wiki/%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%BE%D0%B9-%D0%BF%D0%BE%D0%B4%D0%BB%D0%BE%D0%B6%D0%BA%D0%B8-%D0%B2-NGW), которая в свою очередь отличается от описания в [документации](http://docs.nextgis.ru/docs_ngweb/source/install-ubuntu.html#id5). В итоге что действительно актуально и какими инструкциями пользоваться - не ясно, а в условиях дефицита корректной информации начинаешь хвататься за каждую крупинку. :)

Так вот, подключить что-то кроме OSM, Bing и пустого слоя по аналогии с приведёнными выше ссылками (адаптируя синтаксис под синтаксис текущей версии файла basemaps.json) не получилось. В логах никаких ошибок не рисуется, просто отображается либо белый фон вместо подложки, либо нужный пункт в меню с выбором подложек просто не появляется. Больший интерес представляет, конечно же, подложка Google - я даже нашёл в более ранних коммитах файл Google.js, который на текущий момент удалён, подложил его в nextgisweb/nextgisweb/amd_packages/ngw/openlayers/layer, описал подложку в basemaps.json, после чего вообще ни одна подложка не отрисовывалась, даже стандартная OSM. Ошибок в логах также не было.

```
[{
    "base": {
        "keyname": "google-satellite",
        "mid": "ngw/openlayers/layer/Google"
    },
    "layer": {
        "title": "Google - Спутник",
        "visible": false
    },
    "source": {
        "imagerySet": "satellite"
}]
```

В случае с XYZ подложка Спутника просто не прорисовывалась.

```
[{
    "base": {
        "keyname": "sputnik",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "Карта Спутник",
        "visible": false
    },
    "source": {
        "url": "http://tiles.maps.sputnik.ru/tiles/kmt2/${z}/${x}/${y}.png"
}]
```

Исходя из данного примера использования, а также того, что в актуальной версии basemaps.json через XYZ отрисовывается пустая подложка, я предположил, что XYZ - некий универсальный .js для работы с подложками из внешних источников. Поэтому на основе [данной темы](http://gis-lab.info/forum/viewtopic.php?f=19&t=19763) (где синтаксис, кстати, очень схож с текущим) я даже попробовал сделать так и внезапно подложка Яндекса отрисовалась.

```
[{
    "base": {
        "keyname": "yandex",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "Яндекс Спутник",
        "visible": false
    },
    "source": {
        "url": "http://sat02.maps.yandex.net?l=sat&v=2.8.3&z={z}&x={x}&y={y}"
}]
```

Можно считать это чистой удачей. :) А как с остальными быть? Где искать подходящие для XYZ подложки? И как всё-таки подключить Google? Какое-то применение текущим Image.js и Vector.js есть?

---

P.S: я не линуксоид и даже не ГИСовец, поэтому на установку сервера и приведение его в чувства потребовалось почти два дня. В основном, из-за неточностей в документации. Например, корректно поставить всё на Ubuntu (что 14, что 16) не получилось, т.к. после установки NGW QGIS приложение не запускалось, ссылаясь на ряд отсутствующих модулей. Скорее всего, проблема была в пути до модулей python, но решить мне её так и не удалось.

К тому же, в инструкции ряд команд дан для QGIS выше 2.8, а следом идёт пустой блок для QGIS 2.16. Причём, в английской версии он пустой, а в русской - нет. Для пользователей Ubuntu это может вызвать затруднения, в отличии от пользователей CentOS, для которых последний доступный QGIS во всех репах - 2.14. Именно на CentOS 7, кстати, всё и получилось завести. Но и там есть оговорки по документации, например:
- epel подключается ПОСЛЕ установки pgsql, а не до, хотя об этом даже сказано [по ссылке](http://yum.postgresql.org/repopackages.php), куда предлагает сходить документация
- описывается процедура установки pgsql 9.5, хотя на текущий момент доступна уже 9.6
- не указана необходимость обновления pip, как глобального, так и внутри virtualenv, без чего (лично у меня) установка некоторых пакетов проходила некорректно - например, не создавались nextgisweb-config, nextgisweb-i18n и т.п.
- сам процесс установки NGW QGIS, помимо уточнения про блоки с командами для 2.8+\2.16+, на мой взгляд, лучше конкретизировать:
-- такие как я могут понимать инструкцию слишком буквально, хотя искать и устанавливать python-sip\python-qt\python-qgis вовсе не надо, достаточно установить последний, а он подтянет за собой всё остальное
-- делать это необходимо уже после установки самого QGIS, который в свою очередь надо ставить вовсе не ориентируясь на [инструкцию с официального сайта](http://qgis.org/ru/site/forusers/alldownloads.html#id19), потому что:
--- последнюю (на данный момент) версию 2.18 для CentOS вы никогда не скачаете ни с fedora.vitu.ch, ни откуда-либо ещё, ибо её попросту нет, может получится собрать самостоятельно - я не пробовал, далёк от этого
--- подключая ELGIS, вы нарветёсь на конфликт как с EPEL, так и с подключенным ранее по инструкции NGW PGDP (на мысли об этом должна навести попытка установить qgis-mapserver, которого под CentOS 7 в репозиториях нет)
--- установить qgis-grass можно только если он вам очень нужен, так как исключительно в конце вы узнаете, что он абсолютно не совместим с некоторыми версиями пакетов. которые уже установлены, а начав их даунгрейдить (даже прибегнув к удалению самих rpm без зависимостей, чтобы не поломать всё остальное) вы упретёсь в pgsql96, который не захочет работать с одним из пакетов (не вспомню уже каким именно) версии ниже 5.0, для работы с ним придётся установить pgsql93 и ниже, а это, как говорится, совсем другая история и проще начать установку сначала, но уже используя pgsql93 и всю соответствующую по версии обвязку
--- после процедуры установки нигде не описано, что придётся сделать initialize_db, иначе форма добавления слоя QGIS отображаться не будет
- установку uwsgi внутри virtualenv лучше исключить, если он собирается работать с nginx, установленным через менеджер пакетов
- не совсем понятно описаны варианты установки uwsgi+nginx, то ли они последовательно дополняют друг друга, то ли взаимозаменяемы
- ну и `исправления вносятся в соответствующий файл из папки /etc/nginx/sites-available/` - в Ubuntu, может, и так, а в CentOS создаётся conf-файл в /etc/nginx/conf.d/

Извините, что всё в один Issue свалил, как говорится, был напуган. Надеюсь, это поможет улучшить документацию и упростит жизнь будущим поколениям.

**Comment by drnextgis** [comment]
Здравствуйте, спасибо за фидбек!

1. Формат `basemaps.json` в других репозиториях отличается от текущего, поскольку эти проекты основаны на старой ветке NextGIS Web `2`, текущая версия `3`. Добавил разъяснение про `basemaps.json` в документацию, устаревшую wiki-страницу прибил.
2. В OpenLayers 3 нет нативной подложки GoogleMaps, поэтому по умолчанию эти подложки больше не отображаются на карте. Технически есть возможность добавить подложку Google через `basemaps.json` (но это я так понимаю является нарушением лицензионных соглашений), прописав туда необходимый URL. Список URL-ов всевозможных подложек можно посмотреть на нашем сервисе [QMS](https://qms.nextgis.com/).
3. Для облегчения добавления подложек на карту существует пакет `nextgisweb_basemap` (на данный момент приватный), который обеспечивает поддержку QMS в NextGIS Web. Попробовать его в действии можно создав инстанс в облаке http://nextgis.ru.

**Comment by simgislab** [comment]
добавил в документацию Warning, что мы раздел по CentOS официально не поддерживаем.

>Например, корректно поставить всё на Ubuntu (что 14, что 16) не получилось, т.к. после установки NGW QGIS приложение не запускалось, ссылаясь на ряд отсутствующих модулей.
Вот тут хотелось бы поподробнее (для 14), так как её мы как раз поддерживаем и пытаемся все нюансы в документации оперативно исправлять.

>следом идёт пустой блок для QGIS 2.16
Блок вернул.

**Comment by drnextgis** [comment]
@Venique, разобрались с подложками?

**Comment by Venique** [comment]
@drnextgis да, в итоге разобрался. Основные подключенные слои выглядят вот так:

```
[{
    "base": {
        "keyname": "osm-mapnik",
        "mid": "ngw/openlayers/layer/OSM"
    },
    "layer": {
        "title": "OpenStreetMap"
    },
    "source": {}
}, {
    "base": {
        "keyname": "bing-satellite",
        "mid": "ngw/openlayers/layer/Bing"
    },
    "layer": {
        "title": "Bing - Спутник",
        "visible": false
    },
    "source": {
        "imagerySet": "Aerial"
    }
}, {
    "base": {
        "keyname": "bing-hybrid",
        "mid": "ngw/openlayers/layer/Bing"
    },
    "layer": {
        "title": "Bing - Гибрид",
        "visible": false
    },
    "source": {
        "imagerySet": "AerialWithLabels"
    }
}, {
    "base": {
        "keyname": "bing-road",
        "mid": "ngw/openlayers/layer/Bing"
    },
    "layer": {
        "title": "Bing - Схема",
        "visible": false
    },
    "source": {
        "imagerySet": "Road"
    }
}, {
    "base": {
        "keyname": "yandex-satellite",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "Яндекс - Спутник",
        "visible": false
    },
    "source": {
        "url": "http://sat02.maps.yandex.net/tiles?l=sat&z={z}&x={x}&y={y}"
    }
}, {
    "base": {
        "keyname": "yandex-road",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "Яндекс - Схема",
        "visible": false
    },
    "source": {
        "url": "http://vec02.maps.yandex.net/tiles?l=map&v=4.40&x={x}&y={y}&z={z}"
    }
}, {
    "base": {
        "keyname": "yandex-vector",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "Яндекс - Вектор",
        "visible": false
    },
    "source": {
        "url": "http://vec02.maps.yandex.net/tiles?l=skl&z={z}&x={x}&y={y}"
    }
}, {
    "base": {
        "keyname": "sputnik",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "Спутник - Схема",
        "visible": false
    },
    "source": {
        "url": "http://a.tiles.maps.sputnik.ru/tiles/kmt2/{z}/{x}/{y}.png"
    }
}, {
    "base": {
        "keyname": "blank",
        "mid": "ngw/openlayers/layer/XYZ"
    },
    "layer": {
        "title": "Пустой слой",
        "visible": false
    },
    "source": {}
}]
```

Естественно, предварительно нужно получить и прописать API-ключ BingMaps, что также нигде в явном виде в документации не указано. Как и рекомендации к переносу basemaps.json с последующим указанием пути до файла. Ещё нашёл небольшой сборник рабочих подложек (тайлов):
https://github.com/yetzt/amab/blob/master/assets/data/data.json

@simgislab раз вы CentOS официально не поддерживаете, то форкну документацию и внесу туда все накопленные замечания, актуализировав её. Понятно, что она больше рассчитана на продвинутых администраторов, но некоторые нюансы хотелось бы там прописать, дабы сделать процесс доступнее. Ваше "no any warranty", думаю, позволит без проблем слить это с основной документацией.

Правда, у меня также есть замечания по QGIS и настройке nginx+uWSGI. Надеюсь, их тоже сможете добавить. Постараюсь всё описать в ближайшем будущем. В разделе про nginx+uWSGI, мягко говоря, каша из отрывков различных способов реализации, которые по отдельности толком завести фронт-енд не дали.

Касательно Ubuntu - к сожалению, подробных логов предоставить не смогу, так как после неоднократных попыток всё это дело завести я удалил виртуальную машину. Точно могу сказать, что проблема начиналась при установке NextGIS Web QGIS. Насколько я помню, в virtualenv не копировался PyQt4, несмотря на установленный в систему пакет. Что самое интересное, сам по себе NextGIS Web запускался, а после установки QGIS уже нет, хотя пакет на него никак влиять не должен был. Спишем всё на аномалию, если других подобных жалоб не поступало :)

**Comment by simgislab** [comment]
ждем пулл-реквестов

**Comment by drnextgis** [comment]
@Venique, а вы в курсе, что подключенные таким образом тайлы Yandex будут иметь значительное смещение? Yandex использую другую проекцию, а именно `EPSG:3395`, в то время как OSM и Google `EPSG:3857`. Можете попереключать подложки у себя и убедиться в этом. Если нужен именно Yandex и нет возможности использовать `nextgisweb_basemap`, то можете поступить следующим образом.

1. Создаёте директорию `nextgisweb/amd_packages/contrib/proj4` и кладёте туда файл [proj4.js](https://cdnjs.com/libraries/proj4js)
2. Вносите следующие исправления:
```
$ git diff
diff --git a/nextgisweb/__init__.py b/nextgisweb/__init__.py
index d3255a0..ef468d7 100644
--- a/nextgisweb/__init__.py
+++ b/nextgisweb/__init__.py
@@ -85,6 +85,7 @@ def amd_packages():
         ('openlayers', 'nextgisweb:amd_packages/contrib/openlayers'),
         ('svg4everybody', 'nextgisweb:amd_packages/contrib/svg4everybody'),
         ('codemirror', 'nextgisweb:amd_packages/contrib/codemirror'),
+        ('proj4', 'nextgisweb:amd_packages/contrib/proj4'),
 
         # nextgisweb packages
         ('ngw', 'nextgisweb:amd_packages/ngw'),
diff --git a/nextgisweb/amd_packages/ngw/openlayers/Map.js b/nextgisweb/amd_packages/ngw/openlayers/Map.js
index 64f3f81..3391ddd 100644
--- a/nextgisweb/amd_packages/ngw/openlayers/Map.js
+++ b/nextgisweb/amd_packages/ngw/openlayers/Map.js
@@ -2,11 +2,13 @@
 define([
     "dojo/_base/declare",
     "dojo/Stateful",
-    "openlayers/ol"
+    "openlayers/ol",
+    "proj4/proj4"
 ], function (
     declare,
     Stateful,
-    ol
+    ol,
+    proj4
 ) {
     return declare(Stateful, {
         DPI: 1000 / 39.37 / 0.28,
@@ -28,6 +30,15 @@ define([
             olView.on("change:center", function (evt) {
                 widget.set("center", olView.getCenter());
             });
+
+            ol.proj.setProj4(proj4);
+
+            // Yandex.Maps
+            proj4.defs("EPSG:3395","+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs");
+            ol.proj.get('EPSG:3395').setExtent([-20037508.342789244,
+                                                -20037508.342789244,
+                                                 20037508.342789244,
+                                                 20037508.342789244]);
         },
 
         addLayer: function (layer) {
```
3. В секцию `source` своей подложки добавляете `"projection": "EPSG:3395"` и перезапускаете NGW. Должно заработать, я проверял.

**Comment by Venique** [comment]
Да, было замечено существенное смещение подложек. Я даже нашёл схожую и довольно старую запись в блоге Я.Карт: https://yandex.ru/blog/mapsapi/36655

Директорию создал, файл подложил, а вот с диффом возникли проблемы. Положил его в отдельный файл, поправил путь в начале диффа до абсолютного (/root/nextgisweb/nextgisweb/__init__.py), запустил git diff file.name (еще пробовал git apply file.name), но результата никакого. Открыл имеющийся init.py - он не совсем подходит по содержанию под этот дифф. Вот этих блока, например, нет вообще:

```
         ('openlayers', 'nextgisweb:amd_packages/contrib/openlayers'),
         ('svg4everybody', 'nextgisweb:amd_packages/contrib/svg4everybody'),
         ('codemirror', 'nextgisweb:amd_packages/contrib/codemirror'),
```

Файл у меня из стандартной поставки, ничего в нём не менялось. Можете приложить уже готовый init.py, созданный на основе последней версии файла из репозитория?

P.S: выше Вы сами сказали, что nextgisweb_basemap пока недоступен для установки и является приватным, поэтому и делаю руками, иначе бы давно всё сделал через веб-интерфейс. :)

**Comment by drnextgis** [comment]
Не понял, как нет этого блока, вот же [файл](https://github.com/nextgis/nextgisweb/blob/3/nextgisweb/__init__.py) и там всё это есть, нужно просто добавить запись для `proj4`.

**Comment by simgislab** [comment]
https://github.com/nextgis/nextgisweb_basemap

**Comment by Venique** [comment]
@drnextgis Видимо, моя попытка выполнить diff patch некорректно отработала... Заменил текущий файл на тот, что лежит в репозитории, чтобы вернуть всё к исходному состоянию.

Хочу попробовать basemap, раз он стал публичным, каким образом его установить?
```
git clone https://github.com/nextgis/nextgisweb_basemap.git
source env/bin/activate
env/bin/pip install -e ./nextgisweb_basemap
env/bin/nextgisweb --config config.ini initialize_db
```

Или что-то ещё?

**Comment by simgislab** [comment]
я понимаю, что хочется получить конкретный ответ от разработчика, но давайте разговаривать на языке "что непонятно в документации и что там можно улучшить", а еще лучше - пулл-реквесты

http://docs.nextgis.ru/docs_ngweb/source/extension.html#id3

**Comment by Venique** [comment]
Установил. Добавил `http://vec02.maps.yandex.net/tiles?l=map&v=4.40&x={x}&y={y}&z={z}`, привязал к карте. Всё равно есть смещение.

http://take.ms/ANufr
http://take.ms/jAZVu
А теперь Яндекс:
http://take.ms/P4e6b

Где в веб-интерфейсе Basemaps есть аналог `source`?

**Comment by drnextgis** [comment]
1. Основной способ добавления подложек через `nextgisweb_basemap` - это поиск их по QMS и выбор нужной из списка. В этом случае все параметры подложки, в том числе и проекция подтягиваются автоматически. Если в QMS нет нужной подложки, то можно указать просто URL, но в этом случае будут использованы дефолтные параметры подложки (проекция `EPSG:3857`). Поэтому, чтобы добавить Yandex, необходимо, чтобы он был в QMS. Он раньше там точно был, но сейчас я его не наблюдаю. Может @simgislab прояснит ситуацию. Если что, то вот Sputnik чем-то похож по виду на Yandex, [пример](http://rykovd.nextgis.com/resource/276/display).

2. Если для карты не указать перечень подложек, то по умолчанию будут использованы те, что перечислены в basemaps.json, если хоть одна подложка указаны в настройках конкретной карты, то для неё basemaps.json игнорируется.

Согласен, что много чего ещё можно улучшить. Тот же Bing пока не подключается через QMS, так как у него совсем другая схема тайлирования, да и нужно предусмотреть ввод пользовательского ключа. Не знаю насколько актуально это для большинства пользователей, пока кроме вас об этом никто не просил.

**Comment by Venique** [comment]
Я Вас понял. В таком случае, ручное добавление подложек через файл для меня является более функциональным способом. Попробовал ещё раз описанный метод коррекции - отработал, теперь смещения нет. Спасибо за разъяснения.
