### ISSUE TITLE
Print webmap - add pixel dimension

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#591]
Юзкейс: мне нужно несколько кусков веб-карты отрендрить в png для презентации на полном экране, с подложкой mapnik.
![2017-06-19 11-24-22](https://user-images.githubusercontent.com/4630662/27276007-5b598eb0-54e2-11e7-955a-8a792c9dafe0.png)

На экране печати карты можно выбрать размер в форматах бумаги.
Предлагаю добавить на этот же экран задание размера в пикселах (можно только на премиум, или сделать на преиуме большие размеры)

Это будет единственная возможность генерации полноэкранных картинок с картами для веба без ресемплинга подложки. 
Другие нынешние решения:
* сохранить карту правой кнопкой мыши при полноэкранном режиме браузера можно только с размером чуть меньше чем экран твоего компьютера, нельзя подогнать под соотношение сторон.
* отрендрить в qgis - долго, будет мутный ресемплинг подложки, на Ubuntu 17 сложно поставить версию qgis где можно задавать размер рендеринга в пикселах
* maperitive - падает, читает только один векторный формат.

**Comment by karavanjo** [comment]
Is clarified in https://github.com/nextgis/nextgisweb/issues/620 and https://github.com/nextgis/nextgisweb/issues/621
