### ISSUE TITLE
Ошибка в процессе установки,  п.11.2.4 Инструкции

### ISSUE THREAD

**Issue by pobedov** [nextgis/nextgisweb#592]
Ребята, подскажите  пожалуйста, как обойти эту "незадачу",  которая возникает в момент выполнения установки NextGIS Web в режиме разработки, лог: 

Downloading/unpacking pyramid-debugtoolbar (from nextgisweb==3.0)
  Downloading pyramid_debugtoolbar-4.2.tar.gz (2.9MB): 2.9MB downloaded
  Running setup.py egg_info for package pyramid-debugtoolbar
    error in pyramid_debugtoolbar setup command: Invalid environment marker: python_version<"3.3"
    Complete output from command python setup.py egg_info:
    error in pyramid_debugtoolbar setup command: Invalid environment marker: python_version<"3.3"

**Comment by drnextgis** [comment]
Предлагают обновить pip:

```
pip install -U pip
```

А на каком это дистрибутиве так?

**Comment by pobedov** [comment]
Centos 7

**Comment by pobedov** [comment]
Не помогло

**Comment by drnextgis** [comment]
Официально мы не поддерживаем Centos, но вот буквально вчера я ставил NGW на Centos 7, никаких проблем с установкой не было. Если есть доступ, то могу посмотреть что там у вас.

**Comment by simgislab** [comment]
Решение подобных проблем входит в программу поддержки:
http://nextgis.ru/pricing/#ngw
