### ISSUE TITLE
Неверный атрибут при создании wmsclient_connection всегда capcache

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgisweb#597]
При попытке добавления wmsclient_connection получаю ошибку:

> Неизвестная ошибка 'NotImplementedError' в сериализаторе 'wmsclient_connection', атрибут 'capcache'.

В независимости от того какой атрибут wmsclient_connection  не задан или задан неверно.

Например если "version":null
` {"wmsclient_connection": {"username": "administrator", "url": "http://alisovenko.nextgis.com/api/resource/3095/wms", "password": "q1w2e3zxc", "version": null, "capcache": "query"}, "resource": {"display_name": "1(2)", "parent": {"id": 3096}, "cls": "wmsclient_connection"}}`

Нужно или указать конкретный атрибут, который задан неверно.
Или сообщение об ошибке должно быть другим.

**Comment by dezhin** [comment]
Сейчас у меня не воспроизводится, закрываю.
