### ISSUE TITLE
Error creating new group in IE 11

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#601]
![](http://m-d.me/img/ss/20171102-nx0-142kb.jpg)
![](http://m-d.me/img/ss/20171102-x6b-62kb.jpg)

**Comment by karavanjo** [comment]
Fixed by https://github.com/nextgis/nextgisweb/commit/7fe44fd84a0a059919580fb92535cc246240ad7d, details in https://github.com/nextgis/nextgisweb/issues/612
