### ISSUE TITLE
Error when adding PostGIS layer

### ISSUE THREAD

**Issue by mbandy** [nextgis/nextgisweb#606]
When adding a PostGIS layer on NGW, I get the following error:

> Unexpected error occurred during the operation.
> 
> Error Message: Unknown exception "ProgrammingError' in serializer 'postgis_layer' attribute 'fields'.

This happens if "Attribute Definitions" is set to "Reload". If I set "Attribute Definitions" to "Keep" the layer will save and display, but no attributes are visible.

![image](https://user-images.githubusercontent.com/25719119/33529331-d24a2692-d82c-11e7-80ef-ce8dd2c64002.png)

**Comment by drnextgis** [comment]
Do you have fields of `decimal` or `numeric` type in your table?

**Comment by mbandy** [comment]
No I tried it on two tables. Same result.
![image](https://user-images.githubusercontent.com/25719119/33533209-d2127a14-d85c-11e7-9cc3-a9c7a070b79c.png)
![image](https://user-images.githubusercontent.com/25719119/33533224-e6dccada-d85c-11e7-8288-ce805cfd7806.png)

**Comment by drnextgis** [comment]
What kind of instance are you talking about: instance at nextgis.com or your local one? And if it possible could you provide access to any table which cannot be added to NGW?

**Comment by mbandy** [comment]
It's a local instance of NGW on our corporate network. I can't provide access to our network, but I'm happy to give you any information you need.

**Comment by drnextgis** [comment]
Ok. Do you use the latest version of NGW? Also can you run NGW in debugging mode use `env/bin/pserve development.ini` command and show traceback?

**Comment by mbandy** [comment]
Thank you very much, that did it. The error on the console was:

`ProgrammingError: (psycopg2.ProgrammingError) permission denied for relation geometry_columns`

`grant select on geometry_columns to [user] `fixed the problem. It works as exected now. Thank you very much. I am kicking myself for not seeing that earlier.
