### ISSUE TITLE
QGIS styling not working

### ISSUE THREAD

**Issue by gerbsen** [nextgis/nextgisweb#608]
Hey,
I've installed nextgis locally and can't seem to be able to:

1.  create a **QGIS style** resource, it just isn't shown. (only **MapServer style**)
2. If I create a MapServer style and click **Import QGIS style** and then upload the attached file I only get (this also happens if I use the hosted version)
```
<map>
  <!-- Неизвестный тип: graduatedSymbol -->
</map>
```

any ideas?
cheers, daniel

(had to rename the style file since github complained about qml)
[style.qml.txt](https://github.com/nextgis/nextgisweb/files/1609292/style.qml.txt)

**Comment by gerbsen** [comment]
Okay, I now managed to get the QGIS style layer showing up, but it's not showing up on the map. I do have a problem during installation with this:

```
For QGIS 2.16 and higher:

# Only for latest QGIS version (2.16 and higher)
export PYTHONPATH=$PYTHONPATH:/usr/bin/python
cp -r `/usr/bin/python -c "import PyQt, os.path; print os.path.split(PyQt.__file__)[0]"` $DST
``` 

I always get this error:

```
Step 39/40 : RUN cp -r `/usr/bin/python -c "import PyQt, os.path; print os.path.split(PyQt.__file__)[0]"` /nextgis/env/lib/python2.7/site-packages
 ---> Running in 536a651ee770
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named PyQt
cp: missing destination file operand after '/nextgis/env/lib/python2.7/site-packages'
Try 'cp --help' for more information.
```

Is there maybe a system dependency missing?

**Comment by drnextgis** [comment]
I've updated instrutctions for nextgisweb_qgis installing. You have to install dependencies such way (qgis-to-env is file from nextgisweb_qgis repository):

```
qgis-to-env env
```

**Comment by gerbsen** [comment]
hey @drnextgis I've used your tips to install the qgis plugin. unfortunately all my geometries are somehow transparent and I do not get any error messages: 

<img width="876" alt="screenshot 2018-01-17 22 27 58" src="https://user-images.githubusercontent.com/1186245/35068039-255b97cc-fbd6-11e7-9c10-8a76e8fd0e4d.png">

If I upload the layer via QGIS to nextgis.com I received normal colored geometries. The QML file is exactly the same for my local installation and nextgis online...

[8.qml.txt](https://github.com/nextgis/nextgisweb/files/1640664/8.qml.txt)

**Comment by drnextgis** [comment]
@gerbsen one of my colleagues faced with the same issue. Try to install `qgis` package. I've updated instructions.

**Comment by gerbsen** [comment]
@drnextgis where did you update the instructions?

**Comment by drnextgis** [comment]
https://github.com/nextgis/nextgisweb_qgis/commit/d774ad0ace7ea603de4daf848c2f2d632f31f02d

**Comment by gerbsen** [comment]
Hmm.. I'm using your docker install, where this is already added :(

**Comment by drnextgis** [comment]
Cannot reproduce this issue here with docker. Could you share your data and qml files?

**Comment by gerbsen** [comment]
Okay, I do see the geometries now. :( Recreated everything and removed a HTST issue with my NGINX server. Sorry for the confusion.

**Comment by gerbsen** [comment]
So I'm sorry but I have to reopen this issue. I've uploaded a different layer before and that seemed to work. Unfortunately all other layers I have (mostly coming from Postgis) are not displayed. So the steps to reproduce this issue:

1. Load the `Leipzig` shape file
2. Layer style `Graduated`
3. Column `GRÜNE_per`
4. Classify `Equal interval`
5. Import layer to nextgis
6. create web map

[leipzig.zip](https://github.com/nextgis/nextgisweb/files/1659018/leipzig.zip)
[15.qml.txt](https://github.com/nextgis/nextgisweb/files/1659021/15.qml.txt)

**Comment by gerbsen** [comment]
@drnextgis I think I've found the problem! :) I think it is due to an 'Umlaut' -> "Ü" in the attribute name. If I import a shape file with only one column and no umlauts, the layer is shown correctly.

**Comment by drnextgis** [comment]
It seems that you have broken field names (`FREIE W�_1`, for example):

```
$ ogrinfo -so -al leipzig.shp
INFO: Open of `leipzig.shp'
      using driver `ESRI Shapefile' successful.

Layer name: leipzig
Metadata:
  DBF_DATE_LAST_UPDATE=2018-01-24
Geometry: Polygon
Feature Count: 63
Extent: (307450.169200, 5679889.824000) - (328773.360000, 5702756.016050)
Layer SRS WKT:
PROJCS["SWEREF99_TM",
    GEOGCS["GCS_SWEREF99",
        DATUM["SWEREF99",
            SPHEROID["GRS_1980",6378137,298.257222101]],
        PRIMEM["Greenwich",0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",15],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["Meter",1]]
index: Real (20.0)
Ortsteil: String (254.0)
Wahlkreis: Real (20.0)
Wahlberech: Real (20.0)
Wähler: Real (20.0)
Ungültige: Real (20.0)
Gültige S: Real (20.0)
CDU: Real (20.0)
DIE LINKE: Real (20.0)
SPD: Real (20.0)
AfD: Real (20.0)
GRÜNE: Real (20.0)
NPD: Real (20.0)
FDP: Real (20.0)
PIRATEN: Real (20.0)
FREIE WÄH: Real (20.0)
BüSo: Real (20.0)
MLPD: Real (20.0)
BGE: Real (20.0)
DiB: Real (20.0)
ÖDP: Real (20.0)
Die PARTEI: Real (20.0)
Tierschutz: Real (20.0)
V-Partei³: Real (20.0)
CDU_percen: Real (24.15)
CDU_diff_2: Real (24.15)
CDU_diff_1: Real (24.15)
DIE LINKE_: Real (24.15)
DIE LINK_1: Real (24.15)
DIE LINK_2: Real (24.15)
SPD_percen: Real (24.15)
SPD_diff_2: Real (24.15)
SPD_diff_1: Real (24.15)
AfD_percen: Real (24.15)
AfD_diff_2: Real (24.15)
AfD_diff_1: Real (24.15)
GRÜNE_per: Real (24.15)
GRÜNE_dif: Real (24.15)
GRÜNE_d_1: Real (24.15)
NPD_percen: Real (24.15)
NPD_diff_2: Real (24.15)
NPD_diff_1: Real (24.15)
FDP_percen: Real (24.15)
FDP_diff_2: Real (24.15)
FDP_diff_1: Real (24.15)
PIRATEN_pe: Real (24.15)
PIRATEN_di: Real (24.15)
PIRATEN__1: Real (24.15)
FREIE W�_1: Real (24.15)
FREIE W�_2: Real (24.15)
FREIE W�_3: Real (24.15)
BüSo_perc: Real (24.15)
BüSo_diff: Real (24.15)
BüSo_di_1: Real (24.15)
MLPD_perce: Real (24.15)
MLPD_diff_: Real (24.15)
MLPD_dif_1: Real (24.15)
BGE_percen: Real (24.15)
BGE_diff_2: Real (24.15)
BGE_diff_1: Real (24.15)
DiB_percen: Real (24.15)
DiB_diff_2: Real (24.15)
DiB_diff_1: Real (24.15)
ÖDP_perce: Real (24.15)
ÖDP_diff_: Real (24.15)
ÖDP_dif_1: Real (24.15)
Die PART_1: Real (24.15)
Die PART_2: Real (24.15)
Die PART_3: Real (24.15)
Tierschu_1: Real (24.15)
Tierschu_2: Real (24.15)
Tierschu_3: Real (24.15)
V-Partei_1: Real (24.15)
V-Partei_2: Real (24.15)
V-Partei_3: Real (24.15)
```

**Comment by gerbsen** [comment]
No, I've tried this with a layer that only contains a single column with and without umlauts and ogrinfo does not comlain: one is working one is not :(

[leipzig_with_umlaut.zip](https://github.com/nextgis/nextgisweb/files/1659441/leipzig_with_umlaut.zip)
[leipzig_without_umlaut.zip](https://github.com/nextgis/nextgisweb/files/1659442/leipzig_without_umlaut.zip)

**Comment by drnextgis** [comment]
@gerbsen I've renamed these three columns and have uploaded your layer and style to nextgis.com: http://rykovd.nextgis.com/resource/276/display All works fine.

**Comment by gerbsen** [comment]
@drnextgis If I've a column with **Ü** the layer is not shown. I've just tried this with the `leipzig_with_umlaut.zip` first and then renamed the column in qgis to `GRUENE` and then it shows up.

**Comment by BishopGIS** [comment]
There is a special ``alias`` for non ASCII strings. Please use aliases instead of such field names. Non ASCII field name can be easily rename via Administrative UI. 
See http://docs.nextgis.com/docs_ngweb/source/layers_settings.html#layer-attributes

**Comment by drnextgis** [comment]
Have uploaded your two layer onto [webmap](http://rykovd.nextgis.com/resource/276/display) without any problem. Links to the appropriate style resources:
* **leipzig_with_umlaut**: http://rykovd.nextgis.com/api/resource/376/qml
* **leipzig_without_umlaut**: http://rykovd.nextgis.com/api/resource/378/qml

**Comment by drnextgis** [comment]
@gerbsen I have reproduced your issue with docker instance.

**Comment by drnextgis** [comment]
Issue was fixed. You have to update `ngwdocker` and to perform the following command:
```
docker-compose up -d
```

**Comment by gerbsen** [comment]
Awesome!
