### ISSUE TITLE
Line snaps automatically to create a polygon when upload to nextgisweb

### ISSUE THREAD

**Issue by darkscript** [nextgis/nextgisweb#609]
I tried to create a line (a linestring) on Android app and every time I synchronize with nextgisweb, the endpoints are automatically joined creating a polygon. Is it a known issue? Anyone has come across that? Would it be some configurations on mapserver?

**Comment by simgislab** [comment]
line automatically turns into polygon? sounds strange. When you create a layer, it is either line or polygon.

It is not clear WHERE line magically converts to polygon. On mobile? Then why the issue is opened here? On the server? But how you can sync a line layer with a polygonal one...

Confusing. Can you provide more exact steps to reproduce?

**Comment by darkscript** [comment]
It's simple to reproduce the bug, on your mobile app create a line and connect to nextgis web server (I created an account on nextgis web app), then upload your line to the webapp, add it to a web map, on the web map,  the line will be outomatically transformed to a polygon(endpoint and startpoint are joined). If you sync on the mobile app again, you will also have a polygon, I think the snapping of endpoint and start point happen in the web app

**Comment by drnextgis** [comment]
Cannot reproduse this issue here.

**Comment by darkscript** [comment]
Sorry I took some time before I gave the feedback, I created a test app at http://darkscript.nextgis.com with details (administrator, ZJ1pHOxg). I first added the darkscript.nextgis.com web gis to my mobile app version 2.5.6.8. Then in the mobile app I created a linestring (test-mobile) which I then send to web gis. In web gis, I gave the line a mapserver style and once it's added to the map, it isn't a linestring but a polygon, both ends of the line are joined by a straight line to create a polygon as shown in image I attached, you can also go to the web gis to see the final result. Follow my procedure to reproduce the bug. I also think this may be occurring due to a bug in mobile app maybe (highly likely that the nextgis mobile app first converts the line to a polygon before uploading to nextgis web gis).
![capture](https://user-images.githubusercontent.com/13992858/35939830-5c83c2f4-0c5e-11e8-9223-b9c763d76b9b.PNG)

**Comment by Cthulhu-Dreams** [comment]
I have had this issue as well - though I didnt need to view the line in QGIS to observe it.  The line would change into a polygon shortly after it was recorded in NextGIS mobile.

**Comment by darkscript** [comment]
I have not found a solution yet but the issue maybe occurring on the mobile app side, I attached a video to show the scenario. Any help will be appreciated https://drive.google.com/open?id=1B1covXIw_CWpdr7K_B9zamsYqqdY6ozB

**Comment by simgislab** [comment]
Thanks for the video. I was able to reproduce it here. We'll have a look at what's going on.

**Comment by darkscript** [comment]
@4eRTuk I have been trying to debug on mobile, didn't see any errors in log but  came across a different issue (unrelated), the mobile app can't handle editing/downloading any geometry with xyz(three dimensions geom), it can only handle xy data, nextgis mobile accepts 2d datasets only, it trims the XYZ coord by taking first and last coord, ending up with X and Z instead of X and Y. You can reproduce this by uploading a xyz line or point on nextgis web using qgis connect and try to do editing of the layer on mobile

**Comment by darkscript** [comment]
I really need a fix to this #609 issue though, I need to do an important presentation with nextgis system

**Comment by simgislab** [comment]
please don't mix things up, if you'd like to raise another issue, please do it separately in the correct repo

**Comment by darkscript** [comment]
I added the issue to [right place](https://github.com/nextgis/android_gisapp/issues/615)

**Comment by darkscript** [comment]
This issue was fixed on Nextgis mobile [commit](https://github.com/nextgis/android_gisapp/commit/922a491cc56aa0885137b5d9719ee13f512ea061)
