### ISSUE TITLE
Add tool to allow editing of geometry on map

### ISSUE THREAD

**Issue by darkscript** [nextgis/nextgisweb#610]
It would be great to allow editing of feature geometry on client side and sync with mapserver, we could integrate [this](http://viglino.github.io/ol-ext/examples/bar/map.control.editbar.html) from [ol-ext](https://github.com/Viglino/ol-ext).

**Comment by simgislab** [comment]
AFAIK this was already implemented in a separate branch https://github.com/nextgis/nextgisweb/tree/editing

**Comment by darkscript** [comment]
oh cool, didn't know that
