### ISSUE TITLE
Часть открытых ресурсов не видна пользователю "Гость" в веб-интерфейсе

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#623]
В  группе ресурсов [Открытые данные](http://opendata25.primorsky.ru/ngw/resource/36) созданы дочерние группы ресурсов при помощи NextGIS Connect.
Ранее созданные группы ресурсов [Векторные данные](http://opendata25.primorsky.ru/ngw/resource/2) видны гостю ( незалогиненный пользователь), а вновь созданные группы ресурсов  не видны - [Департамент лесного хозяйства Приморского края](http://opendata25.primorsky.ru/ngw/resource/618) .  Залогиненному пользователю новые группы ресурсов видны.
Права доступа родительского ресурса  [Открытые данные](http://opendata25.primorsky.ru/ngw/resource/36) позволяют Гостю читать структуру данных, данные, ресурсы, метаданные.
Права доступа дочернего ресурса [Векторные данные](http://opendata25.primorsky.ru/ngw/resource/2) Позволяют Гостю: чтение ресурсов, данных, метаданных, соединение с сервисами и открытие веб-карты. 
Права доступа дочернего ресурса [Департамент лесного хозяйства Приморского края](http://opendata25.primorsky.ru/ngw/resource/618) Также позволяют Гостю: чтение ресурсов, данных, метаданных, соединение с сервисами и открытие веб-карты. 

При этом по прямой ссылке, гость может зайти в группу ресурсов  [Департамент лесного хозяйства Приморского края](http://opendata25.primorsky.ru/ngw/resource/618)

Как сделать, что ресурсы в группе ресурсов [Открытые данные](http://opendata25.primorsky.ru/ngw/resource/36) были видны роли "Гость"?

**Comment by dezhin** [comment]
К сожалению ссылки уже не открываются. Если проблема актуальна, то дайте пример и переоткройте тикет.
