### ISSUE TITLE
Группы ресурсовсозданные через NextGIS Connect на седующий день через NGC не видна

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#624]
В группе ресурсов [Открытые данные](http://opendata25.primorsky.ru/ngw/resource/36) при помощи NextGIS Connect были созданы несколько групп ресурсов [615](http://opendata25.primorsky.ru/ngw/resource/615) - [626](http://opendata25.primorsky.ru/ngw/resource/615) .

При повторном авторизованном подключении в NextGIS Connect  на следующий день, созданные группы ресурсов не видны.
А при авторизированном просмотре Веб-ГИС через бразер, вышеуказанные группы ресурсов видны.

Как сделать чтоб в NextGIS Connect эти группы ресурсов стали доступны?

**Comment by alisovenko** [comment]
Подключился при помощи NextGIS Connect к сервису http://opendata25.primorsky.ru/ngw
Как Гость.
Список ресурсов в указанной группе в интерфейсе NextGIS Connect, совпадает со списком, который отображается через веб-интерфейсе, если заходить также - как гость.

Возможно, данное поведение обусловлено изменением прав на ресурсы?

**Comment by simgislab** [comment]
нужен воспроизводимый кейс
