### ISSUE TITLE
Update insufficient permissions error message

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#626]
> Insufficient permissions to perform the operation.
> 
> Error message: Attribute 'permissions' forbidden

should be

> Insufficient permissions to perform the operation. Forgot to log in?
> 
> Error message: Attribute 'permissions' forbidden

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/c4b8b9a41d2b3d9ae002c079e77e56dc72c87f77
