### ISSUE TITLE
Layer with unicode field dependent legend won't show (QGIS renderer)

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#627]
1. Upload a layer (it won't upload through Web, a) encoding problem cp1251, - can be fixed b) data error message, but it will upload through Connect)
2. Create a map (with Connect)
3. The layer won't show on the map

Possibly due to a style dependent on unicode field names.

What can we do here?

Example: 
[внуково-3 кабели.zip](https://github.com/nextgis/nextgisweb/files/1844134/-3.zip) Encoding: cp1251

**Comment by dezhin** [comment]
@simgislab, can you check this on testing instance qgis.staging.nextgis.com? I think, it should work.

**Comment by simgislab** [comment]
it works
