### ISSUE TITLE
Switch to GeoPackage

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#628]
![prefer-geopackage](https://user-images.githubusercontent.com/4630662/37978193-2ab43f5a-31ee-11e8-90cd-10ded03db26c.png)
We, members of the geospatial IT industry, believe that it is time to stop using Shapefiles as the primary vector data exchange format and to replace them with a format that takes advantage of the huge advances that have been made since Shapefile was introduced.

**Comment by simgislab** [comment]
haha, reopen as feature requests for import and export please!
