### ISSUE TITLE
Название пунктов по выгрузке векторного слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#629]
В меню векторного слоя, в административном интерфейсе пункты меню, которые касаются скчиванию векторных данных в разных форматах имеются следующие наименования:

* Загрузить GeoJSON
* Загрузить CSV

Слово загрузить воспринимается как загрузка в NGW. 
Предлагаю переменовать в ``Выгрузить``  или ``Скачать как``:

* Выгрузить GeoJSON
* Выгрузить CSV

или 

* Скачать как GeoJSON
* Скачать как CSV

**Comment by simgislab** [comment]
Давно хотел тоже попросить.

Я за "Скачать" однозначно

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/c643935204de6c56a3c8145094cb40d30724a49d
