### ISSUE TITLE
Изменение свойств стиля запрашивает перезагрущку QML

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#631]
Если зайти в ранее созданный стиль, изменить права доступа, то при попытке сохранения будет запрос на загрузку QML.
 
```
При попытке изменить права доступа на стиль векторного слоя происходит предупреждение 
с просьбой загрузить QML, хотя ранее он был загружен.
```

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb_qgis/commit/621b037839c97a9f6fc5b68b4dbe62b975a6613f
