### ISSUE TITLE
HTTP code return after upload raster

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#632]
after upload raster should be return code 202
Сейчас после загрузки растра, когда начинается его обработка в gdalwarp, nextgis connect выдаёт ошибку. Возможно это что-то связанное с кодами.
А может быть мой инстанс падает и начинает выдавать ошибку 502, и это связано с облаком.

**Comment by dezhin** [comment]
Сейчас все операции синхронные, 202 тут не причем. Ранее были определенные проблемы с таймаутами, но сейчас они в основном поправлены.
