### ISSUE TITLE
Один воркер должен всегда оставатся под http-сервер

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#633]
Шаги для воспроизведения:

- Гружу 2 больших растра по 400 Мб через Connect.
- Они не появляются в админке.
- Гружу третий такой же растр через веб-интерфейс.
- Теперь на сервере одновременно обрабатываются три растра.
- Весь веб-интерфейс перестаёт отвечать, и выдаёт 502 ошибку.

Ожидаемое поведение

Один воркер остаётся под веб, и не занимается утилитами gdal

**Comment by drnextgis** [comment]
NGW сейчас полностью синхронный и нет возможности выполнять тяжёлые задачи асинхронно.
