### ISSUE TITLE
Права суперпользователя сбрасываются при изменении пароля

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#636]
Шаги для воспроизведения:
1. Быть суперпользователем
2. Изменить пароль в ngw
3. После изменения пароля разлогиниться и залогиниться
4. ngw выдаёт ошибку "Insufficient permissions to perform this operation."

При этой операции сбрасывается флаг суперпользователя. Получается что пароль верный, но у пользователя нет прав на вход.
Затем, если поменять пароль через my.nextgis.com, то он меняется, новый пароль подходит, но у него так же нету прав.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/8340bdb80fe0e30810ba796a91bed758baa69f4f
