### ISSUE TITLE
Attributes not visible in identification popup when logged in as a non-administrator

### ISSUE THREAD

**Issue by mbandy** [nextgis/nextgisweb#639]
When logged in as an administrator, identification popups work as expected. Attributes are visible. 

However, when logged in as any other user, attributes are not visible in the popup. Attachments and descriptions are visible in the popup, **and attributes are visible in the feature table** - only missing from the popup. See below for views of the same feature popup while logged in as an administrator and a non-administrator. 

As administrator - 
![image](https://user-images.githubusercontent.com/25719119/42403550-1ba5c920-813f-11e8-8e6e-0dff2de78d3f.png)

As non-administrator - 
![image](https://user-images.githubusercontent.com/25719119/42403564-3ba5d0a8-813f-11e8-8a1b-0d896841de8f.png)

Any ideas?

**Comment by mbandy** [comment]
Yes, the non-administrative user has all read/write permissions. This is verified by the fact that all attributes are visible in the feature table (see image) - 

![image](https://user-images.githubusercontent.com/25719119/42466801-3646c63c-836d-11e8-9b31-daf75f9aa263.png)


I think the problem may be related to issue https://github.com/nextgis/nextgisweb/issues/448

**Comment by BishopGIS** [comment]
no feedback
