### ISSUE TITLE
Аутентификация пользователя в стороннем приложении

### ISSUE THREAD

**Issue by cfdbwrbq** [nextgis/nextgisweb#640]
Привет!
Возможно я не по адресу или не понимаю как все правильно готовить, но, подскажите, пожалуйста, где подсмотреть пример реализации аутентификации пользователя в десктопном приложении для подключения к NGW-серверу? 
Карта в приложении отображается с помощью QT QML QtLocation map plugin. Сейчас при подключении карты выдается ошибка 400 Bad Request, поскольку, все таки нужна аутентификация, а в Qt/QML/Osm-plugin ее как бы нет... 
Предполагается логин/пароль зашить в код, и показывать карту пользователю тайлами по локальной сети.
И если, я таки неправильно думаю, что более чем вероятно, то буду благодарен за наводку на юзкейс, как правильно подключиться к серверу. Спасибо!

**Comment by drnextgis** [comment]
Идея понятна?

```
$ http -v -a administrator:admin http://localhost:6544/api/component/auth/current_user
GET /api/component/auth/current_user HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic YWRtaW5pc3RyYXRvcjphZG1pbg==
Connection: keep-alive
Host: localhost:6544
User-Agent: HTTPie/0.9.2



HTTP/1.1 200 OK
Content-Length: 135
Content-Type: application/json
Date: Mon, 09 Jul 2018 09:50:19 GMT
Server: waitress

{
    "display_name": "Администратор", 
    "id": 4, 
    "keyname": "administrator"
}
```

**Comment by simgislab** [comment]
имейте в виду, что ваши вопросы - из области технической поддержки
вам сюда: http://nextgis.ru/pricing#ngw

**Comment by cfdbwrbq** [comment]
Ок, спасибо. 
Думаю, то, что нужно!
