### ISSUE TITLE
 Неизвестная ошибка 'CalledProcessError' в сериализаторе 'raster_layer', атрибут 'source'

### ISSUE THREAD

**Issue by cfdbwrbq** [nextgis/nextgisweb#641]
Привет всем!
не получается загрузить [растр ](https://yadi.sk/i/qmddjGJP3ZDPtc) (да и вообще никакой) в NGW, ни через Connect, ни через web-интерфейс. 
в Qgis(Arcgis) отображается, 4 канала, EPSG:3857, Тип данных | Byte — 8-битное беззнаковое целое

Пишет ошибку
>  Неизвестная ошибка 'CalledProcessError' в сериализаторе 'raster_layer', атрибут 'source'..
> 			URL: http://mapserver/api/resource/

freeze

> (env) gisolog@mapserver:~/ngw$ pip freeze
> Babel==2.6.0
> bunch==1.0.1
> certifi==2018.4.16
> chardet==3.0.4
> flufl.enum==4.1.1
> GeoAlchemy2==0.4.2
> geojson==2.4.0
> gunicorn==19.8.1
> hupper==1.3
> idna==2.7
> ipaddress==1.0.22
> lxml==4.2.1
> Mako==1.0.7
> mapscript==7.0.7
> MarkupSafe==1.0
> minio==4.0.0
> -e git+https://github.com/nextgis/nextgisweb.git@51a0180c3c75575322c85081ac623284723874bf#egg=nextgisweb
> -e git+https://github.com/nextgis/nextgisweb_mapserver.git@31d7585e01635488356cbd4db563a86f79734cb4#egg=nextgisweb_mapserver
> -e git+https://github.com/nextgis/nextgisweb_qgis.git@621b037839c97a9f6fc5b68b4dbe62b975a6613f#egg=nextgisweb_qgis
> numpy==1.14.5
> OWSLib==0.16.0
> passlib==1.7.1
> PasteDeploy==1.5.2
> Pillow==5.1.0
> plaster==1.0
> plaster-pastedeploy==0.5
> ply==3.11
> psycopg2==2.7.4
> pygdal==2.2.3.3
> Pygments==2.2.0
> pyproj==1.9.5.1
> pyramid==1.9.2
> pyramid-debugtoolbar==4.4
> pyramid-mako==1.0.2
> pyramid-tm==2.2
> python-dateutil==2.7.3
> pytz==2018.4
> repoze.lru==0.7
> requests==2.19.0
> Shapely==1.6.4.post1
> six==1.11.0
> SQLAlchemy==1.2.8
> transaction==2.2.1
> translationstring==1.3
> unicodecsv==0.14.1
> urllib3==1.23
> uWSGI==2.0.17
> venusian==1.1.0
> waitress==1.1.0
> WebOb==1.8.2
> zope.deprecation==4.3.0
> zope.interface==4.5.0
> zope.sqlalchemy==1.0

ps

> Jul 16 11:38:22 mapserver gunicorn[56836]: Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
> Jul 16 11:38:22 mapserver gunicorn[56836]: Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
> Jul 16 11:38:22 mapserver gunicorn[56836]: Input file size is 5308, 4607
> Jul 16 11:38:22 mapserver gunicorn[56836]: 0ERROR 4: Attempt to create new tiff file `/home/gisolog/ngw/data/raster_layer/88/3e/883ecb8826bb468b9123d4feae1314c8' failed: Too many levels of symbolic links
> Jul 16 11:38:22 mapserver gunicorn[56836]: CalledProcessError:
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/nextgisweb/nextgisweb/resource/api.py", line 202, in resource_exception_tween
> Jul 16 11:38:22 mapserver gunicorn[56836]:     response = handler(request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
> Jul 16 11:38:22 mapserver gunicorn[56836]:     reraise(*exc_info)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
> Jul 16 11:38:22 mapserver gunicorn[56836]:     response = handler(request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
> Jul 16 11:38:22 mapserver gunicorn[56836]:     response = _error_handler(request, exc)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 16, in _error_handler
> Jul 16 11:38:22 mapserver gunicorn[56836]:     reraise(*exc_info)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
> Jul 16 11:38:22 mapserver gunicorn[56836]:     response = handler(request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
> Jul 16 11:38:22 mapserver gunicorn[56836]:     view_name
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
> Jul 16 11:38:22 mapserver gunicorn[56836]:     response = view_callable(context, request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
> Jul 16 11:38:22 mapserver gunicorn[56836]:     return view(context, request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
> Jul 16 11:38:22 mapserver gunicorn[56836]:     return view(context, request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
> Jul 16 11:38:22 mapserver gunicorn[56836]:     return view(context, request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
> Jul 16 11:38:22 mapserver gunicorn[56836]:     result = view(context, request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
> Jul 16 11:38:22 mapserver gunicorn[56836]:     response = view(request)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/nextgisweb/nextgisweb/resource/api.py", line 316, in collection_post
> Jul 16 11:38:22 mapserver gunicorn[56836]:     serializer.deserialize()
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/nextgisweb/nextgisweb/resource/serialize.py", line 216, in deserialize
> Jul 16 11:38:22 mapserver gunicorn[56836]:     mobj.deserialize()
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/nextgisweb/nextgisweb/resource/serialize.py", line 178, in deserialize
> Jul 16 11:38:22 mapserver gunicorn[56836]:     sp.deserialize(self)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/nextgisweb/nextgisweb/resource/serialize.py", line 96, in deserialize
> Jul 16 11:38:22 mapserver gunicorn[56836]:     self.setter(srlzr, srlzr.data[self.attrname])
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/nextgisweb/nextgisweb/raster_layer/model.py", line 218, in setter
> Jul 16 11:38:22 mapserver gunicorn[56836]:     srlzr.obj.load_file(filedata, env)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/home/gisolog/ngw/nextgisweb/nextgisweb/raster_layer/model.py", line 113, in load_file
> Jul 16 11:38:22 mapserver gunicorn[56836]:     subprocess.check_call(cmd)
> Jul 16 11:38:22 mapserver gunicorn[56836]:   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
> Jul 16 11:38:22 mapserver gunicorn[56836]:     raise CalledProcessError(retcode, cmd)

**Comment by drnextgis** [comment]
Не знаю в чём у вас причина, но в облако загрузилось без проблем: http://rykovd.nextgis.com/resource/450/display

**Comment by cfdbwrbq** [comment]
symbolic links - меня сразу смутили...
после попытки залить растр по пути (например)
/home/gisolog/ngw/data/raster_layer/f5/44/f5447e55a13c40588ddbaf227aab9947
создается файл с каким-то странным содержанием

> HTTP/1.0 500 Perl execution failed
> Server: MiniServ/1.890
> Date: Wed, 18 Jul 2018 06:43:34 GMT
> Content-type: text/html; Charset=iso-8859-1
> Connection: close
> 
> <h1>Error - Perl execution failed</h1>
> <p>can't open /home/gisolog/ngw/data/raster_layer/3f/ae/3fae3a1d24a54d7ba0e2099253b4335d: Too many levels of symbolic links at /usr/share/webmin/filemin/download.cgi line 27.
> </p>
вот хоть убейте, не понимаю причем тут Webmin.
ладно, буду дальше копать, отпишусь.

**Comment by cfdbwrbq** [comment]
я бы сам за такое розгами по рукам, но...
в функции `workdir_filename` в файле `/home/gisolog/ngw/nextgisweb/nextgisweb/raster_layer/__init__.py`
просто добавил "0"
```
if not os.path.isfile(fname):
            os.symlink(oname, fname + '0')
```
как результат - растр загрузился. создано 2 файла и ссылка, с нулем в конце.

> -rw-r--r-- 1 gisolog gisolog 99097361 июл 30 13:19 0938fc9c680447bca9d510cceed6a1a6
> lrwxrwxrwx 1 gisolog gisolog       74 июл 30 13:19 0938fc9c680447bca9d510cceed6a1a60 -> /home/gisolog/ngw/data/raster_layer/09/38/0938fc9c680447bca9d510cceed6a1a6
> -rw-r--r-- 1 gisolog gisolog  4057122 июл 30 13:19 0938fc9c680447bca9d510cceed6a1a6.ovr

в общем, вот так.
