### ISSUE TITLE
Стили штриховки

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#65]
Если делать картостиль такой же как в QGIS, то у площадных слоёв не получается настраивать штриховку.
![image](https://f.cloud.github.com/assets/4630662/2017890/fef27d02-8803-11e3-9ee2-01925b0affa5.png)

Хотя конкретно этот вопрос наверное не особо важен.

**Comment by drnextgis** [comment]
auto-moving this issue to nextgis/nextgisweb_mapserver#9 and closing this one
