### ISSUE TITLE
Comments translation still needed

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#653]
nextgisweb/webmap/amd/ngw-webmap/Display.js
nextgisweb/webmap/amd/ngw-webmap/plugin/FeatureLayer.js
nextgisweb/webmap/amd/ngw-webmap/tool/Identify.js
nextgisweb/webmap/amd/ngw-webmap/ui/TinyDisplay/TinyDisplay.js

**Comment by dezhin** [comment]
Fixed in 4bddac3f626b846e76d52f10c4923057bdd9d993
