### ISSUE TITLE
 When saving the layer, it says that there is no Create 

### ISSUE THREAD

**Issue by iraqez** [nextgis/nextgisweb#687]
'NoneType' object has no attribute 'Create'
in: /package/nextgisweb/nextgisweb/feature_layer/api.py

def _ogr_memory_ds():
    return gdal.GetDriverByName(b'Memory').Create(
        b'', 0, 0, 0, gdal.GDT_Unknown)

**Comment by drnextgis** [comment]
This is due to an old version of GDAL. Upgrading GDAL should helps you.

**Comment by iraqez** [comment]
Thank you, this really solved my problem.
