### ISSUE TITLE
Export vector layer to geopackage

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#692]
![Снимок экрана от 2019-10-03 12-25-25](https://user-images.githubusercontent.com/4630662/66115148-ea69a700-e5d8-11e9-966c-2647d3d3a454.png)

Экспорт в DXF и Mapinfo - хорош, хочу такой же в GeoPackage.
Это позволит смотреть тяжёлые слои из ngw в qgis нажатием двух кнопок, а не девяти, как с Shapefile

**Comment by dezhin** [comment]
Implemented in 155429c65f44e6b015d6212e08c223817ac2eec2
