### ISSUE TITLE
Проблема вывода на печать аннотаций

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#693]
Не выводит длинные надписи. На печати они обрезаются по окну аннотации, а нужен вывод всей информации. Или расширение окна, или вывод полного текста ниже под картой.

![Снимок экрана 2019-10-04 в 12 21 41](https://user-images.githubusercontent.com/1708122/66196659-970f5b80-e6a1-11e9-9a42-d7c8f0c503d2.png)

**Comment by simgislab** [comment]
так есть же скрол?
