### ISSUE TITLE
Cyrrilics in CRS name breaks CRS creation

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#695]
1. Try creating new CRS with cyrrilics in the name:
`PROJCS["МСК 23 зона 1",GEOGCS["GCS_Pulkovo_1942",DATUM["D_Pulkovo_1942",SPHEROID["Krasovsky_1940",6378245.0,298.3]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Gauss_Kruger"],PARAMETER["False_Easting",1300000.0],PARAMETER["False_Northing",-4511057.628],PARAMETER["Central_Meridian",37.98333333333],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]`

It will produce useless error.

If 'МСК 23 зона 1' is changed to something in latin - CRS will be created.

**Comment by rendrom** [comment]
but it turned out that the above example is not supported by the proj4.js coordinate transformation on the client
