### ISSUE TITLE
Shift+drag zooming sets up incorrect scale in landscape view

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#700]
1. Visit http://espartest.nextgis.com/resource/180/display?base=basemap_0&lon=59.0375&lat=53.3985&angle=0&zoom=12&styles=272
2. Switch to print
3. Shift+drag to zoom to 6

Result - the rectangle doesn't fit.

Possible related to #698 i.e. the correct zoom can't get selected.

Actual, for example:
![before_700](https://user-images.githubusercontent.com/669999/67952869-0f186500-fbff-11e9-86b5-623f085f0452.gif)

**Comment by karavanjo** [comment]
Implemented.

![after_700](https://user-images.githubusercontent.com/669999/67952918-29ead980-fbff-11e9-9450-5ea95367f38e.gif)

**Comment by simgislab** [comment]
nice!

**Comment by karavanjo** [comment]
- Add caption to scale selector:
![image](https://user-images.githubusercontent.com/669999/68018511-5dcf0900-fcaa-11e9-8ff4-7e69349e4de4.png)

- Align buttons by left

**Comment by simgislab** [comment]
new text

```Use Shift+drag for box zooming
Используйте Shift+мышь для увеличения рамкой```

**Comment by simgislab** [comment]
works good
