### ISSUE TITLE
Админка коллектора: поиск работает только по e-mail, а по фамилии не работает

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#702]
⏸
![Снимок экрана от 2019-11-08 17-20-22](https://user-images.githubusercontent.com/4630662/68483161-187f7e00-024c-11ea-87dc-9573f280bab1.png)
хотя может это и не важно, на это ссылается учебный материал

**Comment by dezhin** [comment]
![image](https://user-images.githubusercontent.com/237320/171487516-c4a1fd5e-f9cb-491f-9e12-0a3dbcbe6fe1.png)

Сейчас это так и работает.
