### ISSUE TITLE
Ability to add copyrights information while adding non-QMS basemap

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#707]
Currently basemap copyrights for a Web map are taken from QMS-based basemaps that include copyright information. [Example](https://qms.nextgis.com/geoservices/448/).

There is no way to add copyrights if a user uses custom (non-QMS) URL to some TMS service.

**Comment by dezhin** [comment]
Here's the way:

![image](https://user-images.githubusercontent.com/237320/141744422-360ef372-5c76-48c2-8e33-b9b88899f329.png)
