### ISSUE TITLE
Identification ignores records over 10 limit

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#708]
1. Create a map with a layer that has over 10 intersecting features. I.e. there are 10+ features present at one point

2. Click in the interscetion area (identify)

Current result: 10 features are selectable through the selector
Expected result: 10+ features are selectable through the selector

[example-11records.zip](https://github.com/nextgis/nextgisweb/files/3966766/example-11records.zip)

![](http://m-d.me/img/ss/20191216_114525.png)

![](http://m-d.me/img/ss/20191216_114556.png)

**Comment by simgislab** [comment]
not a bug, but we need to do something about this

**Comment by dezhin** [comment]
Do we have to show all features (which is technically hard)? Or we need to show that there are more than ten features and only ten are shown?

**Comment by simgislab** [comment]
we need to start from design here

**Comment by simgislab** [comment]
increased to a hundred
