### ISSUE TITLE
Highlight feature in search panel

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#709]
Currently in search pane two sources used:

- vector layer attributes
- nominatim

Both sources return geometry of found features. It's expected to zoom in (implemented) and highlight feature (not implemented).  This is consistent with feature highlight in attribute table.

For nominatim API should be:

```
https://nominatim.openstreetmap.org/search?q=%D0%A1%D0%B5%D0%B2%D0%B5%D1%80%D0%BE-%D0%9A%D0%B0%D0%B2%D0%BA%D0%B0%D0%B7%D1%81%D0%BA%D0%B8%D0%B9%20%D1%84%D0%B5%D0%B4%D0%B5%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%BE%D0%BA%D1%80%D1%83%D0%B3&format=geojson&polygon_geojson=1
```  

polygon_geojson=1 - returns geometry

**Comment by dezhin** [comment]
https://app.clickup.com/t/pv9ut6
https://app.clickup.com/t/pv9va8
