### ISSUE TITLE
Документация (en): 2.11.1. Install in Ubuntu — virtualenv

### ISSUE THREAD

**Issue by kethertiphereth** [nextgis/nextgisweb#727]
> Install virtualenv:
>
> $ sudo pip install virtualenv

Virtualenv установлен, идем дальше, создаем виртуальную среду:

> virtualenv: error: unrecognized arguments: --no-site-packages

Оказывается, что с 20-ой версии virtualenv эта опция убрана, и нужно ставить более раннюю версию, чем 20 версия.

Почему это не отражено в документации?

**Comment by dezhin** [comment]
Действительно некоторые моменты в документации потеряли актуальность. Обновленная документация размещена тут - https://docs.nextgis.com/docs_ngweb_dev/doc/admin/install.html - там есть еще ряд белых пятен, но на ваш вопрос она отвечает.
