### ISSUE TITLE
Документация (ru): 13.1.3 Create resource — Feature in vector or PostGIS layer

### ISSUE THREAD

**Issue by kethertiphereth** [nextgis/nextgisweb#729]
Я даже не знаю, считать это за issue, или нет 

Содержание json'а в запросе немного смущает, на фоне всей остальной документации
 
![Screenshot_4](https://user-images.githubusercontent.com/44239176/77442491-8099bf80-6dfb-11ea-87bb-57aedd247004.png)

Ссылка на документацию: https://docs.nextgis.ru/docs_ngweb_dev/doc/developer/create.html#feature-in-vector-or-postgis-layer

**Comment by dezhin** [comment]
Что конкретно смущает?
