### ISSUE TITLE
Документация (ru): 13.1.3 — Batch create features in vector layer

### ISSUE THREAD

**Issue by kethertiphereth** [nextgis/nextgisweb#730]
Еще раз открываю issue (связано с #728): 

Что ожидалось:

![image](https://user-images.githubusercontent.com/44239176/77448954-76c78a80-6e02-11ea-9211-5f80ccc5916a.png)

Что в документации:

![Screenshot_3](https://user-images.githubusercontent.com/44239176/77441995-2993ea80-6dfb-11ea-8979-543a8dbf4128.png)

**Comment by BishopGIS** [comment]
@kethertiphereth 

1. Не надо открывать новые тикеты на ту же тему - просто переоткройте имеющийся если проблема не решена.
2. В документации все исправлено. Поробуйте перезагрузить страницу с очисткой кэша браузера. У меня выглядит вот так:

![Снимок экрана 2020-03-24 в 19 42 20](https://user-images.githubusercontent.com/1708122/77452932-97461380-6e07-11ea-907d-1acafc103a66.png)
