### ISSUE TITLE
installation docs and self hosting license

### ISSUE THREAD

**Issue by gotjoshua** [nextgis/nextgisweb#731]
I see that the docs for installation have not been updated in quite some time.

Before I step in and try everything, I want to check are these the most up to date docs available:  
https://github.com/nextgis/docs_ngweb/blob/en/source/install-ubuntu.rst

??

Also, Do you support / allow / encourage users to run their own instances of nextgisweb?
As you are selling SAAS plans on nextgis.com, I thought it best to check before investing too much effort.

Many thanks for what appears to be a truly amazing open souce project!

**Comment by simgislab** [comment]
We certainly do allow it and we know people install it.

However we can't offer much support. We're a small company and we don't have resources for community bulding and such. Despite being open source for years we don't see much interest from outside.

**Comment by gotjoshua** [comment]
Thanks!  
Can anyone confirm that the current installation docs are up to date?

**Comment by dezhin** [comment]
No. Current installation docs are outdated in some aspects. But we're working on documentation here - https://docs.nextgis.com/docs_ngweb_dev/doc/admin/install.html. It have some white spots but it's more compact and up-to-date.
