### ISSUE TITLE
Не работает инструмент идентификации если стилем смещены маркеры объектов

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#735]
Веб-карта http://gis-naturalist.nextgis.com/resource/666/display

В слое "Точки встреч" при клике по объекту не всплывает окно с атрибутами объекта.

При этом клик по другим векторным слоям - всплывает окно с атрибутами объекта.

Таблица объектов проблемного слоя открывается.

ресурс - источник слоя с описанной проблемой http://gis-naturalist.nextgis.com/resource/664

Стиль отображения слоя был "Уникальные значения", тип геометрии - точка.

Слои у которых нет проблем с идентификацией объектов: 
"Квартальная сеть" - полигоны, стиль отображения Обычный знак
"Количество встреч в кварталах" - полигоны -  Градуированный знак.

слои и стили всех слоев созданы в QGIS 3.4.13-Madeira и добавлены в веб-гис через веб-интерфейс.

Все слои добавленные на данную веб-карту лежат здесь: http://gis-naturalist.nextgis.com/resource/658

**Comment by simgislab** [comment]
просьба сделать отдельную чистую карту с отдельным слоем который не идентифицируется

если проблема сохранится, просьба приложить архив со слоем сюда

**Comment by ABiatov** [comment]
Создал карту, на которую добавил этот слой с разными стилями

http://gis-naturalist.nextgis.com/resource/680/display

Идентификация не работает только в слое "Точки - уникальные значения - v1"
http://gis-naturalist.nextgis.com/resource/665

а в слое "Точки - уникальные значения - v2" работает
http://gis-naturalist.nextgis.com/resource/682

Отличие между этими стилями оказалось, что в стиле где не работает идентификация,  в QGIS в настройках значка "якорь" указан "внизу".

Изменил "якорь" на "Верт. центр" и такой файл стилей добавил в веб-гис. И идентификация по слою заработала.

**Comment by ABiatov** [comment]
![изображение](https://user-images.githubusercontent.com/13443276/85567372-775a0200-b639-11ea-8561-93bf5f0f5ee2.png)

**Comment by simgislab** [comment]
возможно дело в том, что из-за смещения маркера стилем в него просто не получается попасть

**Comment by ABiatov** [comment]
да, походу в этом деле.

Думаю, что это issue можно закрывать
