### ISSUE TITLE
на веб-карте не отображаются подписи объектов, при загрузке файла стилей созданном в QGIS 3

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#736]
на веб-карту добавлен слой и стиль в котором настроено отображение подписей из атрибута, при этом подписи не отображаются.

веб-карта
http://gis-naturalist.nextgis.com/resource/666/display
Слой "Квартальная сеть"

Ресурс стиля http://gis-naturalist.nextgis.com/resource/662

Слой создан из geojson файла созданного в QGIS 3. 
Стиль слоя также создан в QGIS 3, сохранен в QML формате и загружен в веб-гис через браузер.

Проблема воспроизводится и на других веб-картах и слоях.

**Comment by simgislab** [comment]
это ожидаемо

NGW работает на QGIS2, стили QGIS3 использовать можно, но они должны быть совместимы с 2. Какие именно особенности стиля ломают совместимость - не подскажем.
