### ISSUE TITLE
Do not let to go outside of map's extent

### ISSUE THREAD

**Issue by Romchik93** [nextgis/nextgisweb#738]
In the map settings, make a function (checkbox) that would not allow to go outside of extend, if one is defined.

**Comment by dezhin** [comment]
https://openlayers.org/en/latest/examples/extent-constrained.html

**Comment by dezhin** [comment]
Случайно закрыл, ссылка вдруг пригодиться.

**Comment by drnextgis** [comment]
In order to implement this we have to upgrade OpenLayers to v6: https://github.com/openlayers/openlayers/pull/9137

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/33e00f6dbc0c84eb89b24164643c161a147f3dbc
