### ISSUE TITLE
Remove broken link on G+

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#739]
Google plus is not working now. 

![Снимок экрана 2020-08-15 в 00 00 58](https://user-images.githubusercontent.com/1708122/90292450-92533080-de8a-11ea-9a50-46918c19e772.png)

![Снимок экрана 2020-08-15 в 00 03 18](https://user-images.githubusercontent.com/1708122/90292599-de9e7080-de8a-11ea-827f-1f1b455f7509.png)

**Comment by dezhin** [comment]
Убрал.
