### ISSUE TITLE
Изменить разделитель при экспорте слоя в csv-формат на точку с запятой (;)

### ISSUE THREAD

**Issue by Romchik93** [nextgis/nextgisweb#740]
Сейчас экспортирует, разделяя запятой.
Excel при открытии этого csv выбора не предоставляет и кладет все данные в одну ячейку
А при ";" сразу открывает с правильным разбитием, проверили

**Comment by Romchik93** [comment]
https://support.nextgis.com/#ticket/zoom/405

**Comment by dezhin** [comment]
https://app.clickup.com/t/buv85v

**Comment by dezhin** [comment]
Добавили отдельный пункт "CSV for Microsoft Excel"
