### ISSUE TITLE
Мелкая ошибка при установке 

### ISSUE THREAD

**Issue by desertwolf7** [nextgis/nextgisweb#744]
Nextgis Web 3.6.0dev0
FreeBSD 11.3 x86
Python 3.7.9

При запуске env/bin/pip install -e ./nextgisweb, процесс вылетает при установке zope.interface. Проблема в том, что версия 4.4.0 использует depricated api setuptools, которое начиная с версии 46.0.0 было удалено. Пока проблему решил так:
```
--- a/setup.py
+++ b/setup.py
@@ -21,7 +21,7 @@ requires = [
     'pyramid_debugtoolbar==4.5.1',
     'pyramid_mako==1.0.2',
     'zope.sqlalchemy==1.1',
-    'zope.interface==4.6.0',
+    'zope.interface>4.6.0',
     'zope.event',
     'bunch==1.0.1',
     'flufl.enum==4.1.1',
```
Установилось zope.interface 5.1.2. Пока работает без замечаний.

**Comment by dezhin** [comment]
Поменяли на < 5 в зависимостях.
