### ISSUE TITLE
Ошибка отображения TMS слоя созданного на базе TMS подключения. (Кварталы ПКК с geoservices).

### ISSUE THREAD

**Issue by pamfilov** [nextgis/nextgisweb#745]
На определённом масштабе Кварталы ПКК улетают на восток относительно базовой карты OSM.

```http://pamfilov.nextgis.com/resource/1/display?base=basemap_0&lon=66.9268&lat=65.5984&angle=0&zoom=3&styles=3,8```

Ситуация воспроизведена на pamfilov.nextgis.com

**Comment by dezhin** [comment]
Готово.
