### ISSUE TITLE
QML растрового QGIS стиля ведет на 404 в GUI

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#749]
Не важно авторизован или нет.

Пример: 

https://demo.nextgis.com/resource/4941

https://demo.nextgis.com/api/resource/4941/qml

И выглядит по другому чем у векторного. Растровый:

![](http://m-d.me/img/ss/20201203_203258.png)

Векторный:

![](http://m-d.me/img/ss/20201203_203349.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb_qgis/commit/099445f4d0157d04f8f595abc04b6dd227e90734
