### ISSUE TITLE
Возможно создание атрибутов векторного поля с одинаковыми keyname

### ISSUE THREAD

**Issue by pamfilov** [nextgis/nextgisweb#750]
Возможно создание атрибутов векторного поля с одинаковыми именами.

![image](https://user-images.githubusercontent.com/8543523/101664885-68d39b80-3a5d-11eb-9c3a-c92acd56411a.png)

Ожидается, что будет создано уведомление, что не может быть создано второе поле с таким же keyname

**Comment by edpop** [comment]
Fixed in https://github.com/nextgis/nextgisweb/commit/38ffb9f3f710010ebd18471b787a16b5ee90d588
