### ISSUE TITLE
Проблемы редактирования слоя добавляемого по WFS

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#757]
Есть слой https://abspatial.nextgis.com/resource/41
Добавил этот слой в WFS сервис https://abspatial.nextgis.com/resource/85
Добавил этот слой в NG QGIS при помощи NG Connect, кликнув по стилю и нажав  "Add to QGIS"
Слой добавился и отобразился корректно:

![изображение](https://user-images.githubusercontent.com/13443276/110205107-4ba54200-7e7f-11eb-8b57-f062d592f5b0.png)

Добавил этот же слой подключенный в WFS при помощи NG Connect. Выделив соответсвующий сервис  и нажав  "Add to QGIS".
Слой добавился. Также добавились другие слои подключенные в этот WFS-сервис.
Все слои визуально отображаются корректно.

![изображение](https://user-images.githubusercontent.com/13443276/110205346-22d17c80-7e80-11eb-8d00-81d757727c3e.png)

Включаю редактирование этого слоя.

Делаю любое изменение, на пример двигаю узлы какого-то объекта.

Жму дискетку "сохранить изменения" и получаю ошибку: "Не удалось внести изменения в слой Выработки очистные".

![изображение](https://user-images.githubusercontent.com/13443276/110205394-5d3b1980-7e80-11eb-9f91-1b841612d4fe.png)

Нажал ссылку "Ошибки" и вижу сообщение:
```
Не удалось внести изменения в слой Выработки очистные
Ошибки: ОШИБКА: не изменена 1 геометрия.
```

![изображение](https://user-images.githubusercontent.com/13443276/110205469-ba36cf80-7e80-11eb-9ef4-3cb568539d1f.png)

При этом в другие слои из этого же WFS-сервиса, на пример в слой https://abspatial.nextgis.com/resource/39 изменения сохраняются.

**Пробую другим путем**

Добавляю этот WFS-сервис классическим путем "Добавить слой WFS".

Создаю соединение с сервером, логинюсь как администратор.
Выбираю этот проблемный слой (resource 41) и жму "Добвить" и тут получаю неожиданное:

![изображение](https://user-images.githubusercontent.com/13443276/110205634-ca02e380-7e81-11eb-9f1d-e5e82f59b771.png)

И тут уже не про какое редактирование не может быть и речи.

При этом другой слой из этого же сервис (resource 39) отображается корректно и даже правки вносятся и сохраняются на сервере.

![изображение](https://user-images.githubusercontent.com/13443276/110205740-89f03080-7e82-11eb-9483-32d6814e6352.png)

В чем может быть проблема?

И как ее решать?

**Comment by simgislab** [comment]
дело в том что слой - Multipolygon Z, WFS такое редактировать не умеет
