### ISSUE TITLE
Игнорируется настройка количества фич для WFS

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#758]
1. Создать WFS-сервис, ограничение 1000 фич
2. Подключить в QGIS

Результат: загружаются все фичи, больше 1000, ограничение игнорируется

Пример сервиса:
https://demo.nextgis.com/resource/5097 (10к+ фич в источнике, ограничение стоит).

https://github.com/nextgis/nextgisweb/blob/29d8f0f62827bb98dadf715c9d159b6e2bf8d5df/nextgisweb/wfsserver/model.py#L42

**Comment by edpop** [comment]
Исправлено https://github.com/nextgis/nextgisweb/commit/2d565a7f948bed28c1df1b5e705c6876314e134a
