### ISSUE TITLE
Removing custom CRS breaks measurements on Web map

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#759]
Steps to replicate:

1. Create custom CRS
2. Assign it for measurements on the Web map
3. Remove custom CRS

Result:
1. Control panel shows that Lat/long got assigned as CRS for measurements -> GOOD
2. Measurements on the map completely stop working -> BAD

Example Web GIS with this effect:
https://demo.nextgis.com/resource/4041/display?panel=layers

Stupid solution. Go to control panel and click save again.
Expected behaviour. CRS removal should trigger correct assignment of default CRS.

**Comment by edpop** [comment]
Fixed in https://github.com/nextgis/nextgisweb/commit/c053bcafe1f67fd36632c8b247c78512eace67e1
