### ISSUE TITLE
Не удаётся загрузить слой в NGW: ошибка связанная с геометриями

### ISSUE THREAD

**Issue by MikhanGusev** [nextgis/nextgisweb#761]
Проверяю средствами QGIS валидность геометрий слоя - всё хорошо. Загружаю слой через Connect. В ответ возвращается:

{
    "title": "Validation error",
    "message": "Векторный слой не может быть записан из-за ошибок.",
    "detail": "Объект #1 содержит несколько геометрий, удовлетворяющих условиям.Объект #2 содержит несколько геометрий, удовлетворяющих условиям.Объект #3 содержит несколько геометрий, удовлетворяющих условиям.Объект #4 содержит несколько геометрий, удовлетворяющих условиям.Объект #5 содержит несколько геометрий, удовлетворяющих условиям.Объект #6 содержит несколько геометрий, удовлетворяющих условиямОбъект #7 содержит несколько геометрий, удовлетворяющих условиям.Объект #8 содержит несколько геометрий, удовлетворяющих условиям.Объект #9 содержит несколько геометрий, удовлетворяющих условиям.Объект #10 содержит несколько геометрий, удовлетворяющих условиям.",
    "exception": "nextgisweb.core.exception.ValidationError",
    "status_code": 422,
    "data": {
        "attribute": "source",
        "serializer": "vector_layer"
    },
    "guru_meditation": "007cb50f014a7dc2dd49564a61ede436"
}

Слой:
[data.zip](https://github.com/nextgis/nextgisweb/files/6478008/data.zip)

**Comment by edpop** [comment]
Fixed in https://github.com/nextgis/nextgisweb/commit/54fe0418535f4ce85b4591624aa964b69ca9f487
Дело было в том, что Shapefile отдавал ложную информацию по поводу типа геометрии. Теперь определяем её вручную, если загрузка идёт из этого формата.
