### ISSUE TITLE
Уведомление о сохраните правок описания векторных объектов

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#763]
1. Захожу в векторный слой
2. Открываю его таблицу
3. Выбираю нужный объект
4. Нажимаю кнопку "Редактировать" 
5. Объект открывается на новой вкладке браузера
6. Перехожу на вкладку "описание"
7. Правлю описание
8. Жму кнопку "Сохранить" и на этом шаге сохраняет, но никакого уведомления об успешном сохранении не происходит. Что неудобно и не понятно, сохранило ли или нет.
Если я открою описание этого объекта заново через веб-карту или таблицу, то вижу что сохранилось.

Но для удобства пользования нехватает какого-то уведомления "Правки сохранены" или чего-то подобного, сразу после нажатия кнопки "Сохранить"

**Comment by dezhin** [comment]
Сделали аналогично редактированию ресурсов, форма и кнопка блокируется.
