### ISSUE TITLE
фильтр объектов провайдера в стиле QML и вывод на карту

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#764]
1. создал векторный полигональный слой
2. опубликовал в вебгис со стилем без фильтра
3. создал слой фильтр объектов провайдера в NEXTGIS QGIS в стиле слоя и сохранил в QML.
4. добавил этот стиль к слою в веб-гис
5. добавил стили без фильтра и с фильтром на веб-карту
и в итоге на карте **Фильтр не работает**

Было бы очень удобно если бы фильтр объектов провайдера работал в NGW 

карта
https://abspatial.nextgis.com/resource/497/display?panel=layers

стиль без фильтра
https://abspatial.nextgis.com/resource/494

стиль с фильтром
https://abspatial.nextgis.com/resource/495

**Comment by ABiatov** [comment]
файл стиля
[buildings_rekonstrukcia.zip](https://github.com/nextgis/nextgisweb/files/6994517/buildings_rekonstrukcia.zip)

**Comment by dezhin** [comment]
Обсудили в чатике - это ожидаемое поведение. Про идентификацию где-то тут есть отдельный тикет.
