### ISSUE TITLE
REST API. Поиск ресурса 

### ISSUE THREAD

**Issue by Bagrutdinov** [nextgis/nextgisweb#765]
Версия 3.9.1. Поиск ресурса осуществляется очень медленно (более секунды даже в пустой базе). 
Используется метод GET /api/resource/search/?(string:key1)=(string:value1)&(string:key2)=(string:value2).
Поиск осуществляется по ключу display_name.
В более ранних версиях работало все быстро.

**Comment by dezhin** [comment]
Пожалуйста приведите пример запроса, который выполяется долго на пустой базе. Аналогичный запрос выполняется так же долго на sandbox.nextgis.com? Вот такой запрос например практически моментально обрабатывается https://sandbox.nextgis.com/api/resource/search/?display_name=Examples
