### ISSUE TITLE
missing functionalities

### ISSUE THREAD

**Issue by SunucuKomutani** [nextgis/nextgisweb#766]
Hi,

I have just setup NextGIS on my local ubuntu by following this document (https://docs.nextgis.com/docs_ngweb_dev/doc/admin/install.html). The setup goes well except some warnings about webpack (which I learnt here that it is not very important or not the possible cause of my problem, but I added the message at the end of this email anyway). 

After the setup, I can easily run and access to NextGIS but 
1) When I add a layer I do not see style options (neither Mapserver nor qGIS)
2) When I add the layer I cannot use them in a map because layers are there in the list but cannot be added to a map. They are all childelement of the top resource folder. 
3) I tried fresh setup with master and branch 3.9.1, both ended up same. 

Can anyone help?
SK

The webpack warnings are:

[3/4] Linking dependencies...
warning "workspace-aggregator-8ee0ea98-4794-4acc-831c-10170855cc00 > @nextgisweb/stylesheet > css-minimizer-webpack-plugin@2.0.0" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-8ee0ea98-4794-4acc-831c-10170855cc00 > @nextgisweb/stylesheet > mini-css-extract-plugin@1.6.2" has unmet peer dependency "webpack@^4.4.0 || ^5.0.0".
warning "workspace-aggregator-8ee0ea98-4794-4acc-831c-10170855cc00 > @nextgisweb/external > buble-loader@0.5.1" has unmet peer dependency "webpack@*".
warning "workspace-aggregator-8ee0ea98-4794-4acc-831c-10170855cc00 > @nextgisweb/external > string-replace-loader@3.0.3" has unmet peer dependency "webpack@^5".
[4/4] Building fresh packages...
success Saved lockfile.

**Comment by SunucuKomutani** [comment]
Two small notes to add:
a) I also do not see Basemap option in the Create Resources list
b)After adding the layers, preview actually works, but that is it.

**Comment by drnextgis** [comment]
Hi! You have to install additional packages:

1) https://github.com/nextgis/nextgisweb_qgis (for QGIS-based tyles)
2) https://github.com/nextgis/nextgisweb_mapserver (for MapServer-based styles)

**Comment by SunucuKomutani** [comment]
OK. Do I have to install before or after I install the nextgisweb?

**Comment by drnextgis** [comment]
After.

**Comment by dezhin** [comment]
You have to install them during the installation. To be precise:

![image](https://user-images.githubusercontent.com/237320/134863236-3431d585-9275-4085-b8d7-3af3648d2c6a.png)
