### ISSUE TITLE
add Bookmarks name on webmap

### ISSUE THREAD

**Issue by ABiatov** [nextgis/nextgisweb#770]
В настройках карты при выборе векторного слоя пространственных закладок "Bookmark resource" добавить выбор атрибутивного поля от куда брать текст для отображения имен закладок.

Сейчас при создании пространственных закладок получаются безликие закладки с номерами 1, 2, 3...

**Comment by simgislab** [comment]
Попробуй установить в слое использующемся для закладок атрибут наименования. Это подтянется в качестве названий закладок.

**Comment by ABiatov** [comment]
Спасибо, все получилось.
Что-то я отстал от ваших обновлений в последнее время.

**Comment by simgislab** [comment]
да, нового много
догоняй, мы поможем
