### ISSUE TITLE
Debug mode with pycharm

### ISSUE THREAD

**Issue by vherbst** [nextgis/nextgisweb#771]
I try to develop a module for nextgisweb and can't quite figure out how to debug. I could install but when I run pserve with a development.ini file it starts the server but the references are broken so that css files etc. cant be loaded. When I start with command line the compiled package (nextgisweb server) it does work. I also read the old thread concerning a Dockerfile. I would love to have a look at this as well. Thanks in advance... Volkmar

**Comment by dezhin** [comment]
We don't use pserve anymore, but it should work if configured correctly.  I'm not very familiar with PyCharm, but let's try to figure it out. If PyCharm is unable to debug Python console scripts directly (which `nextgisweb server` is), it'll be possible to create a wrapper script and debug it. So, try to create `launch.py` with the following contents:

```python
from nextgisweb.script import main
main()
``` 

And debug it as an regular Python script adding `server` to command line options.
