### ISSUE TITLE
Проблемы с установкой nextgisweb_qgis

### ISSUE THREAD

**Issue by Bagrutdinov** [nextgis/nextgisweb#776]
nextgisweb 4.4.0
nextgisweb_qgis 2.8.0

На этапе установки QGIS Headless Rendering, в котором требуется выполнить команду **pip install --editable ./[tests]** возникает ошибка:
/srv/ngw/package/nextgisweb_qgis/qgis_headless/src/lib/style.cpp:34:10: fatal error: qgslinesymbol.h: No such file or directory

**Comment by dezhin** [comment]
Скорее всего что-то с установкой QGIS, или он слишком старый, или нет необходимых пакетов. Что-то более определенное тут трудно сказать, для этого мало информации.
