### ISSUE TITLE
После установки не могу создать слой

### ISSUE THREAD

**Issue by iDevPro** [nextgis/nextgisweb#777]
```
/model.py:304: SAWarning: Object of type <QgisVectorStyle> not in session, add operation along 'Resource.children' will not proceed if q.scalar() == 0:
```

Не создается слой

Система:
- Debian 12.2

Дополнительно:
- Инструкция по которой ставил nextgis... допиливал по обстоятельствам [NextGIS.md](https://github.com/nextgis/nextgisweb/files/14257718/NextGIS.md)

**Comment by dezhin** [comment]
Сложно что-то определенное сказать по имеющейся информации. Ворнинг который вы привели возможно не связан с проблемой с которой вы столкнулись.
