### ISSUE TITLE
Ссылка на пользовательское соглашение

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb#80]
Если использовать веб-гис в качестве портала открытых данных, то наверняка понадобится возможность размещения ссылки на какую-нибудь страницу с пользовательским соглашением.

**Comment by drnextgis** [comment]
@Kinda-me ты понимаешь про что это?

**Comment by Kinda-me** [comment]
Да, понимаю, но для этого у нас другой репозиторий. Думаю, здесь можно закрывать.
