### ISSUE TITLE
Возможность откреплять и прикреплять вкладки таблицы атрибутов в карте 

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb#93]
Не уверен, что нужно именно откреплять. По мне, достаточно сделать стандартный layout как на скриншоте в тикете #68. Только еще место на легенду предусмотреть, а потом просто включать или отключать видимость того или иного элемента по желанию пользователя или при активации инструмента (меню). 
По мотивам этого тикета: https://github.com/nextgis/nextgisweb/issues/68

**Comment by drnextgis** [comment]
@BishopGIS, сейчас таблица атрибутов открывается снизу карты, можно закрывать?

**Comment by BishopGIS** [comment]
Да!
